import Link from "next/link";
import { redirect } from "next/navigation";
import { AppShell } from "@/components/app-shell";
import { PageHeader } from "@/components/page-header";
import { getViewer } from "@/lib/auth/viewer";
import { createClient } from "@/lib/supabase/server";
import { createTenant, deleteEmptyTenant, enterTenantWorkspace, updateIndustryTemplateVisibility, updateTenant } from "./actions";
import "./platform.module.css";

type TenantRow = { id: string; name: string; status: string; is_internal_demo: boolean; subscription_status: string; industry_template: { id: string; name: string } | null };
type TemplateRow = { id: string; name: string; is_enabled: boolean; is_internal_only: boolean; is_public_demo_visible: boolean; is_available_during_signup: boolean };

export default async function PlatformAdminPage() {
  const viewer = await getViewer();
  if (viewer?.role !== "platform_owner") redirect("/admin");
  const supabase = await createClient();
  const [{ data: tenants }, { data: templates }] = await Promise.all([
    supabase.from("organizations").select("id,name,status,is_internal_demo,subscription_status,industry_template:industry_templates!organizations_industry_template_id_fkey(id,name)").order("name"),
    supabase.from("industry_templates").select("id,name,is_enabled,is_internal_only,is_public_demo_visible,is_available_during_signup").order("name"),
  ]);
  const tenantRows = (tenants || []) as unknown as TenantRow[];
  const templateRows = (templates || []) as TemplateRow[];
  return <AppShell title="Platform Admin"><PageHeader eyebrow="RunFloor platform" title="Tenants & Industry Templates" description={`Viewing: ${viewer.organizationName}. Platform changes are separate from tenant administration.`}/>
    <section className="card"><h2>Create tenant</h2><p>Create an isolated workspace from a selected industry template. This does not copy BGC data.</p><form action={createTenant} className="grid grid-2"><input className="input" name="name" required minLength={2} maxLength={120} placeholder="Company or demo tenant name"/><select className="input" name="templateId" required defaultValue=""><option value="" disabled>Choose industry template</option>{templateRows.filter((template) => template.is_enabled).map((template) => <option key={template.id} value={template.id}>{template.name}</option>)}</select><label><input type="checkbox" name="isInternalDemo"/> Internal demo tenant</label><button className="btn btn-primary">Create tenant</button></form></section>
    <section className="card"><h2>Tenants</h2><p>Archiving a tenant prevents it from being opened as the active platform workspace while preserving its users and business data. Reassigning an industry does not overwrite that tenant’s existing content.</p><div className="table-wrap"><table className="table"><thead><tr><th>Tenant</th><th>Industry</th><th>Plan</th><th>Status</th><th>Visibility</th><th>Actions</th></tr></thead><tbody>{tenantRows.map((tenant) => <tr key={tenant.id}><td><form action={updateTenant} style={{display:"flex",gap:8,alignItems:"center",flexWrap:"wrap"}}><input type="hidden" name="tenantId" value={tenant.id}/><input className="input" name="name" defaultValue={tenant.name} aria-label={`${tenant.name} name`}/><select className="input" name="templateId" defaultValue={tenant.industry_template?.id || ""} aria-label={`${tenant.name} industry template`} required><option value="" disabled>Choose industry</option>{templateRows.filter((template) => template.is_enabled).map((template) => <option key={template.id} value={template.id}>{template.name}</option>)}</select><select className="input" name="subscriptionStatus" defaultValue={tenant.subscription_status} aria-label={`${tenant.name} subscription`}><option value="trial">Trial</option><option value="active">Active</option><option value="past_due">Past due</option><option value="suspended">Suspended</option><option value="cancelled">Cancelled</option></select><select className="input" name="status" defaultValue={tenant.status} aria-label={`${tenant.name} tenant status`}><option value="active">Active</option><option value="suspended">Archived</option></select><button className="btn btn-ghost">Save tenant</button></form></td><td>{tenant.industry_template?.name || "Unassigned"}</td><td>{tenant.subscription_status}</td><td>{tenant.status === "suspended" ? "Archived" : tenant.status}</td><td>{tenant.is_internal_demo ? "Internal only" : "Customer tenant"}</td><td><form action={enterTenantWorkspace}><input type="hidden" name="organizationId" value={tenant.id}/><button className="btn btn-ghost" disabled={tenant.status !== "active"}>Enter workspace</button></form><details><summary>Delete empty tenant</summary><form action={deleteEmptyTenant}><input type="hidden" name="tenantId" value={tenant.id}/><input className="input" name="confirmation" placeholder={`Type ${tenant.name}`} aria-label={`Confirm deletion of ${tenant.name}`}/><button className="btn btn-ghost">Delete permanently</button></form></details></td></tr>)}</tbody></table></div></section>
    <section className="card"><h2>Industry Templates</h2><p>Internal-only templates are automatically excluded from public demos and signup.</p><div className="table-wrap"><table className="table"><thead><tr><th>Template</th><th>Enabled</th><th>Internal only</th><th>Public demo</th><th>Signup</th><th></th></tr></thead><tbody>{templateRows.map((template) => <tr key={template.id}><td><Link href={`/admin/platform/templates/${template.id}`}>{template.name}</Link></td><td>{template.is_enabled ? "Yes" : "No"}</td><td>{template.is_internal_only ? "Yes" : "No"}</td><td>{template.is_public_demo_visible ? "Yes" : "No"}</td><td>{template.is_available_during_signup ? "Yes" : "No"}</td><td><form action={updateIndustryTemplateVisibility} style={{display:"flex",gap:8}}><input type="hidden" name="templateId" value={template.id}/><label><input type="checkbox" name="isEnabled" defaultChecked={template.is_enabled}/> Enabled</label><label><input type="checkbox" name="isInternalOnly" defaultChecked={template.is_internal_only}/> Internal only</label><label><input type="checkbox" name="isPublicDemoVisible" defaultChecked={template.is_public_demo_visible}/> Public demo</label><label><input type="checkbox" name="isAvailableDuringSignup" defaultChecked={template.is_available_during_signup}/> Signup</label><Link className="btn btn-ghost" href={`/admin/platform/templates/${template.id}`}>Edit content</Link><button className="btn btn-ghost">Save</button></form></td></tr>)}</tbody></table></div></section>
  </AppShell>;
}
