/* eslint-disable @typescript-eslint/no-explicit-any */
import { NextResponse } from "next/server";
import { getViewer } from "@/lib/auth/viewer";
import { createAdminClient } from "@/lib/supabase/admin";
import { normalizeCompetitorIdentity, productSourceHash } from "@/lib/products/competitor-sync";

type ExtractedProduct = { name: string; brand: string; normalizedModel: string; sourceUrl: string; description: string; priceCents: number | null; rangeText: string; seatsText: string; powertrainText: string; highlights: string[]; specifications: Record<string, string>; sourceImageUrl: string | null };

function likelyProductLinks(html: string, base: string) { const links = new Set<string>(); const pattern = /href=["']([^"'#]+)["']/gi; let match: RegExpExecArray | null; while ((match = pattern.exec(html)) && links.size < 30) { try { const url = new URL(match[1], base); if (url.origin === new URL(base).origin && /model|vehicle|cart|product/i.test(url.pathname)) links.add(url.toString()); } catch {} } return [...links]; }
function titleFromUrl(url: string) { const part = new URL(url).pathname.split("/").filter(Boolean).at(-1) || ""; return decodeURIComponent(part).replace(/[-_]+/g, " ").replace(/\b\w/g, (letter) => letter.toUpperCase()).trim(); }
function decodeHtml(value: string) { return value.replace(/&amp;/g, "&").replace(/&quot;/g, '"').replace(/&#39;/g, "'").replace(/&nbsp;/g, " ").replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").trim(); }
function pageHeading(html: string) { const heading = html.match(/<h1[^>]*>([\s\S]{1,300}?)<\/h1>/i)?.[1]; return heading ? decodeHtml(heading) : ""; }
function meta(html: string, key: string) { const escaped = key.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"); const patterns = [new RegExp(`<meta[^>]+(?:property|name)=["']${escaped}["'][^>]+content=["']([^"']+)["']`, "i"), new RegExp(`<meta[^>]+content=["']([^"']+)["'][^>]+(?:property|name)=["']${escaped}["']`, "i")]; for (const pattern of patterns) { const value = html.match(pattern)?.[1]; if (value) return decodeHtml(value); } return ""; }
function jsonProducts(html: string): Array<Record<string, unknown>> { const products: Array<Record<string, unknown>> = []; const scripts = html.matchAll(/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi); for (const script of scripts) { try { const data = JSON.parse(script[1]); const values = Array.isArray(data) ? data : Array.isArray(data?.["@graph"]) ? data["@graph"] : [data]; values.forEach((value) => { const type = value?.["@type"]; if (type === "Product" || (Array.isArray(type) && type.includes("Product"))) products.push(value); }); } catch {} } return products; }
function firstString(value: unknown) { if (typeof value === "string") return decodeHtml(value); if (Array.isArray(value)) return firstString(value[0]); if (value && typeof value === "object" && "url" in value) return firstString((value as { url?: unknown }).url); return ""; }
function priceCents(value: unknown) { const numeric = typeof value === "number" ? value : Number(String(value || "").replace(/[^0-9.]/g, "")); return Number.isFinite(numeric) && numeric > 0 ? Math.round(numeric * 100) : null; }
function matchText(text: string, patterns: RegExp[]) { for (const pattern of patterns) { const match = text.match(pattern)?.[1]; if (match) return match.replace(/\s+/g, " ").trim(); } return ""; }
function headingValue(html: string, heading: string) { const escaped = heading.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"); const match = html.match(new RegExp(`<h[3-6][^>]*>\\s*${escaped}\\s*<\\/h[3-6]>([\\s\\S]{0,700}?)(?=<h[2-6]|$)`, "i")); return match ? decodeHtml(match[1]).slice(0, 280) : ""; }
function descriptionFromPage(html: string) { const match = html.match(/<h[2-4][^>]*>\s*Description\s*<\/h[2-4]>([\s\S]{0,2500}?)(?=<h[2-4]|$)/i); return match ? decodeHtml(match[1]).slice(0, 1200) : ""; }

function extractProduct(html: string, url: string, fallbackBrand: string): ExtractedProduct {
  const structured = jsonProducts(html)[0] || {}; const text = decodeHtml(html).slice(0, 160000); const name = firstString(structured.name) || pageHeading(html) || meta(html, "og:title") || meta(html, "twitter:title") || titleFromUrl(url); const brandValue = structured.brand; const brand = firstString(typeof brandValue === "object" && brandValue ? (brandValue as { name?: unknown }).name : brandValue) || fallbackBrand; const offer = Array.isArray(structured.offers) ? structured.offers[0] : structured.offers; const additional = Array.isArray(structured.additionalProperty) ? structured.additionalProperty : []; const specifications = { ...Object.fromEntries(additional.flatMap((item: any) => { const key = String(item?.name || "").trim(); const value = firstString(item?.value); return key && value ? [[key, value]] : []; })), ...Object.fromEntries([["batteryType", "Batteries"], ["controller", "Controller"], ["motor", "Motor"], ["brakes", "Brakes"], ["safetyFeatures", "Safety"], ["lighting", "Full Light Package"], ["audioSystem", "Dash & Infotainment"]].map(([key, heading]) => [key, headingValue(html, heading)]).filter(([, value]) => Boolean(value))) }; const rangeText = matchText(text, [/(?:range|miles per charge)\s*[:\-]?\s*(up to\s*)?(\d{1,3}\s*(?:mile|mi)\b[^.]{0,30})/i]); const seatsText = matchText(text, [/(\b(?:\d{1,2}|two|four|six|eight)[ -]?(?:passenger|seater|seat)s?\b[^.]{0,25})/i]); const powertrainText = matchText(text, [/(\b(?:\d{2,3}V\s*)?(?:lithium|lead[- ]acid|electric)\b[^.]{0,45})/i]); const highlights = Array.from(new Set([...html.matchAll(/<li[^>]*>([\s\S]{3,180}?)<\/li>/gi)].map((match) => decodeHtml(match[1])).filter((item) => item.length > 4 && item.length < 140))).slice(0, 12); const description = firstString(structured.description) || meta(html, "description") || meta(html, "og:description") || descriptionFromPage(html); const image = firstString(structured.image) || meta(html, "og:image") || null; return { name, brand, normalizedModel: normalizeCompetitorIdentity(name, brand), sourceUrl: url, description, priceCents: priceCents((offer as any)?.price), rangeText, seatsText, powertrainText, highlights, specifications, sourceImageUrl: image };
}

async function fetchProduct(url: string, competitorName: string) { try { const response = await fetch(url, { headers: { "User-Agent": "Refyntra-CompetitorSync/1.0" }, signal: AbortSignal.timeout(8000), cache: "no-store" }); if (!response.ok) throw new Error(); return extractProduct(await response.text(), url, competitorName); } catch { const name = titleFromUrl(url); return { name, brand: competitorName, normalizedModel: normalizeCompetitorIdentity(name, competitorName), sourceUrl: url, description: "", priceCents: null, rangeText: "", seatsText: "", powertrainText: "", highlights: [], specifications: {}, sourceImageUrl: null } satisfies ExtractedProduct; } }

export async function POST(_request: Request, { params }: { params: Promise<{ id: string }> }) {
  const viewer = await getViewer(); if (!viewer?.organizationId || !["tenant_admin", "platform_owner", "manager"].includes(viewer.role)) return NextResponse.json({ error: "Manager access is required." }, { status: 403 }); const id = (await params).id; if (!/^[0-9a-f-]{36}$/i.test(id)) return NextResponse.json({ error: "Invalid source." }, { status: 400 }); const admin = createAdminClient(); const { data: source } = await admin.from("competitor_sources").select("id,source_url,competitor_name").eq("id", id).eq("organization_id", viewer.organizationId).eq("is_active", true).maybeSingle(); if (!source) return NextResponse.json({ error: "Source not found." }, { status: 404 }); const { data: run, error: runError } = await admin.from("competitor_sync_runs").insert({ organization_id: viewer.organizationId, source_id: id, status: "running", initiated_by: viewer.id, started_at: new Date().toISOString() }).select("id").single(); if (runError || !run) return NextResponse.json({ error: "Could not start sync." }, { status: 500 });
  try { const response = await fetch(source.source_url, { headers: { "User-Agent": "Refyntra-CompetitorSync/1.0" }, signal: AbortSignal.timeout(15000), cache: "no-store" }); if (!response.ok) throw new Error(`Website returned ${response.status}.`); const links = likelyProductLinks(await response.text(), source.source_url); const existingResult = await admin.from("products").select("id,name,brand,normalized_model,source_hash").eq("organization_id", viewer.organizationId).eq("product_type", "competitor_product"); const existing = existingResult.data || []; const details = await Promise.all(links.map((url) => fetchProduct(url, source.competitor_name))); const candidates = details.map((extracted) => { const match = existing.find((product) => product.normalized_model === extracted.normalizedModel || normalizeCompetitorIdentity(product.name, product.brand || "") === extracted.normalizedModel); const hash = productSourceHash(extracted); return { organization_id: viewer.organizationId, sync_run_id: run.id, matched_product_id: match?.id || null, source_url: extracted.sourceUrl, source_hash: hash, extracted_product: extracted, classification: match ? (match.source_hash === hash ? "matched" : "update_available") : "new", field_changes: match ? { sourceHash: { current: match.source_hash, discovered: hash } } : {} }; }); if (candidates.length) await admin.from("competitor_sync_candidates").insert(candidates); const totals = { new_count: candidates.filter((item) => item.classification === "new").length, matched_count: candidates.filter((item) => item.classification === "matched").length, update_count: candidates.filter((item) => item.classification === "update_available").length }; await admin.from("competitor_sync_runs").update({ status: "review_ready", products_scanned: links.length, ...totals, completed_at: new Date().toISOString() }).eq("id", run.id); await admin.from("competitor_sources").update({ last_checked_at: new Date().toISOString(), last_successful_sync_at: new Date().toISOString(), sync_status: "review_ready" }).eq("id", id); return NextResponse.json({ runId: run.id, discovered: links.length, ...totals }); } catch (error) { const message = error instanceof Error ? error.message : "Scan failed."; await admin.from("competitor_sync_runs").update({ status: "failed", errors: [message], completed_at: new Date().toISOString() }).eq("id", run.id); await admin.from("competitor_sources").update({ last_checked_at: new Date().toISOString(), sync_status: "failed" }).eq("id", id); return NextResponse.json({ error: message }, { status: 502 }); }
}
/* eslint-disable @typescript-eslint/no-explicit-any */
