import { NextResponse } from "next/server";
import { getViewer } from "@/lib/auth/viewer";
import { createClient } from "@/lib/supabase/server";
import { flagScenarioDuplicates, parseScenarioSpreadsheet, type ImportedCoachScenario } from "@/lib/coach/scenario-import";
async function context(){const viewer=await getViewer();if(!viewer?.organizationId||viewer.demo||!["tenant_admin","platform_owner"].includes(viewer.role))return null;return{viewer,db:await createClient()};}
const slug=(value:string)=>value.toLowerCase().normalize("NFKD").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,90)||"practice-scenario";
export async function POST(request:Request){const current=await context();if(!current)return NextResponse.json({error:"Tenant administrator access is required."},{status:403});const form=await request.formData(),file=form.get("file");if(!(file instanceof File)||file.size>10*1024*1024||!/.\.(csv|xlsx)$/i.test(file.name))return NextResponse.json({error:"Choose a CSV or Excel file smaller than 10 MB."},{status:400});try{const scenarios=await parseScenarioSpreadsheet(file);if(!scenarios.length)return NextResponse.json({error:"No scenarios were detected."},{status:422});const[{data:existing},{data:categories}]=await Promise.all([current.db.from("coach_scenarios").select("id,title,slug").eq("organization_id",current.viewer.organizationId),current.db.from("text_template_categories").select("name").eq("organization_id",current.viewer.organizationId).eq("content_group","practice_scenario")]);const known=new Set((categories||[]).map(c=>c.name.toLowerCase()));return NextResponse.json({scenarios:flagScenarioDuplicates(scenarios,existing||[]),missingCategories:[...new Set(scenarios.map(i=>i.category).filter(name=>name&&!known.has(name.toLowerCase())))]});}catch{return NextResponse.json({error:"The file could not be processed. Check the template and try again."},{status:422});}}
export async function PUT(request:Request){const current=await context();if(!current)return NextResponse.json({error:"Tenant administrator access is required."},{status:403});const body=await request.json().catch(()=>null) as {scenarios?:ImportedCoachScenario[];duplicateStrategy?:string;createMissingCategories?:boolean}|null,items=Array.isArray(body?.scenarios)?body.scenarios.slice(0,500):[],strategy=["replace","new"].includes(body?.duplicateStrategy||"")?body!.duplicateStrategy!:"skip",org=current.viewer.organizationId;let imported=0,replaced=0,skipped=0;if(body?.createMissingCategories){for(const[index,name]of [...new Set(items.map(i=>String(i.category||"").trim()).filter(Boolean))].entries())await current.db.from("text_template_categories").upsert({organization_id:org,content_group:"practice_scenario",name:name.slice(0,120),position:500+index*10},{onConflict:"organization_id,content_group,name"});}
  for(const[itemIndex,item]of items.entries()){if(item.validationIssues?.length||!item.title||!item.category||item.responseOptions?.length<2){skipped++;continue;}if(item.duplicateId&&strategy==="skip"){skipped++;continue;}const record={organization_id:org,slug:slug(item.title)+(item.duplicateId&&strategy==="new"?`-copy-${itemIndex+1}`:""),title:item.title.slice(0,160),category:item.category.slice(0,120),difficulty:item.difficulty,duration_minutes:item.durationMinutes,customer_persona:item.customerPersona,goal:item.goal,opening:item.opening,skills:item.skills.slice(0,20),tags:item.tags.slice(0,20),response_options:item.responseOptions.slice(0,6),preferred_option_indices:[0],rubric_weights:item.rubricWeights,status:item.status,updated_at:new Date().toISOString()};let scenarioId="";if(item.duplicateId&&strategy==="replace"){const{data,error}=await current.db.from("coach_scenarios").update(record).eq("id",item.duplicateId).eq("organization_id",org).select("id").single();if(error||!data){skipped++;continue;}scenarioId=data.id;await current.db.from("coach_scenario_rounds").delete().eq("scenario_id",scenarioId).eq("organization_id",org);replaced++;}else{const{data,error}=await current.db.from("coach_scenarios").insert(record).select("id").single();if(error||!data){skipped++;continue;}scenarioId=data.id;imported++;}const prompts=[item.opening,item.roundTwoPrompt,item.roundThreePrompt],{error}=await current.db.from("coach_scenario_rounds").insert(prompts.map((prompt,index)=>({organization_id:org,scenario_id:scenarioId,round_number:index+1,customer_prompt:prompt,response_options:item.responseOptions,preferred_option_indices:[0],skill_impacts:item.skills})));if(error){await current.db.from("coach_scenarios").delete().eq("id",scenarioId).eq("organization_id",org);if(item.duplicateId&&strategy==="replace")replaced--;else imported--;skipped++;}}
  return NextResponse.json({imported,replaced,skipped});}
