import { NextResponse } from "next/server";
import { getViewer } from "@/lib/auth/viewer";
import { createAdminClient } from "@/lib/supabase/admin";
import { createClient } from "@/lib/supabase/server";
import { createEmbeddings } from "@/lib/rag/openai";
import { getCommunicationContext, formatCommunicationContext } from "@/lib/rag/communication-context";
import { compileRefyntraPrompt } from "@/lib/rag/prompt-compiler";
import { coachSkills, nextDifficulty, profileFromRow, type CoachMode } from "@/lib/coach/adaptive";

const MODEL = process.env.OPENAI_COACH_MODEL || process.env.OPENAI_CHAT_MODEL || "gpt-5-mini";
const modes: CoachMode[] = ["role_play", "objection", "challenge"];
type CoachSupabaseClient = Parameters<typeof getCommunicationContext>[0];
type KnowledgeProduct = { name: string; model: string | null; description: string | null; sales_guide: string | null; highlights: string | null };
type KnowledgeChunk = { document_name: string; content: string };
type ConversationMessage = { speaker: string; content: string };
type PersonaTemplate = { id: string; name: string; archetype: string; difficulty: string; configuration: Record<string, unknown>; notes: string };
const customerQuestionFocus = `Customer questions should feel like real cart-shopping conversation and focus on one useful topic at a time: early shopping (price range, differences between options, new versus used, colors); general product questions (comfort, range, charging, seating, features, accessories); fit and use (passengers, neighborhood, golf course, cargo, family use); street or legal suitability; price, financing, trade-in, payment, and value; dealership trust, service, warranty support, and delivery; competitor comparisons; and natural purchase objections such as needing time, spouse input, budget, styling, or shopping around. Keep questions conversational and general; never request written documentation, exact measurements, specifications, policy wording, references, PDFs, emails, attachments, proof, or links.`;
function limitCustomerQuestions(reply: string) {
  let questions = 0;
  for (let index = 0; index < reply.length; index += 1) {
    if (reply[index] !== "?") continue;
    questions += 1;
    if (questions > 2) return reply.slice(0, index).trim();
  }
  return reply;
}
const prohibitedCustomerRequest = /\b(?:written|documentation|document|pdf|spec(?:ification|ifications)?|exact (?:measurement|measurements|dimension|dimensions)|measurement(?:s)?|dimension(?:s)?|reference(?:s)?|citation(?:s)?|warranty (?:document|language|policy)|service (?:policy|document)|email (?:me|us)|send (?:me|us)|attach(?:ment)?|link(?:s)?|proof)\b/i;
const salespersonDiscoveryQuestion = /\b(?:will you (?:mainly )?use|how do you plan (?:to|on) use|what (?:are|is) your (?:use|need|needs|priority|priorities)|who will (?:be )?using|how many (?:passengers|people) will you)\b/i;
const coachingLeak = /(?:^|\n)\s*(?:best move|safe|recommended|next move|turning point|score|customer response|coach)\s*:/im;
function safeCustomerMessage(message: unknown, fallback: string) {
  const text = String(message || "").trim();
  const sentenceCount = (text.match(/[.!?]+(?=\s|$)/g) || []).length;
  return prohibitedCustomerRequest.test(text) || salespersonDiscoveryQuestion.test(text) || coachingLeak.test(text) || sentenceCount > 3 || text.length > 700 || !text ? fallback : limitCustomerQuestions(text).slice(0, 4000);
}
function discoveryAnswer(persona: unknown, repReply: string) {
  const details = persona && typeof persona === "object" ? persona as Record<string, unknown> : {};
  const intendedUse = typeof details.intendedUse === "string" ? details.intendedUse.trim() : "neighborhood trips and time with family";
  const motivation = typeof details.buyingMotivation === "string" ? details.buyingMotivation.trim() : "something comfortable and dependable";
  if (/\b(?:how|where|what).*\b(?:use|using|drive|need|plan)\b/i.test(repReply)) return `We’ll mainly use it for ${intendedUse}. We’re looking for ${motivation}.`;
  if (/\b(?:who|how many).*(?:ride|passenger|people|family)\b/i.test(repReply)) return "It will usually be for our family and friends, so comfort and easy passenger access matter to us.";
  return `What matters most to us is finding something that works well for ${intendedUse} and feels like a good long-term choice.`;
}
async function ai(system: string, payload: unknown) {
  const key = process.env.OPENAI_API_KEY; if (!key) throw new Error("OpenAI is not configured.");
  const response = await fetch("https://api.openai.com/v1/chat/completions", { method: "POST", headers: { Authorization: `Bearer ${key}`, "Content-Type": "application/json" }, body: JSON.stringify({ model: MODEL, messages: [{ role: "system", content: system }, { role: "user", content: JSON.stringify(payload) }], response_format: { type: "json_object" } }), cache: "no-store" });
  const data = await response.json(); if (!response.ok) throw new Error(data?.error?.message || "The coach could not respond.");
  return JSON.parse(data.choices?.[0]?.message?.content || "{}");
}
async function approvedContext(supabase: CoachSupabaseClient, organizationId: string, query: string) {
  const [embedding] = await createEmbeddings([query]);
  const [{ data: chunks }, { data: products }, communication] = await Promise.all([
    supabase.rpc("match_knowledge_chunks", { query_embedding: `[${embedding.join(",")}]`, match_tenant_id: organizationId, match_location_id: null, match_product_id: null, match_count: 6 }),
    supabase.from("products").select("name,model,description,sales_guide,highlights").eq("organization_id", organizationId).eq("status", "published").eq("review_status", "approved").neq("product_type", "competitor_product").limit(30), getCommunicationContext(supabase, organizationId, embedding),
  ]);
  const knowledge = [...((products || []) as KnowledgeProduct[]).map((product) => `PRODUCT: ${product.name} ${product.model || ""}\n${product.description || ""}\n${product.sales_guide || ""}`), ...((chunks || []) as KnowledgeChunk[]).map((chunk) => `KNOWLEDGE: ${chunk.document_name}\n${chunk.content}`)].join("\n\n");
  return { knowledge, communication };
}
export async function POST(request: Request) {
  const viewer = await getViewer(); if (!viewer?.organizationId || viewer.demo) return NextResponse.json({ error: "Sign in to use adaptive coaching." }, { status: 401 });
  const body = await request.json().catch(() => null); const action = body?.action;
  const client = await createClient();
  try {
    const admin = createAdminClient();
    if (action === "start") {
      const mode = modes.includes(body.mode) ? body.mode : "role_play"; const requestedType = typeof body.customerType === "string" ? body.customerType.trim() : ""; const requestedDifficulty = ["Beginner", "Intermediate", "Advanced", "Expert"].includes(body.difficulty) ? body.difficulty : ""; const { data: profileRow } = await client.from("coach_adaptive_profiles").select("*").eq("organization_id", viewer.organizationId).eq("user_id", viewer.id).maybeSingle(); const profile = profileFromRow(profileRow);
      const { data: templateRows } = await admin.from("coach_persona_templates").select("id,name,archetype,difficulty,configuration,notes").eq("organization_id", viewer.organizationId).eq("is_active", true).order("name");
      const templates = (templateRows || []) as PersonaTemplate[]; const template = requestedType && requestedType !== "Random Customer" ? templates.find((item) => item.id === requestedType || item.name === requestedType || item.archetype === requestedType) || null : templates.length ? templates[Math.floor(Math.random() * templates.length)] : null;
      const difficulty = requestedDifficulty || template?.difficulty || profile.difficulty;
      const context = await approvedContext(client, viewer.organizationId, `${profile.recommendedFocus} ${mode}`);
      const system = compileRefyntraPrompt({ standards: context.communication.standards, approvedKnowledge: context.knowledge, conversationContext: formatCommunicationContext(context.communication), userRequest: "", featureInstructions: `You create a realistic adaptive dealership customer role-play. Return JSON with persona and opening. persona must contain customerName, personality, productInterest, intendedUse, buyingMotivation, budgetSensitivity, competitors, primaryObjection, hiddenObjection, timeline, decisionMakers, willingnessToBuy, emotionalDrivers. Do not invent company facts. You are the buyer, never the salesperson: state needs in first person and ask about the cart, purchase, ownership, or dealership; never ask the rep buyer-qualification or discovery questions about how they will use a cart, their passengers, needs, or priorities. The opening must be 1-3 natural sentences and reveal only what a real customer would initially say. The primary objection remains hidden until naturally discovered. Build a sales conversation, not a documentation or administrative exercise: do not make email, attachment, contact-data, CRM, verification, technical spec sheets, exact measurements, warranty PDFs, or written policy requests the focus. ${customerQuestionFocus} Technical questions should be natural and general, then lead back to needs, value, dealership support, a visit, or the purchase. Adapt difficulty to demonstrated profile proficiency. Challenge mode is tougher and objection mode starts with a natural concern.` });
      const generated = await ai(system, { mode, profile, requestedDifficulty: difficulty, personaTemplate: template ? { name: template.name, archetype: template.archetype, configuration: template.configuration, notes: template.notes } : null }); if (!generated.opening || !generated.persona) throw new Error("The coach returned an incomplete scenario.");
      const opening = safeCustomerMessage(generated.opening, `Hi, I’m interested in ${String(generated.persona.productInterest || "a cart").slice(0, 120)}. I’m trying to find something that works well for how we’ll use it. What would you recommend?`);
      const sessionValues = { organization_id: viewer.organizationId, user_id: viewer.id, status: "in_progress", session_type: mode, difficulty: difficulty === "Beginner" ? "Foundational" : difficulty, coaching_focus: profile.recommendedFocus, persona_template_id: template?.id || null };
      let created = await admin.from("coach_sessions").insert(sessionValues).select("id").single();
      if (created.error && /persona_template_id|difficulty/i.test(created.error.message)) created = await admin.from("coach_sessions").insert({ organization_id: viewer.organizationId, user_id: viewer.id, status: "in_progress", session_type: mode, difficulty: profile.difficulty, coaching_focus: profile.recommendedFocus }).select("id").single();
      const session = created.data; if (created.error || !session) throw created.error || new Error("The practice session could not be created.");
      await admin.from("coach_session_personas").insert({ session_id: session.id, organization_id: viewer.organizationId, persona: { ...generated.persona, buyingState: "Guarded", discoveredFacts: [] } });
      await admin.from("coach_conversation_messages").insert({ session_id: session.id, organization_id: viewer.organizationId, speaker: "customer", content: opening });
      return NextResponse.json({ sessionId: session.id, opening, focus: profile.recommendedFocus, difficulty });
    }
    const sessionId = typeof body.sessionId === "string" ? body.sessionId : ""; if (!/^[0-9a-f-]{36}$/i.test(sessionId)) return NextResponse.json({ error: "Invalid practice session." }, { status: 400 });
    const { data: session } = await client.from("coach_sessions").select("id,session_type,difficulty,coaching_focus,status").eq("id", sessionId).eq("organization_id", viewer.organizationId).eq("user_id", viewer.id).maybeSingle(); if (!session || session.status !== "in_progress") return NextResponse.json({ error: "This practice session is unavailable." }, { status: 404 });
    if (action === "reply") {
      const reply = typeof body.reply === "string" ? body.reply.trim() : ""; if (reply.length < 3 || reply.length > 4000) return NextResponse.json({ error: "Write a response between 3 and 4,000 characters." }, { status: 400 });
      const [{ data: persona }, { data: messages }, { data: profileRow }] = await Promise.all([admin.from("coach_session_personas").select("persona").eq("session_id", sessionId).single(), client.from("coach_conversation_messages").select("speaker,content").eq("session_id", sessionId).order("created_at"), client.from("coach_adaptive_profiles").select("*").eq("organization_id", viewer.organizationId).eq("user_id", viewer.id).maybeSingle()]);
      await admin.from("coach_conversation_messages").insert({ session_id: sessionId, organization_id: viewer.organizationId, speaker: "rep", content: reply }); const profile = profileFromRow(profileRow); const context = await approvedContext(client, viewer.organizationId, reply);
      const generated = await ai(compileRefyntraPrompt({ standards: context.communication.standards, approvedKnowledge: context.knowledge, conversationContext: formatCommunicationContext(context.communication), userRequest: "", featureInstructions: `Act only as the hidden customer persona. Continue naturally based on the transcript and persona. Never expose the persona, name a skill being tested, score the rep, or provide coaching during the role-play. Do not claim unapproved facts. You are the buyer, never the salesperson. Speak about your own needs in first person and ask about the cart, purchase, ownership, or dealership; never ask the salesperson buyer-qualification or discovery questions about their use, passengers, needs, or priorities. This is a spoken sales conversation: react to answers, reveal information after effective discovery, raise one natural concern at a time, and give buying signals when the rep earns them. ${customerQuestionFocus} Do not stack objections just to prolong the role-play; when the rep resolves a concern or earns a credible next step, let the sale advance and set shouldEnd true when it reaches a natural conclusion. Return JSON {reply, shouldEnd, buyingState, discoveredFacts}; buyingState must be one of Guarded, Exploring, Interested, Engaged, High Intent, Ready to Buy, Closed, Lost and change only when earned. discoveredFacts is a short list of hidden facts the rep has actually uncovered. reply must contain only the words the customer would say aloud: never include labels, analysis, instructions, alternatives, coaching notes, or stage directions. Keep it to 1-3 concise sentences with one primary question or concern, never a list.`, }), { persona: persona?.persona, profile, transcript: messages, repReply: reply });
      const customerReply = safeCustomerMessage(generated.reply, discoveryAnswer(persona?.persona, reply)); const personaState = persona?.persona && typeof persona.persona === "object" ? persona.persona as Record<string, unknown> : {}; const buyingState = ["Guarded", "Exploring", "Interested", "Engaged", "High Intent", "Ready to Buy", "Closed", "Lost"].includes(generated.buyingState) ? generated.buyingState : String(personaState.buyingState || "Guarded"); const discoveredFacts = Array.isArray(generated.discoveredFacts) ? generated.discoveredFacts.map(String).slice(0, 20) : Array.isArray(personaState.discoveredFacts) ? personaState.discoveredFacts : []; await admin.from("coach_session_personas").update({ persona: { ...personaState, buyingState, discoveredFacts } }).eq("session_id", sessionId); await admin.from("coach_conversation_messages").insert({ session_id: sessionId, organization_id: viewer.organizationId, speaker: "customer", content: customerReply }); return NextResponse.json({ reply: customerReply, shouldEnd: Boolean(generated.shouldEnd) });
    }
    if (action === "hint") {
      const { data: messages } = await client.from("coach_conversation_messages").select("speaker,content").eq("session_id", sessionId).order("created_at");
      const generated = await ai("You are a sales coach providing one optional, concise hint during an active role-play. Do not script an answer, reveal the hidden persona, score the rep, or mention a framework. Return JSON {hint}; hint must be one sentence under 24 words and point to one discovery, listening, objection, buying-signal, or closing opportunity.", { transcript: messages, focus: session.coaching_focus });
      const hint = String(generated.hint || "Ask one open question that helps you understand the customer’s priorities.").slice(0, 220);
      await admin.from("coach_sessions").update({ evaluation: { hintUsed: true } }).eq("id", sessionId).eq("organization_id", viewer.organizationId);
      return NextResponse.json({ hint });
    }
    if (action === "complete") {
      const [{ data: messages }, { data: profileRow }, { data: personaRow }] = await Promise.all([client.from("coach_conversation_messages").select("speaker,content").eq("session_id", sessionId).order("created_at"), client.from("coach_adaptive_profiles").select("*").eq("organization_id", viewer.organizationId).eq("user_id", viewer.id).maybeSingle(), admin.from("coach_session_personas").select("persona").eq("session_id", sessionId).maybeSingle()]); const profile = profileFromRow(profileRow); const context = await approvedContext(client, viewer.organizationId, ((messages || []) as ConversationMessage[]).map((message) => message.content).join(" "));
      const evaluation = await ai(compileRefyntraPrompt({ standards: context.communication.standards, approvedKnowledge: context.knowledge, userRequest: "", featureInstructions: `You are now in Coach Mode. Evaluate the entire completed interaction against approved knowledge, consultative selling, C.L.O.S.E.R., NLP communication, and the rep's profile. Return JSON: score (0-100), skillScores object containing all ${coachSkills.join(", ")}, result, summary, strength, improvement, turningPoint, betterMove, whatToSay, closerAssessment, strengths array, weaknesses array, recommendedFocus, objectionType, customerOutcome, missedQuestions. customerOutcome must be Sold, Strong Opportunity, Follow-Up Needed, or Customer Lost. missedQuestions must be a concise array of the most useful discovery questions the rep did not ask. Compare the transcript to the hidden persona's discoveredFacts and buyingState. Identify the specific turning point that affected the outcome and give one concise better move and wording example. Assess rapport, discovery, listening, needs identification, recommendation, value building, objections, buying signals, commitment, conversation control, and advancement. Do not reward invented facts; score fairly and specifically.` }), { profile, focus: session.coaching_focus, transcript: messages, hiddenPersona: personaRow?.persona });
      const score = Math.max(0, Math.min(100, Number(evaluation.score) || 0)); const skills = Object.fromEntries(coachSkills.map((skill) => [skill, Math.max(0, Math.min(100, Number(evaluation.skillScores?.[skill]) || 0))])); const updatedSkills = Object.fromEntries(coachSkills.map((skill) => [skill, profile.skillScores[skill] ? Math.round(profile.skillScores[skill] * .65 + skills[skill] * .35) : skills[skill]])); const overall = profile.overallScore ? Math.round(profile.overallScore * .65 + score * .35) : score; const weaknesses = (evaluation.weaknesses || coachSkills.filter((skill) => updatedSkills[skill] < 70)).map(String).slice(0, 4); const strengths = (evaluation.strengths || coachSkills.filter((skill) => updatedSkills[skill] >= 80)).map(String).slice(0, 4); const difficulty = nextDifficulty(overall, profile.difficulty);
      await admin.from("coach_sessions").update({ status: "completed", score, closer_scores: Object.fromEntries([["Clarify", skills.Discovery], ["Listen", skills.Communication], ["Open", skills["NLP / language"]], ["Solve", skills["Objection handling"]], ["Explain", skills["Product knowledge"]], ["Recommend", skills.Closing]]), summary: String(evaluation.summary || "Practice session completed."), strength: String(evaluation.strength || strengths[0] || "You kept the conversation customer-centered."), improvement: String(evaluation.improvement || weaknesses[0] || "Continue building discovery depth."), evaluation, completed_at: new Date().toISOString() }).eq("id", sessionId);
      await admin.from("coach_adaptive_profiles").upsert({ organization_id: viewer.organizationId, user_id: viewer.id, overall_score: overall, skill_scores: updatedSkills, recurring_strengths: strengths, recurring_weaknesses: weaknesses, recent_trend: score >= profile.overallScore ? "Improving" : "Needs focused repetition", completed_scenarios: [...profile.completedScenarios, session.session_type].slice(-30), objection_types_practiced: [...new Set([...profile.objectionTypes, String(evaluation.objectionType || session.session_type)])].slice(-20), current_difficulty: difficulty, recommended_focus: String(evaluation.recommendedFocus || weaknesses[0] || "Discovery and customer priorities"), updated_at: new Date().toISOString() });
      return NextResponse.json({ score, skills, summary: evaluation.summary, strength: evaluation.strength, improvement: evaluation.improvement, recommendedFocus: evaluation.recommendedFocus, difficulty, customerOutcome: evaluation.customerOutcome, missedQuestions: evaluation.missedQuestions, turningPoint: evaluation.turningPoint, betterMove: evaluation.betterMove, whatToSay: evaluation.whatToSay });
    }
    return NextResponse.json({ error: "Unsupported coach action." }, { status: 400 });
  } catch (error) { console.error("Adaptive coach error", error); return NextResponse.json({ error: error instanceof Error ? error.message : "The coach is temporarily unavailable." }, { status: 503 }); }
}
