"use server";
import { revalidatePath } from "next/cache";
import { getViewer } from "@/lib/auth/viewer";
import { createClient } from "@/lib/supabase/server";
import { createAdminClient } from "@/lib/supabase/admin";

function productSlug(value: string, candidateId: string) {
  const base = value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || "competitor-product";
  return `${base}-${candidateId.slice(0, 8)}`;
}

export async function approveNewCompetitorCandidate(formData: FormData) { const viewer = await getViewer(); if (!viewer?.organizationId || !["tenant_admin","platform_owner","manager"].includes(viewer.role)) throw new Error("Unauthorized"); const id = String(formData.get("candidateId") || ""); const supabase = await createClient(); const { data: candidate, error } = await supabase.from("competitor_sync_candidates").select("*").eq("id", id).eq("organization_id", viewer.organizationId).eq("classification", "new").is("approved_at", null).single(); if (error || !candidate) throw new Error("This candidate is unavailable."); const item = candidate.extracted_product as any; const admin = createAdminClient(); const { data: product, error: productError } = await admin.from("products").insert({ organization_id: viewer.organizationId, name: item.name, slug: productSlug(`${item.brand}-${item.name}`, candidate.id), model: "", brand: item.brand, manufacturer: item.brand, product_type: "competitor_product", product_category: "Competitor Vehicles", normalized_model: item.normalizedModel, normalized_variant: "", source_url: candidate.source_url, source_hash: candidate.source_hash, source_name: item.brand, source_last_checked_at: new Date().toISOString(), description: item.description || "", base_price_cents: item.priceCents || 0, range_text: item.rangeText || "", seats_text: item.seatsText || "", powertrain_text: item.powertrainText || "", highlights: Array.isArray(item.highlights) ? item.highlights : [], specifications: { ...(item.specifications || {}), sourceImageUrl: item.sourceImageUrl || "" }, status: "published", imported_by: viewer.id, imported_at: new Date().toISOString() }).select("id").single(); if (productError || !product) throw new Error("The competitor product could not be approved."); await admin.from("competitor_sync_candidates").update({ matched_product_id: product.id, approved_at: new Date().toISOString(), approved_by: viewer.id }).eq("id", id); revalidatePath("/admin/competitor-sources/review"); revalidatePath("/comparisons"); }
export async function skipCompetitorCandidate(formData: FormData) { const viewer = await getViewer(); if (!viewer?.organizationId || !["tenant_admin","platform_owner","manager"].includes(viewer.role)) throw new Error("Unauthorized"); const id = String(formData.get("candidateId") || ""); const supabase = await createClient(); const { error } = await supabase.from("competitor_sync_candidates").update({ classification:"skipped", approved_at:new Date().toISOString(), approved_by:viewer.id }).eq("id",id).eq("organization_id",viewer.organizationId).is("approved_at",null); if(error) throw new Error("Candidate could not be skipped."); revalidatePath("/admin/competitor-sources/review"); }
export async function approveCompetitorUpdate(formData: FormData) { const viewer=await getViewer(); if(!viewer?.organizationId||!["tenant_admin","platform_owner","manager"].includes(viewer.role)) throw new Error("Unauthorized"); const id=String(formData.get("candidateId")||""); const supabase=await createClient(); const {data:candidate,error}=await supabase.from("competitor_sync_candidates").select("*").eq("id",id).eq("organization_id",viewer.organizationId).eq("classification","update_available").is("approved_at",null).single(); if(error||!candidate||!candidate.matched_product_id) throw new Error("Update is unavailable."); const item=candidate.extracted_product as any; const admin=createAdminClient(); const {data:product}=await admin.from("products").select("source_hash,specifications").eq("id",candidate.matched_product_id).single(); await admin.from("products").update({source_hash:candidate.source_hash,source_url:candidate.source_url,source_last_checked_at:new Date().toISOString(),description:item.description||"",base_price_cents:item.priceCents||0,range_text:item.rangeText||"",seats_text:item.seatsText||"",powertrain_text:item.powertrainText||"",highlights:Array.isArray(item.highlights)?item.highlights:[],specifications:{...(item.specifications||{}),sourceImageUrl:item.sourceImageUrl||""}}).eq("id",candidate.matched_product_id).eq("organization_id",viewer.organizationId); await admin.from("competitor_product_change_history").insert({organization_id:viewer.organizationId,product_id:candidate.matched_product_id,changed_field:"source_sync",previous_value:{sourceHash:product?.source_hash,specifications:product?.specifications},new_value:candidate.extracted_product,source_url:candidate.source_url,change_type:"website_sync",approved_at:new Date().toISOString(),approved_by:viewer.id}); await admin.from("competitor_sync_candidates").update({approved_at:new Date().toISOString(),approved_by:viewer.id}).eq("id",id); revalidatePath("/admin/competitor-sources/review"); revalidatePath("/comparisons"); }
