/* eslint-disable @typescript-eslint/no-explicit-any */
import { AppShell } from "@/components/app-shell";
import { PageHeader } from "@/components/page-header";
import Link from "next/link";
import { getViewer } from "@/lib/auth/viewer";
import { createClient } from "@/lib/supabase/server";
import { approveCompetitorUpdate, approveNewCompetitorCandidate, skipCompetitorCandidate } from "./actions";
export default async function CompetitorReviewPage() { const viewer = await getViewer(); const supabase = await createClient(); const result = viewer?.organizationId ? await supabase.from("competitor_sync_candidates").select("id,classification,source_url,extracted_product,created_at,competitor_sync_runs!inner(created_at,competitor_sources!inner(competitor_name))").eq("organization_id", viewer.organizationId).is("approved_at", null).order("created_at", { ascending: false }).limit(100) : { data: [] }; const candidates = result.data || []; return <AppShell title="Competitor Review"><PageHeader eyebrow="Competitor products" title="Review discovered products" description="Nothing here is live until a manager approves it."/><section className="card">{candidates.length ? <div className="table-wrap"><table className="table"><thead><tr><th>Product</th><th>Classification</th><th>Source page</th><th>Action</th></tr></thead><tbody>{candidates.map((candidate: any) => <tr key={candidate.id}><td><strong>{candidate.extracted_product?.name || "Unnamed product"}</strong><small style={{display:"block",color:"#68738a"}}>{candidate.extracted_product?.brand || "Competitor"}</small></td><td><span className="badge amber">{candidate.classification.replace(/_/g," ")}</span></td><td><a href={candidate.source_url} target="_blank" rel="noreferrer">Open source</a></td><td><div style={{display:"flex",gap:6,flexWrap:"wrap"}}><Link className="btn btn-secondary" href={`/admin/competitor-sources/review/${candidate.id}`}>Preview</Link>{candidate.classification === "new" && <form action={approveNewCompetitorCandidate}><input type="hidden" name="candidateId" value={candidate.id}/><button className="btn btn-primary" type="submit">Approve & import</button></form>}{candidate.classification === "update_available" && <form action={approveCompetitorUpdate}><input type="hidden" name="candidateId" value={candidate.id}/><button className="btn btn-primary" type="submit">Approve update</button></form>}<form action={skipCompetitorCandidate}><input type="hidden" name="candidateId" value={candidate.id}/><button className="btn btn-ghost" type="submit">Skip</button></form></div></td></tr>)}</tbody></table></div> : <p>No unreviewed competitor products are available yet. Add a source and run a scan first.</p>}</section></AppShell>; }
/* eslint-disable @typescript-eslint/no-explicit-any */
