import Link from "next/link";
import { ArrowRight, Award, BookOpenCheck, Clock3, Handshake, MapPin, Mountain, Play, Target, TrendingUp, UsersRound } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { PageHeader } from "@/components/page-header";
import { getViewer } from "@/lib/auth/viewer";
import { getCoachDashboardData } from "@/lib/coach/data";
import { demoCloserScores } from "@/lib/coach/demo";
import { getViewerIndustryTemplateKey } from "@/lib/organizations/industry";
import styles from "./coach.module.css";

export default async function CoachDashboardPage() {
  const [data, viewer] = await Promise.all([getCoachDashboardData(), getViewer()]);
  const templateKey = viewer ? await getViewerIndustryTemplateKey(viewer) : null;
  const workspaceName = viewer?.organizationName.trim().toLowerCase() || "";
  const tailored = Boolean(viewer && (templateKey === "golf-cart" || viewer.demo || workspaceName === "runfloor demo" || workspaceName === "rayne rv"));
  const isRv = templateKey === "rv" || workspaceName === "rayne rv" || (viewer?.demo && workspaceName === "runfloor rv");
  const recommended = data.scenarios[0];
  const scores = data.recentSessions[0]?.closerScores.length ? data.recentSessions[0].closerScores : demoCloserScores;

  if (tailored) return <AppShell title="Sales Coach" industry={isRv ? "rv" : undefined}><main className={styles.coachExperience}>
    <section className={styles.hero}><div><span className={styles.eyebrow}>Practice with purpose</span><h1>Build confidence one<br/><em>conversation at a time.</em></h1><p>Sharpen your skills. Handle real situations. Create better customer experiences — and drive more sales.</p></div><div className={styles.heroAction}><blockquote>Great Conversations<br/>Lead to<br/>Great Adventures.</blockquote><Link className="btn btn-primary" href="/coach/scenarios"><Play size={16}/> Start practice</Link></div></section>
    <div className={styles.content}>
      <div className={styles.scope}><span><MapPin size={18}/><strong>Reporting scope:</strong> {data.scopeLabel}</span><Link className="btn btn-ghost" href="/coach/scenarios">Change location <ArrowRight size={14}/></Link></div>
      {data.error && <div className="card error-card"><h2>Coach data unavailable</h2><p>{data.error}</p></div>}
      <section className={styles.metrics}><Metric label="Practice sessions" value={String(data.practiceSessions)} copy="Saved sessions" icon={<BookOpenCheck/>}/><Metric label="Available scenarios" value={String(data.scenarios.length)} copy="Published practice" icon={<Award/>}/><Metric label="Average score" value={data.averageScore===null?"—":`${data.averageScore}%`} copy={data.averageScore===null?"Complete a session":"Saved performance"} icon={<Target/>}/><Metric label="Recent activity" value={String(data.recentSessions.length)} copy="Reviewable sessions" icon={<Clock3/>}/></section>
      <section className={styles.dashboard}><div className={styles.scenarios}><header><div><h2>Practice scenarios</h2><p>Real-world conversations. Real results.</p></div><Link className="text-button" href="/coach/scenarios">View all scenarios <ArrowRight size={14}/></Link></header>{recommended?<article className={styles.recommended}><span className="badge amber">Recommended next</span><h2>{recommended.title}</h2><p>{recommended.goal}</p><Link className="btn btn-primary" href={`/coach/session?scenario=${recommended.slug}`}><Play size={16}/> Start practice</Link></article>:<div className={styles.empty}><Target size={40}/><h2>No scenarios available yet</h2><p>A workspace administrator can publish the first scenario.</p><Link className="btn btn-primary" href="/coach/scenarios"><Play size={16}/> Start practice</Link></div>}</div><div className={styles.rightColumn}><section className={styles.skills}><header><div><h2>C.L.O.S.E.R. skill profile</h2><p>See how your skills measure up and where to focus next.</p></div><Link className="text-button" href="/coach/review">View detailed report <ArrowRight size={14}/></Link></header><div className="coach-scores">{scores.map(([skill,score])=><div key={skill}><span>{skill}</span><div className="progress"><span style={{width:`${score}%`}}/></div><strong>{score}</strong></div>)}</div></section><section className={styles.activity}><header><div><h2>Recent activity</h2><p>Your latest practice sessions and results.</p></div><Link className="text-button" href="/coach/review">View all <ArrowRight size={14}/></Link></header>{data.recentSessions.length?<div>{data.recentSessions.slice(0,3).map(session=><Link href={`/coach/review?session=${session.id}`} key={session.id}><strong>{session.scenarioTitle}</strong><span>{session.score}%</span></Link>)}</div>:<div className={styles.activityEmpty}><Clock3 size={30}/><strong>No recent activity</strong><p>Complete a practice session to see your activity here.</p></div>}</section></div></section>
      <section className={styles.promise}><blockquote><small>Stronger skills. Happier customers.</small>When you grow, we all go further.</blockquote><Pillar icon={<Handshake/>} title="Build Confidence" copy="Practice without pressure."/><Pillar icon={<UsersRound/>} title="Serve Customers Better" copy="Turn training into real results."/><Pillar icon={<Mountain/>} title="Drive Dealership Success" copy="A stronger team creates a stronger tomorrow."/></section>
    </div>
  </main></AppShell>;

  return <AppShell title="Sales Coach"><PageHeader eyebrow="Practice with purpose" title="Build confidence one conversation at a time" description="Use structured BGC practice scenarios and C.L.O.S.E.R.-based coaching to sharpen the skills that matter most." action={<Link className="btn btn-primary" href="/coach/scenarios"><Play size={16}/> Start practice</Link>}/><p className="callout"><strong>Reporting scope:</strong> {data.scopeLabel}</p>{data.error && <div className="card error-card"><h2>Coach data unavailable</h2><p>{data.error}</p></div>}<div className="grid grid-4"><Metric label="Practice sessions" value={String(data.practiceSessions)} copy="Saved sessions" icon={<BookOpenCheck/>}/><Metric label="Available scenarios" value={String(data.scenarios.length)} copy="Published practice" icon={<Award/>}/><Metric label="Average score" value={data.averageScore===null?"—":`${data.averageScore}%`} copy="Saved performance" icon={<TrendingUp/>}/><Metric label="Recent activity" value={String(data.recentSessions.length)} copy="Reviewable sessions" icon={<Clock3/>}/></div><div className="coach-dashboard-grid">{recommended?<section className="card"><h2>{recommended.title}</h2><p>{recommended.goal}</p><Link className="btn btn-primary" href={`/coach/session?scenario=${recommended.slug}`}>Begin practice <ArrowRight size={16}/></Link></section>:<section className="card output empty"><div><h2>No scenarios available</h2><p>A workspace administrator can publish the first scenario.</p></div></section>}<section className="card"><h2>C.L.O.S.E.R. skill profile</h2><div className="coach-scores">{scores.map(([skill,score])=><div key={skill}><span>{skill}</span><div className="progress"><span style={{width:`${score}%`}}/></div><strong>{score}</strong></div>)}</div></section></div></AppShell>;
}

function Metric({label,value,copy,icon}:{label:string;value:string;copy:string;icon:React.ReactNode}){return <div className="card"><div className="metric-row"><span>{label}</span><span className="metric-icon">{icon}</span></div><div className="metric">{value}</div><span className="delta">{copy}</span></div>}
function Pillar({icon,title,copy}:{icon:React.ReactNode;title:string;copy:string}){return <div>{icon}<span><strong>{title}</strong><small>{copy}</small></span></div>}
