import Link from "next/link";
import { AlertTriangle, ArrowRight, BarChart3, BookOpen, CalendarDays, Check, ClipboardCheck, Info, Lightbulb, MapPin, Plus, Target, TrendingDown, TrendingUp, UsersRound } from "lucide-react";
import { redirect } from "next/navigation";
import { AppShell } from "@/components/app-shell";
import { getExecutiveTrends } from "@/lib/executive/trends-repository";
import styles from "./trends.module.css";

const monthLabel = (period: string) => new Date(`${period}-01T12:00:00`).toLocaleDateString(undefined, { month: "short", year: "numeric" });
const money = (value: number) => new Intl.NumberFormat(undefined, { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(value);
const signed = (value: number, suffix = "") => `${value > 0 ? "+" : ""}${value.toLocaleString()}${suffix}`;

export default async function ExecutiveTrendsPage({ searchParams }: { searchParams: Promise<{ months?: string; location?: string; from?: string; to?: string; start?: string; end?: string }> }) {
  const data = await getExecutiveTrends(await searchParams);
  if (!data.canView) redirect("/dashboard");
  const latest = data.periods.at(-1);
  const previous = data.periods.at(-2);
  const totalSales = data.periods.reduce((sum, item) => sum + item.revenueActual, 0);
  const completedReviews = data.periods.filter((item) => item.reviewCompleted).length;
  const maximumRevenue = Math.max(1, ...data.periods.flatMap((item) => [item.revenueTarget, item.revenueActual]));
  const locationQuery = data.selectedLocation === "all" ? "" : `&location=${encodeURIComponent(data.selectedLocation)}`;
  const selectedRange = data.start || data.end ? "custom" : String(data.months);

  return <AppShell title="Executive Trends" industry="rv"><div className={styles.page}>
    <header className={styles.hero}><div><span>Executive Advisor</span><h1>See verified performance<br/>across <em>reporting periods.</em></h1><p>Compare approved monthly sales activity and leadership-review completion with real data from your locations.</p></div><Link href="/executive"><ArrowRight size={20}/>Command Center</Link></header>
    {data.error && <p className="form-error executive-data-error"><AlertTriangle size={15}/>Some historical records could not be loaded: {data.error}</p>}
    <section className={styles.metrics} aria-label="Approved trend summary">
      <article><span className={`${styles.icon} ${styles.orange}`}><BarChart3/></span><div><h2>Total Approved Sales <Info size={14}/></h2><strong>{data.periods.length ? money(totalSales) : "—"}</strong><small>{previous ? `Latest: ${money(latest!.revenueActual)} · previous: ${money(previous.revenueActual)}` : "Across the selected periods"}</small></div></article>
      <article><span className={`${styles.icon} ${styles.green}`}><UsersRound/></span><div><h2>Leadership Reviews <Info size={14}/></h2><strong>{data.periods.length ? `${completedReviews} / ${data.periods.length}` : "—"}</strong><small>Approved periods completed</small></div></article>
      <article><span className={`${styles.icon} ${styles.blue}`}><MapPin/></span><div><h2>Locations Reporting <Info size={14}/></h2><strong>{latest?.approvedLocations ?? 0}</strong><small>In the latest approved period</small></div></article>
      <article><span className={`${styles.icon} ${styles.purple}`}><CalendarDays/></span><div><h2>Reporting Period</h2><strong>{latest ? monthLabel(latest.period) : new Date().toLocaleDateString(undefined, { month: "short", year: "numeric" })}</strong><small>{latest ? "Latest approved month" : "No approved month yet"}</small></div></article>
    </section>
    <div className={styles.toolbar}><nav className={styles.ranges} aria-label="Trend range">{([6, 12, 24] as const).map((months) => <Link key={months} className={selectedRange === String(months) ? styles.active : ""} href={`/executive/trends?months=${months}${locationQuery}`}><CalendarDays size={17}/>{months} months</Link>)}<Link className={selectedRange === "custom" ? styles.active : ""} href={`/executive/trends?start=${data.start ?? new Date().toISOString().slice(0, 7)}${locationQuery}#custom-range`}><CalendarDays size={17}/>Custom range</Link></nav><form action="/executive/trends" method="get"><input type="hidden" name="months" value={data.months}/>{data.start && <input type="hidden" name="start" value={data.start}/>}{data.end && <input type="hidden" name="end" value={data.end}/>}<label><MapPin size={17}/><span className="sr-only">Location</span><select name="location" defaultValue={data.selectedLocation}><option value="all">All approved locations</option>{data.locations.map((location) => <option value={location.id} key={location.id}>{location.name}</option>)}</select></label><button type="submit">Apply filters</button></form></div>
    <details id="custom-range" className={styles.customRange} open={selectedRange === "custom"}><summary>Choose a custom reporting range</summary><form action="/executive/trends" method="get"><input type="hidden" name="location" value={data.selectedLocation}/><label>From <input className="input" type="month" name="start" defaultValue={data.start}/></label><label>Through <input className="input" type="month" name="end" defaultValue={data.end}/></label><button className="btn btn-primary" type="submit">Show range</button></form></details>
    <section className={styles.history} aria-labelledby="history-title"><div className={styles.historyHead}><span className={`${styles.icon} ${styles.orange}`}><BarChart3/></span><div><h2 id="history-title">Approved Tenant History</h2><p>Every point represents an approved monthly sales record. Missing months remain missing and are never estimated.</p></div><div className={styles.legend}><span><i/>Sales Activity</span><span><i/>Leadership Reviews</span></div></div>
      {data.periods.length ? <div className={styles.historyContent}><div className={styles.chartIntro}><div><strong>Actual compared with target</strong><p>{data.selectedLocation === "all" ? "Combined approved location results" : `Filtered to ${data.locations.find((item) => item.id === data.selectedLocation)?.name}`}</p></div><span>Latest sales pace: {latest?.salesPace ?? "—"}%</span></div><div className="trend-bars">{data.periods.map((item) => <div key={item.period}><strong>{monthLabel(item.period)}</strong><div><span className="trend-bar target" style={{ width: `${Math.round(item.revenueTarget / maximumRevenue * 100)}%` }}><small>{money(item.revenueTarget)} target</small></span><span className="trend-bar actual" style={{ width: `${Math.round(item.revenueActual / maximumRevenue * 100)}%` }}><small>{money(item.revenueActual)} actual</small></span></div></div>)}</div></div> : <div className={styles.empty}><div className={styles.emptyArt}><BarChart3 size={58} strokeWidth={1.4}/></div><h3>No approved historical results yet</h3><p>Approve monthly location results to begin the Executive trend history.<br/>Draft and missing records are intentionally excluded.</p><div className={styles.emptyActions}><Link href="/admin/sales-results"><Plus size={20}/>Open sales results</Link><Link href="/executive/readiness"><BookOpen size={20}/>Learn how trends work</Link></div></div>}
    </section>
    <div className={styles.guides}><article className={styles.tip}><Lightbulb size={45}/><div><h2>Pro Tip</h2><p>Approved data ensures accurate trends and better leadership decisions.</p><Link href="/executive/readiness">Learn about approvals <ArrowRight size={17}/></Link></div></article><article className={styles.features}><BarChart3 size={45}/><div><h2>What You’ll See</h2><ul><li><Check/>Month-over-month sales activity</li><li><Check/>Leadership review completion</li><li><Check/>Performance across all locations</li><li><Check/>Clear trend insights — no forecasts</li></ul></div></article><article className={styles.next}><Target size={45}/><div><h2>Ready to Build Your Story?</h2><p>Approve monthly results, review progress, and turn data into action.</p><Link href="/executive">Go to Command Center <ArrowRight size={18}/></Link></div></article></div>
    {data.periods.length > 0 && <div className={styles.detail}><section className="card"><div className="metric-row"><div><span className="badge blue">Latest approved period</span><h2>{monthLabel(latest!.period)}</h2><p>{latest!.approvedLocations} approved location{latest!.approvedLocations === 1 ? "" : "s"} · {latest!.reviewCompleted ? "Leadership review complete" : "Leadership review pending"}</p></div><div className={`metric trend-change ${data.change === null ? "neutral" : data.change >= 0 ? "positive" : "attention"}`}>{data.change === null ? "—" : <>{data.change >= 0 ? <TrendingUp size={24}/> : <TrendingDown size={24}/>} {signed(data.change, " pts")}</>}</div></div><p>Change in approved sales pace from the previous available period.</p></section>
      {data.comparison && <section className="card executive-period-comparison"><div className="metric-row"><div><span className="badge blue">Selected comparison</span><h2>Compare two approved periods</h2><p>Choose any two available months for the current location filter.</p></div><TrendingUp size={21}/></div><form action="/executive/trends" method="get"><input type="hidden" name="months" value={data.months}/><input type="hidden" name="location" value={data.selectedLocation}/>{data.start && <input type="hidden" name="start" value={data.start}/>}{data.end && <input type="hidden" name="end" value={data.end}/>}<label><span className="label">Starting period</span><select className="input" name="from" defaultValue={data.comparison.from.period}>{data.periods.map((item) => <option value={item.period} key={item.period}>{monthLabel(item.period)}</option>)}</select></label><label><span className="label">Comparison period</span><select className="input" name="to" defaultValue={data.comparison.to.period}>{data.periods.map((item) => <option value={item.period} key={item.period}>{monthLabel(item.period)}</option>)}</select></label><button className="btn btn-secondary" type="submit">Compare periods</button></form><div className="comparison-periods"><article><small>Starting period</small><strong>{monthLabel(data.comparison.from.period)}</strong><span>{money(data.comparison.from.revenueActual)} actual · {data.comparison.from.salesPace ?? "—"}% pace</span></article><div className="comparison-deltas"><span><small>Revenue</small><strong>{signed(data.comparison.revenueChange)}</strong></span><span><small>Sales pace</small><strong>{data.comparison.paceChange === null ? "—" : signed(data.comparison.paceChange, " pts")}</strong></span><span><small>Units</small><strong>{signed(data.comparison.unitChange)}</strong></span><span><small>Leads</small><strong>{signed(data.comparison.leadChange)}</strong></span><span><small>Appointments</small><strong>{signed(data.comparison.appointmentChange)}</strong></span></div><article><small>Comparison period</small><strong>{monthLabel(data.comparison.to.period)}</strong><span>{money(data.comparison.to.revenueActual)} actual · {data.comparison.to.salesPace ?? "—"}% pace</span></article></div></section>}
      <section className="card executive-trend-table"><div className="section-heading"><div><span className="badge blue">Source detail</span><h2>Approved monthly activity</h2><p>Counts and totals are direct sums of approved location records.</p></div><ClipboardCheck size={24}/></div><div className="executive-table-scroll"><table><thead><tr><th>Period</th><th>Locations</th><th>Sales pace</th><th>Units</th><th>Leads</th><th>Appointments</th><th>Review</th></tr></thead><tbody>{data.periods.toReversed().map((item) => <tr key={item.period}><td><strong>{monthLabel(item.period)}</strong></td><td>{item.approvedLocations}</td><td>{item.salesPace === null ? "—" : `${item.salesPace}%`}</td><td>{item.unitsActual} / {item.unitsTarget}</td><td>{item.leads}</td><td>{item.appointments}</td><td><span className={`badge ${item.reviewCompleted ? "blue" : "amber"}`}>{item.reviewCompleted ? "Complete" : "Pending"}</span></td></tr>)}</tbody></table></div></section></div>}
  </div></AppShell>;
}
