import { NextResponse } from "next/server";
import { getViewer } from "@/lib/auth/viewer";
import { createClient } from "@/lib/supabase/server";

async function context(){const viewer=await getViewer();if(!viewer?.organizationId||viewer.demo||!["tenant_admin","platform_owner"].includes(viewer.role))return null;return{viewer,db:await createClient()};}
const ids=(value:unknown)=>Array.isArray(value)?value.filter((id):id is string=>typeof id==="string"&&/^[0-9a-f-]{36}$/i.test(id)).slice(0,500):[];
export async function POST(request:Request){const current=await context();if(!current)return NextResponse.json({error:"Tenant administrator access is required."},{status:403});const body=await request.json().catch(()=>null) as Record<string,unknown>|null;const action=String(body?.action||""),org=current.viewer.organizationId;
  if(action.startsWith("category:")){const id=ids([body?.id])[0],name=String(body?.name||"").trim().slice(0,120);if(action==="category:add"){if(name.length<2)return NextResponse.json({error:"Enter a category name."},{status:400});const{error}=await current.db.from("text_template_categories").insert({organization_id:org,content_group:"practice_scenario",name,position:999});return error?NextResponse.json({error:"That category could not be added."},{status:422}):NextResponse.json({success:true});}if(!id)return NextResponse.json({error:"Invalid category."},{status:400});if(action==="category:rename"){const{data:old}=await current.db.from("text_template_categories").select("name").eq("id",id).eq("organization_id",org).eq("content_group","practice_scenario").single();if(!old||name.length<2)return NextResponse.json({error:"Category not found or name is invalid."},{status:400});const{error}=await current.db.from("text_template_categories").update({name,updated_at:new Date().toISOString()}).eq("id",id).eq("organization_id",org).eq("content_group","practice_scenario");if(!error)await current.db.from("coach_scenarios").update({category:name,updated_at:new Date().toISOString()}).eq("organization_id",org).eq("category",old.name);return error?NextResponse.json({error:"The category could not be renamed."},{status:422}):NextResponse.json({success:true});}const update=action==="category:archive"?{archived:true}:action==="category:restore"?{archived:false}:action==="category:reorder"?{position:Number(body?.position)||0}:null;if(!update)return NextResponse.json({error:"Unknown category action."},{status:400});const{error}=await current.db.from("text_template_categories").update({...update,updated_at:new Date().toISOString()}).eq("id",id).eq("organization_id",org).eq("content_group","practice_scenario");return error?NextResponse.json({error:"The category could not be updated."},{status:422}):NextResponse.json({success:true});}
  const selected=ids(body?.ids);if(!selected.length)return NextResponse.json({error:"Select at least one scenario."},{status:400});let update:Record<string,unknown>|null=null;if(action==="publish")update={status:"published"};if(action==="draft"||action==="restore")update={status:"draft"};if(action==="archive")update={status:"archived"};if(action==="category")update={category:String(body?.category||"").trim().slice(0,120)};if(action==="difficulty"&&["Foundational","Intermediate","Advanced"].includes(String(body?.difficulty)))update={difficulty:body?.difficulty};if(action==="tags"){const tags=String(body?.tags||"").split(",").map(t=>t.trim()).filter(Boolean).slice(0,20),{data}=await current.db.from("coach_scenarios").select("id,tags").eq("organization_id",org).in("id",selected);for(const item of data||[])await current.db.from("coach_scenarios").update({tags:[...new Set([...(item.tags||[]),...tags])].slice(0,20),updated_at:new Date().toISOString()}).eq("id",item.id).eq("organization_id",org);return NextResponse.json({success:true});}if(!update)return NextResponse.json({error:"Unknown scenario action."},{status:400});const{error}=await current.db.from("coach_scenarios").update({...update,updated_at:new Date().toISOString()}).eq("organization_id",org).in("id",selected);return error?NextResponse.json({error:"Scenarios could not be updated."},{status:422}):NextResponse.json({success:true});}
