"use server";
import { revalidatePath } from "next/cache";
import { getViewer } from "@/lib/auth/viewer";
import { createClient } from "@/lib/supabase/server";
import { createAdminClient } from "@/lib/supabase/admin";
import { extractProductModels } from "@/lib/products/document-extraction";

export async function addCompetitorSource(formData: FormData) {
  const viewer = await getViewer(); if (!viewer?.organizationId || !["tenant_admin", "platform_owner", "manager"].includes(viewer.role)) throw new Error("Unauthorized");
  const competitorName = String(formData.get("competitorName") || "").trim(); const sourceUrl = String(formData.get("sourceUrl") || "").trim();
  try { const url = new URL(sourceUrl); if (!/^https?:$/.test(url.protocol)) throw new Error(); } catch { throw new Error("Enter a valid public http or https URL."); }
  if (competitorName.length < 2) throw new Error("Enter a competitor name."); const supabase = await createClient(); const { error } = await supabase.from("competitor_sources").insert({ organization_id: viewer.organizationId, competitor_name: competitorName, source_url: sourceUrl, source_type: "manufacturer_website", created_by: viewer.id }); if (error) throw new Error("This source could not be saved. It may already exist."); revalidatePath("/admin/competitor-sources");
}

export async function deleteCompetitorSource(formData: FormData) {
  const viewer = await getViewer();
  if (!viewer?.organizationId || !["tenant_admin", "platform_owner", "manager"].includes(viewer.role)) throw new Error("Unauthorized");
  const sourceId = String(formData.get("sourceId") || "");
  if (!/^[0-9a-f-]{36}$/i.test(sourceId)) throw new Error("Invalid source.");

  const supabase = await createClient();
  const { error } = await supabase
    .from("competitor_sources")
    .delete()
    .eq("id", sourceId)
    .eq("organization_id", viewer.organizationId);

  if (error) throw new Error("The competitor source could not be deleted.");
  revalidatePath("/admin/competitor-sources");
  revalidatePath("/admin/competitor-sources/review");
}

async function requireManager() { const viewer = await getViewer(); if (!viewer?.organizationId || !["tenant_admin", "platform_owner", "manager"].includes(viewer.role)) throw new Error("Unauthorized"); return viewer; }
export async function changeProductType(formData: FormData) { const viewer=await requireManager(); const id=String(formData.get("productId")||""); const product_type=formData.get("productType")==="our_product"?"our_product":"competitor_product"; if(!/^[0-9a-f-]{36}$/i.test(id)) throw new Error("Invalid product."); const {error}=await (await createClient()).from("products").update({product_type,updated_at:new Date().toISOString()}).eq("id",id).eq("organization_id",viewer.organizationId); if(error) throw new Error("The product type could not be updated."); ["/admin/competitor-sources","/comparisons","/products","/admin/products"].forEach((path)=>revalidatePath(path)); }
export async function approveProduct(formData: FormData) { const viewer=await requireManager(); const id=String(formData.get("productId")||""); if(!/^[0-9a-f-]{36}$/i.test(id)) throw new Error("Invalid product."); const {error}=await (await createClient()).from("products").update({review_status:"approved",status:"published",updated_at:new Date().toISOString()}).eq("id",id).eq("organization_id",viewer.organizationId); if(error) throw new Error("The product could not be approved."); revalidatePath("/admin/competitor-sources"); revalidatePath("/comparisons"); }
export async function deleteProductModel(formData: FormData) { const viewer=await requireManager(); const id=String(formData.get("productId")||""); if(!/^[0-9a-f-]{36}$/i.test(id)) throw new Error("Invalid product."); const {error}=await (await createClient()).from("products").delete().eq("id",id).eq("organization_id",viewer.organizationId); if(error) throw new Error("The product model could not be deleted."); ["/admin/competitor-sources","/admin/products","/products","/comparisons"].forEach((path)=>revalidatePath(path)); }
export async function deleteProductDocument(formData: FormData) { const viewer=await requireManager(); const id=String(formData.get("documentId")||""); if(!/^[0-9a-f-]{36}$/i.test(id)) throw new Error("Invalid document."); const db=await createClient(); const {data}=await db.from("product_documents").select("storage_path").eq("id",id).eq("organization_id",viewer.organizationId).maybeSingle(); if(!data) throw new Error("Document not found."); const {error}=await db.from("product_documents").delete().eq("id",id).eq("organization_id",viewer.organizationId); if(error) throw new Error("The document could not be deleted."); await db.storage.from("product-documents").remove([data.storage_path]); revalidatePath("/admin/competitor-sources"); }
export async function addManualModel(formData: FormData) { const viewer=await requireManager(); const name=String(formData.get("name")||"").trim(); const manufacturer=String(formData.get("manufacturer")||"").trim(); const model=String(formData.get("model")||"").trim(); const year=Number(formData.get("year")||0)||null; const product_type=formData.get("productType")==="competitor_product"?"competitor_product":"our_product"; if(name.length<2) throw new Error("Enter a model name."); const slug=`${name}-${model||"standard"}-${year||""}-${crypto.randomUUID().slice(0,8)}`.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,""); const db=await createClient(); const {error}=await db.from("products").insert({organization_id:viewer.organizationId,name,slug,model,manufacturer,brand:manufacturer,model_year:year,product_category:String(formData.get("category")||"").trim(),product_type,description:String(formData.get("description")||"").trim(),base_price_cents:0,status:"draft",review_status:"pending_review",visual_theme:"blue"}); if(error) throw new Error(error.code==="23505"?"A matching model already exists. Review the existing catalog entry.":"The model could not be saved."); revalidatePath("/admin/competitor-sources"); }
export async function reprocessProductDocument(formData:FormData){const viewer=await requireManager();const id=String(formData.get("documentId")||"");if(!/^[0-9a-f-]{36}$/i.test(id))throw new Error("Invalid document.");const db=createAdminClient();const {data:doc}=await db.from("product_documents").select("storage_path,original_filename,mime_type,initial_product_type,manufacturer").eq("id",id).eq("organization_id",viewer.organizationId).maybeSingle();if(!doc)throw new Error("Document not found.");const {data:organization}=await db.from("organizations").select("industry_template_id").eq("id",viewer.organizationId).maybeSingle();const {data:template}=organization?.industry_template_id?await db.from("industry_templates").select("template_key").eq("id",organization.industry_template_id).maybeSingle():{data:null};const industry=template?.template_key==="golf-cart"?"golf-cart" as const:"generic" as const;await db.from("product_documents").update({processing_status:"processing",processing_error:""}).eq("id",id);try{const {data:fileData,error:downloadError}=await db.storage.from("product-documents").download(doc.storage_path);if(downloadError||!fileData)throw new Error("The source file could not be read.");const models=await extractProductModels(new File([fileData],doc.original_filename,{type:doc.mime_type}),{},industry);await db.from("products").delete().eq("organization_id",viewer.organizationId).eq("source_document_id",id).neq("review_status","approved");for(const item of models){const brand=item.manufacturer||doc.manufacturer;await db.from("products").insert({organization_id:viewer.organizationId,source_document_id:id,product_type:doc.initial_product_type,review_status:"pending_review",status:"draft",name:item.name,slug:`${item.name}-${crypto.randomUUID().slice(0,8)}`.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,""),model:item.model,manufacturer:brand,brand,model_year:item.modelYear,product_category:item.category,description:item.description,specifications:item.specifications,base_price_cents:0,visual_theme:"blue"});}await db.from("product_documents").update({processing_status:"needs_review",models_found:models.length,updated_at:new Date().toISOString()}).eq("id",id);}catch(error){await db.from("product_documents").update({processing_status:"needs_review",processing_error:error instanceof Error?error.message:"Extraction needs review"}).eq("id",id);}revalidatePath("/admin/competitor-sources");}
