import { AppShell } from "@/components/app-shell";
import { PageHeader } from "@/components/page-header";
import Link from "next/link";
import { getViewer } from "@/lib/auth/viewer";
import { createClient } from "@/lib/supabase/server";
import { CompetitorSourceScanButton } from "@/components/competitor-source-scan-button";
import { addCompetitorSource, deleteCompetitorSource } from "./actions";

export default async function CompetitorSourcesPage() {
  const viewer = await getViewer(); const supabase = await createClient(); const sourceResult = viewer?.organizationId ? await supabase.from("competitor_sources").select("id,competitor_name,source_url,is_active,last_checked_at,sync_status").eq("organization_id", viewer.organizationId).order("created_at", { ascending: false }) : { data: [] }; const sources = sourceResult.data || [];
  const allowed = viewer && ["tenant_admin", "platform_owner", "manager"].includes(viewer.role);
  return <AppShell title="Competitor Sources"><PageHeader eyebrow="Competitor products" title="Competitor Sources" description="Add a public manufacturer or category URL, then review discovered products before approving any catalog changes."/>{allowed ? <section className="card form-stack"><h2>Add website source</h2><form action={addCompetitorSource} className="grid grid-2"><input className="input" name="competitorName" required placeholder="Competitor name, e.g. Epic"/><input className="input" name="sourceUrl" required type="url" placeholder="https://manufacturer.example/models"/><button className="btn btn-primary" type="submit">Add source</button></form></section> : <section className="card"><p>Manager access is required to manage competitor sources.</p></section>}<section className="card"><div className="flex items-center justify-between gap-4"><h2>Saved sources</h2>{allowed ? <Link className="btn btn-primary" href="/admin/competitor-sources/review">Review updates</Link> : null}</div>{sources.length ? <div className="table-wrap"><table className="table"><thead><tr><th>Competitor</th><th>Source</th><th>Status</th><th>Last checked</th><th></th></tr></thead><tbody>{sources.map((source: any) => <tr key={source.id}><td>{source.competitor_name}</td><td><a href={source.source_url} target="_blank" rel="noreferrer">{source.source_url}</a></td><td>{source.sync_status}</td><td>{source.last_checked_at ? new Date(source.last_checked_at).toLocaleDateString() : "Not checked"}</td><td>{allowed ? <div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}><CompetitorSourceScanButton sourceId={source.id} /><form action={deleteCompetitorSource}><input type="hidden" name="sourceId" value={source.id}/><button className="btn btn-ghost" type="submit">Delete source</button></form></div> : null}</td></tr>)}</tbody></table></div> : <p>No competitor sources have been added.</p>}<p style={{ marginTop: 12, fontSize: 13, color: "#68738a" }}>Deleting a source stops future checks and removes its scan history. Products you already approved remain in your catalog.</p></section></AppShell>;
}
