/* eslint-disable @typescript-eslint/no-explicit-any */
import Link from "next/link";
import { AppShell } from "@/components/app-shell";
import { PageHeader } from "@/components/page-header";
import { getViewer } from "@/lib/auth/viewer";
import { createClient } from "@/lib/supabase/server";
import { TopScrollTable } from "@/components/top-scroll-table";
import { addManualModel, approveProduct, changeProductType, deleteProductDocument, deleteProductModel, reprocessProductDocument } from "./actions";

export default async function ProductDocumentsPage({searchParams}:{searchParams:Promise<{q?:string;type?:string;status?:string;sort?:string}>}) {
  const filters=await searchParams;
  const viewer=await getViewer(), db=await createClient(), org=viewer?.organizationId;
  const allowed=!!viewer&&["tenant_admin","platform_owner","manager"].includes(viewer.role);
  const [docResult,productResult]=org?await Promise.all([
    db.from("product_documents").select("id,title,manufacturer,initial_product_type,processing_status,models_found,created_at").eq("organization_id",org).order("created_at",{ascending:false}),
    db.from("products").select("id,name,model,manufacturer,brand,model_year,product_category,product_type,review_status,updated_at").eq("organization_id",org).order("updated_at",{ascending:false}).limit(250),
  ]):[{data:[]},{data:[]}]; const docs=docResult.data||[], productRows=productResult.data||[];
  const query=(filters.q||"").trim().toLowerCase(), type=filters.type||"", status=filters.status||"", sort=filters.sort||"updated";
  const products=productRows.filter((product:any)=>{const matchesQuery=!query||[product.name,product.model,product.manufacturer,product.brand,product.product_category].filter(Boolean).join(" ").toLowerCase().includes(query);return matchesQuery&&(!type||product.product_type===type)&&(!status||product.review_status===status);}).sort((a:any,b:any)=>sort==="name"?a.name.localeCompare(b.name):sort==="manufacturer"?(a.manufacturer||a.brand||"").localeCompare(b.manufacturer||b.brand||""):sort==="year"?(b.model_year||0)-(a.model_year||0):new Date(b.updated_at).getTime()-new Date(a.updated_at).getTime());
  return <AppShell title="Product Documents & Models"><PageHeader eyebrow="Product catalog" title="Product Documents & Models" description="Upload product specifications, brochures, and product documentation. Approved models are available throughout RunFloor."/><section className="card form-stack"><div className="metric-row"><div><h2>Find product models</h2><p>Search, filter, and sort the model list below.</p></div><span className="badge blue">{products.length} shown</span></div><form className="grid grid-2" method="get"><input className="input" name="q" defaultValue={filters.q||""} placeholder="Search model, manufacturer, category…"/><select className="input" name="type" defaultValue={type}><option value="">All product types</option><option value="our_product">Our Products</option><option value="competitor_product">Competitor Products</option></select><select className="input" name="status" defaultValue={status}><option value="">All review statuses</option><option value="pending_review">Pending review</option><option value="approved">Approved</option><option value="needs_attention">Needs attention</option></select><select className="input" name="sort" defaultValue={sort}><option value="updated">Newest updated</option><option value="name">Model name</option><option value="manufacturer">Manufacturer</option><option value="year">Model year</option></select><button className="btn btn-secondary">Apply filters</button><a className="btn btn-ghost" href="/admin/competitor-sources">Clear</a></form></section>
    {allowed&&<section className="card form-stack"><div><h2>Extract products from documents</h2><p>Upload comparison sheets, brochures, PDFs, images, or spreadsheets. Detected models are added to this workspace for review.</p></div><form action="/api/product-documents" method="post" encType="multipart/form-data" className="grid grid-2"><input type="hidden" name="returnTo" value="/admin/competitor-sources"/><input className="input" name="files" type="file" multiple required accept=".jpg,.jpeg,.png,.pdf,.doc,.docx,.xlsx,.csv"/><select className="input" name="productType"><option value="our_product">My Products</option><option value="competitor_product">Competitor Products</option></select><input className="input" name="manufacturer" placeholder="Manufacturer (optional)"/><button className="btn btn-primary">Extract and add for review</button></form></section>}
    <section className="card"><h2>Uploaded Documents</h2><div className="table-wrap"><table className="table"><thead><tr><th>Document</th><th>Manufacturer</th><th>Type</th><th>Uploaded</th><th>Status</th><th>Models</th><th>Actions</th></tr></thead><tbody>{docs.map((d:any)=><tr key={d.id}><td>{d.title}</td><td>{d.manufacturer||"—"}</td><td>{d.initial_product_type==="our_product"?"My Product":"Competitor"}</td><td>{new Date(d.created_at).toLocaleDateString()}</td><td>{d.processing_status.replaceAll("_"," ")}</td><td>{d.models_found}</td><td><div style={{display:"flex",gap:6}}><Link className="btn btn-ghost" href={`/api/product-documents/${d.id}/open`} target="_blank">View</Link>{allowed&&<><form action={reprocessProductDocument}><input type="hidden" name="documentId" value={d.id}/><button className="btn btn-ghost">Reprocess</button></form><form action={deleteProductDocument}><input type="hidden" name="documentId" value={d.id}/><button className="btn btn-ghost">Delete</button></form></>}</div></td></tr>)}{!docs.length&&<tr><td colSpan={7}>No product documents have been uploaded yet.</td></tr>}</tbody></table></div></section>
    <section className="card"><h2>Product Models</h2>{allowed&&<form action={addManualModel} className="grid grid-2" style={{marginBottom:16}}><input className="input" name="name" required placeholder="Model name"/><input className="input" name="manufacturer" placeholder="Manufacturer"/><input className="input" name="model" placeholder="Model / variant"/><input className="input" name="year" type="number" min="1900" max="2200" placeholder="Year"/><input className="input" name="category" placeholder="Category"/><select className="input" name="productType"><option value="our_product">My Product</option><option value="competitor_product">Competitor Product</option></select><input className="input" name="description" placeholder="Description (optional)"/><button className="btn btn-primary">Add Model Manually</button></form>}<TopScrollTable><table className="table"><thead><tr><th>Type</th><th>Manufacturer</th><th>Model</th><th>Year</th><th>Category</th><th>Status</th><th>Updated</th><th>Actions</th></tr></thead><tbody>{products.map((p:any)=><tr key={p.id}><td><span className={`badge ${p.product_type==="our_product"?"green":"blue"}`}>{p.product_type==="our_product"?"My Product":"Competitor"}</span></td><td>{p.manufacturer||p.brand||"—"}</td><td>{p.name}{p.model?` · ${p.model}`:""}</td><td>{p.model_year||"—"}</td><td>{p.product_category||"—"}</td><td>{p.review_status.replaceAll("_"," ")}</td><td>{new Date(p.updated_at).toLocaleDateString()}</td><td><div style={{display:"flex",gap:6,alignItems:"center"}}><Link className="btn btn-ghost" href={`/admin/products/${p.id}/edit`}>Edit</Link>{allowed&&<>{p.review_status!=="approved"&&<form action={approveProduct}><input type="hidden" name="productId" value={p.id}/><button className="btn btn-ghost">Approve</button></form>}<form action={changeProductType} style={{display:"flex",gap:6}}><input type="hidden" name="productId" value={p.id}/><select className="input" name="productType" defaultValue={p.product_type} aria-label={`Change type for ${p.name}`} style={{minWidth:150}}><option value="our_product">Our Product</option><option value="competitor_product">Competitor Product</option></select><button className="btn btn-ghost">Save</button></form><form action={deleteProductModel}><input type="hidden" name="productId" value={p.id}/><button className="btn btn-ghost danger-button">Delete</button></form></>}</div></td></tr>)}{!products.length&&<tr><td colSpan={8}>No product models are available.</td></tr>}</tbody></table></TopScrollTable></section>
  </AppShell>;
}
/* eslint-disable @typescript-eslint/no-explicit-any */
