/* eslint-disable @typescript-eslint/no-explicit-any */
import "server-only";
import { getViewer } from "@/lib/auth/viewer";
import { createClient } from "@/lib/supabase/server";

type Scope = "company" | "location" | "employee";
export type DashboardData = { allowed: boolean; team: boolean; scope: Scope; title: string; subtitle: string; locations: {id:string;name:string}[]; employees: {id:string;name:string;role:string;locationId:string|null;location:string;questions:number;messages:number;training:number;confidence:string;lastActivity:string}[]; metrics:{questions:number;messages:number;training:number;confidence:string}; selectedLocation?:string; selectedEmployee?:string };

const demoEmployees = [
  {id:"demo-amy",name:"Amy Parker",role:"Manager",locationId:"demo-mb",location:"Myrtle Beach",questions:64,messages:28,training:88,confidence:"4.7",lastActivity:"12 min ago"},
  {id:"demo-john",name:"John Smith",role:"Salesperson",locationId:"demo-mb",location:"Myrtle Beach",questions:42,messages:19,training:76,confidence:"4.4",lastActivity:"38 min ago"},
  {id:"demo-maya",name:"Maya Stone",role:"Salesperson",locationId:"demo-nmb",location:"North Myrtle Beach",questions:53,messages:24,training:91,confidence:"4.8",lastActivity:"8 min ago"},
];
function summarize(employees: DashboardData["employees"]) { const count=employees.length || 1; const scores=employees.map(e=>Number(e.confidence)).filter(Number.isFinite); return {questions:employees.reduce((n,e)=>n+e.questions,0),messages:employees.reduce((n,e)=>n+e.messages,0),training:Math.round(employees.reduce((n,e)=>n+e.training,0)/count),confidence:scores.length?(scores.reduce((sum,score)=>sum+score,0)/scores.length).toFixed(1):"—"}; }

export async function getDashboardData(input: {view?:string;locationId?:string;employeeId?:string}): Promise<DashboardData> {
 const viewer=await getViewer(); if (!viewer) return {allowed:false,team:false,scope:"employee",title:"Dashboard",subtitle:"Sign in to view performance.",locations:[],employees:[],metrics:{questions:0,messages:0,training:0,confidence:"—"}};
 const requested:Scope=input.employeeId === "team-overview" || input.locationId === "team-overview" ? "company" : (input.view === "company" || input.view === "location" || input.view === "employee" ? input.view : (viewer.role === "salesperson" ? "employee" : "company"));
 if (viewer.demo) { const locations=[{id:"demo-mb",name:"Myrtle Beach"},{id:"demo-nmb",name:"North Myrtle Beach"}]; const scope=viewer.role === "salesperson" ? "employee" : requested; const selectedLocation=input.locationId && locations.some(l=>l.id===input.locationId) ? input.locationId : locations[0].id; const pool=scope === "location" ? demoEmployees.filter(e=>e.locationId===selectedLocation) : scope === "employee" ? demoEmployees.filter(e=>e.id === (input.employeeId || "demo-john")) : demoEmployees; return {allowed:true,team:viewer.role!=="salesperson",scope,title:scope === "company" ? "BGC — Company Overview" : scope === "location" ? `Location: ${locations.find(l=>l.id===selectedLocation)?.name}` : `${pool[0]?.name || "Your"} performance`,subtitle:scope === "company" ? "Performance across all BGC locations." : scope === "location" ? `Performance for ${locations.find(l=>l.id===selectedLocation)?.name}.` : `Performance and training activity for ${pool[0]?.name || "you"}.`,locations,employees:pool,metrics:summarize(pool),selectedLocation,selectedEmployee:pool[0]?.id}; }
 const supabase=await createClient(); const {data: membership}=await supabase.from("organization_memberships").select("location_id").eq("organization_id",viewer.organizationId).eq("user_id",viewer.id).eq("status","active").maybeSingle();
 const isAdmin=["tenant_admin","platform_owner"].includes(viewer.role); const {data: assigned}=isAdmin ? await supabase.from("locations").select("id,name").eq("organization_id",viewer.organizationId).order("name") : await supabase.from("organization_member_locations").select("location_id,locations(id,name)").eq("organization_id",viewer.organizationId).eq("user_id",viewer.id);
 const locations=(isAdmin ? assigned || [] : (assigned || []).map((row:any)=>row.locations).filter(Boolean)) as {id:string;name:string}[];
 const allowedLocation=input.locationId && locations.some(l=>l.id===input.locationId) ? input.locationId : (membership?.location_id || locations[0]?.id);
 const team=isAdmin || viewer.role === "manager";
 const corporateLocation=locations.find((location)=>location.name.trim().toLowerCase()==="corporate");
 const scope:Scope=team ? (input.locationId && input.locationId===corporateLocation?.id ? "company" : requested) : "employee";
 const {data: members}=await supabase.from("organization_memberships").select("user_id,role,location_id,profiles(full_name),locations(name)").eq("organization_id",viewer.organizationId).eq("status","active");
 const permitted=(members || []).filter((row:any)=>isAdmin || row.user_id===viewer.id || (viewer.role==="manager" && locations.some(l=>l.id===row.location_id)));
 const ids=permitted.map((row:any)=>row.user_id); const [{data:events},{data:progress},{data:responses}]=await Promise.all([supabase.from("performance_events").select("user_id,event_type,created_at").eq("organization_id",viewer.organizationId).in("user_id",ids),supabase.from("training_progress").select("user_id,status,updated_at").eq("organization_id",viewer.organizationId).in("user_id",ids),supabase.from("coach_responses").select("user_id,score,created_at").eq("organization_id",viewer.organizationId).in("user_id",ids)]);
 const employees=permitted.map((row:any)=>{const personEvents=(events||[]).filter((e:any)=>e.user_id===row.user_id);const personProgress=(progress||[]).filter((p:any)=>p.user_id===row.user_id);const scores=(responses||[]).filter((r:any)=>r.user_id===row.user_id).map((r:any)=>Number(r.score)).filter(Number.isFinite);return {id:row.user_id,name:row.profiles?.full_name||"Team member",role:row.role,locationId:row.location_id,location:row.locations?.name||"Unassigned",questions:personEvents.filter((e:any)=>e.event_type==="assistant_question_answered").length,messages:personEvents.filter((e:any)=>e.event_type==="message_created").length,training:personProgress.length?Math.round(personProgress.filter((p:any)=>p.status==="completed").length/personProgress.length*100):0,confidence:scores.length?(scores.reduce((a:number,b:number)=>a+b,0)/scores.length).toFixed(1):"—",lastActivity:personEvents[0]?.created_at ? new Date(personEvents[0].created_at).toLocaleDateString() : "No activity"};});
 const selected=scope==="location"?employees.filter(e=>e.locationId===allowedLocation):scope==="employee"?employees.filter(e=>e.id===(input.employeeId||viewer.id)):employees; const subject=scope==="location"?locations.find(l=>l.id===allowedLocation)?.name:scope==="employee"?selected[0]?.name:viewer.organizationName;
 return {allowed:true,team,scope,title:scope==="company"?`${viewer.organizationName} — Company Overview`:scope==="location"?`Location: ${subject}`:`${subject||"Your"} performance`,subtitle:scope==="company"?`Performance across all ${viewer.organizationName} locations.`:scope==="location"?`Performance for ${subject}.`:`Performance and training activity for ${subject||"you"}.`,locations,employees:selected,metrics:summarize(selected),selectedLocation:allowedLocation,selectedEmployee:selected[0]?.id};
}
