"use client";
import Link from "next/link";
import {ArrowRight,BarChart3,BookOpenCheck,Bot,BrainCircuit,ChevronDown,CirclePlay,ClipboardCheck,Gauge,GraduationCap,MessageSquareText,ShieldCheck,Target,UsersRound} from "lucide-react";
import {useState} from "react";
import { BrandLogo } from "@/components/brand-logo";

const features=[[Bot,"AI Sales Assistant","Instant answers, customer conversations, objection support, email/text assistance, and selling guidance."],[GraduationCap,"Sales Coach","AI role-play, objection handling, coaching, and adaptive training."],[BookOpenCheck,"Product Knowledge","Centralized product information, specifications, comparisons, and approved sales information."],[MessageSquareText,"Conversations","Capture, review, and improve sales conversations."],[Target,"Opportunities","Manage opportunities, assignments, stores, employees, and sales activity."],[BarChart3,"Reports & Scorecards","Performance visibility, KPIs, coaching opportunities, and management insights."],[ClipboardCheck,"Content & Knowledge Library","Training materials, SOPs, playbooks, documents, and approved company knowledge."],[ShieldCheck,"Admin & Settings","Locations, employees, roles, permissions, templates, and platform configuration."]];
const people={"Sales Representatives":["Get accurate product answers in the moment.","Practice tough conversations before the customer arrives.","Follow up with consistent, dealership-approved messaging."],"Sales Managers":["See where each rep needs coaching.","Create a shared standard for conversations and product knowledge.","Turn daily activity into focused development."],"General Managers":["Connect sales execution to the broader dealership plan.","Keep every location aligned on the same playbooks.","Surface gaps before they become performance problems."],"Multi-Location Leadership":["Give every store one connected sales system.","Compare execution and coaching needs across locations.","Scale consistent knowledge without adding manager dependency."],"Ownership / Executives":["See the signals behind sales performance.","Connect priorities, accountability, and results.","Make decisions from approved, visible operational data."]};
export default function Home(){const [role,setRole]=useState<keyof typeof people>("Sales Representatives");const [all,setAll]=useState(false);return <main className="rf-landing"><header className="rf-nav"><Link href="/" className="rf-brand" aria-label="RunFloor home"><BrandLogo priority/></Link><nav><details><summary>Platform <ChevronDown size={14}/></summary><div><a href="#platform">Platform overview</a><a href="#advisors">AI advisors</a></div></details><details><summary>Solutions <ChevronDown size={14}/></summary><div><a href="#roles">By role</a><Link href="/coach">Sales coaching</Link></div></details><a href="#resources">Resources</a><a href="#pricing">Pricing</a></nav><div className="rf-nav-actions"><Link href="/demo">View Demo</Link><Link className="rf-button small" href="/login">Sign In <ArrowRight size={15}/></Link></div></header>
<section className="rf-hero"><div><p className="rf-kicker">RUN YOUR SALES FLOOR.</p><h1>Every rep, ready for every conversation.</h1><p className="rf-lead">The AI-powered sales enablement platform built for dealerships.</p><p className="rf-actions"><Link className="rf-button" href="/demo">Explore the RunFloor Platform <ArrowRight size={17}/></Link><a className="rf-watch" href="#platform"><CirclePlay size={19}/> Watch Demo</a></p><div className="rf-proof"><span><ShieldCheck/>Product Knowledge</span><span><MessageSquareText/>Consistent Messaging</span><span><GraduationCap/>On-Demand Coaching</span></div></div><div className="rf-workspace"><div className="preview-head"><b>RF</b><span>Sales workspace</span><i/></div><div className="preview-main"><aside><b>Overview</b><span>Sales Assistant</span><span>Products</span><span>Coaching</span><span>Performance</span></aside><section><p>Good morning, team</p><h3>Ready for today&apos;s floor?</h3><small>Everything your people need, in one connected workspace.</small><div className="preview-metrics"><b><small>Product answers</small>Ready</b><b><small>Coaching focus</small>Discovery</b><b><small>Team rhythm</small>On track</b></div><article><Bot size={19}/><span><strong>Ask the Sales Assistant</strong><small>Compare models, prepare for an objection, or build a follow-up.</small></span></article></section></div></div></section>
<section className="rf-advisors" id="advisors"><div className="rf-intro"><p className="rf-kicker">YOUR AI ADVISORY TEAM</p><h2>More than answers. A better way to run the floor.</h2></div><div className="rf-advisor-grid">{[[GraduationCap,"Sales Coach","Train & role play","Practice meaningful customer conversations and receive adaptive coaching."],[ClipboardCheck,"Operations Assistant","Processes & tasks","Turn repeatable work into clear, accountable execution."],[BrainCircuit,"Business Growth Advisor","Strategy & insights","Connect action plans with the work that improves results."],[Gauge,"Executive Advisor","KPIs & performance","Make leadership decisions from visible, approved data."]].map(([Icon,title,sub,copy])=><article key={title as string}><span><Icon size={23}/></span><div><h3>{title as string}</h3><p>{sub as string}</p><small>{copy as string}</small></div></article>)}</div></section>
<section className="rf-platform" id="platform"><div className="rf-heading"><div><p className="rf-kicker">ONE CONNECTED PLATFORM</p><h2>Everything your team needs to win.</h2><p>One platform. Every rep. Any location.</p></div><button onClick={()=>setAll(!all)}>{all?"Show core features":"See All Platform Features"}<ArrowRight size={16}/></button></div><div className="rf-features">{features.slice(0,all?8:6).map(([Icon,title,copy])=><article key={title as string}><Icon size={22}/><h3>{title as string}</h3><p>{copy as string}</p><ArrowRight size={17}/></article>)}</div></section>
<section className="rf-connection"><div><p className="rf-kicker">THE RUNFLOOR SYSTEM</p><h2>From the sales floor to a clearer next move.</h2><p>RunFloor connects the work your team already does instead of forcing people to manage disconnected tools and information.</p></div><div className="rf-flow">{["People","Products","Knowledge","Conversations","Coaching","Opportunities","Performance"].map((x,i)=><span key={x}><b>0{i+1}</b>{x}</span>)}</div></section>
<section className="rf-roles" id="roles"><div className="rf-intro"><p className="rf-kicker">BUILT FOR THE WHOLE DEALERSHIP</p><h2>Useful at every level of the business.</h2></div><div className="rf-role-grid"><div className="rf-role-tabs">{Object.keys(people).map(x=><button className={role===x?"selected":""} onClick={()=>setRole(x as keyof typeof people)} key={x}>{x}<ArrowRight size={16}/></button>)}</div><article><UsersRound/><p className="rf-kicker">{role}</p><h3>Make the next interaction count.</h3><ul>{people[role].map(x=><li key={x}><ShieldCheck size={16}/>{x}</li>)}</ul><Link className="rf-button dark" href="/demo">Explore RunFloor <ArrowRight size={16}/></Link></article></div></section>
<section className="rf-performance" id="performance"><div><p className="rf-kicker">PERFORMANCE, MADE VISIBLE</p><h2>Give every salesperson a stronger path to performance.</h2><p>RunFloor brings knowledge, conversation quality, coaching, and accountability into the same system.</p></div><div>{["Better prepared salespeople","Faster access to product knowledge","More consistent messaging","Stronger objection handling","Better coaching visibility","Reduced manager dependency","Improved accountability","Higher sales performance"].map(x=><span key={x}><ShieldCheck size={18}/>{x}</span>)}</div></section>
<section className="rf-proof-section"><p className="rf-kicker">DEALERSHIP-READY BY DESIGN</p><h2>Built to make space for the proof that matters.</h2><p>Customer stories and dealership results belong here when they are verified. Until then, RunFloor lets the product speak for itself.</p></section>
<section className="rf-cta" id="pricing"><BrandLogo compact/><div><p className="rf-kicker">READY WHEN YOUR TEAM IS</p><h2>Ready to run a better sales floor?</h2><p>See how RunFloor can help your team sell smarter, coach better, and create a more consistent customer experience.</p></div><p className="rf-actions"><Link className="rf-button" href="/demo">Get a Demo <ArrowRight size={17}/></Link><Link className="rf-button outline" href="/dashboard">Explore RunFloor</Link></p></section>
<footer className="rf-footer" id="resources"><div><span className="rf-brand"><BrandLogo/></span></div>{[["Platform","Sales Assistant","Sales Coach","Product Knowledge","Performance"],["Solutions","Sales teams","Managers","Multi-location","Executive leadership"],["Resources","Product updates","Knowledge library","Support","Demo"],["Company","About RunFloor","Contact","Careers","Privacy"],["Legal","Privacy","Terms","Security"]].map(([head,...links])=><div key={head as string}><strong>{head as string}</strong>{links.map(x=><a href="#" key={x as string}>{x as string}</a>)}</div>)}</footer></main>}
