import Link from "next/link";
import { AlertTriangle, ArrowRight, BellRing, BookOpen, CalendarDays, CheckCircle2, ClipboardList, Compass, History, Settings, Target, UserRoundX, UsersRound } from "lucide-react";
import { redirect } from "next/navigation";
import { AppShell } from "@/components/app-shell";
import { ReportingPeriodSelector } from "@/components/reporting-period-selector";
import { executiveReviewStatusLabel } from "@/lib/executive/accountability";
import { getExecutiveAccountability } from "@/lib/executive/accountability-repository";
import styles from "./accountability.module.css";

const dateLabel = (value: string) => value ? new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", year: "numeric" }).format(new Date(`${value}T12:00:00`)) : "No due date";
const timeLabel = (value: string) => new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", hour: "numeric", minute: "2-digit" }).format(new Date(value));

export default async function ExecutiveAccountabilityPage({ searchParams }: { searchParams: Promise<{ period?: string; notice?: string; owner?: string; activity?: string }> }) {
  const query = await searchParams;
  const data = await getExecutiveAccountability(query.period);
  if (!data.canView) redirect("/dashboard");
  const noticeFilter = query.notice === "reminder" || query.notice === "escalation" ? query.notice : "all";
  const ownerFilter = query.owner ?? "all";
  const activityFilter = query.activity === "created" || query.activity === "status" || query.activity === "notes" ? query.activity : "all";
  const owners = [...new Set(data.reviews.map((review) => review.ownerName.trim()).filter(Boolean))].sort();
  const notices = data.notifications.filter((notice) => noticeFilter === "all" || notice.level === noticeFilter);
  const reviews = data.reviews.filter((review) => ownerFilter === "all" || (ownerFilter === "unassigned" ? !review.ownerName.trim() : review.ownerName === ownerFilter));
  const history = data.history.filter((item) => activityFilter === "all" || (activityFilter === "created" ? !item.previousStatus : activityFilter === "notes" ? Boolean(item.reviewNote) : Boolean(item.previousStatus)));
  const cards = [
    ["Active ownership", data.summary.active, "Acknowledged or in progress", UsersRound],
    ["Completed", data.summary.completed, `${data.summary.completionRate}% of reviewed priorities`, CheckCircle2],
    ["Overdue", data.summary.overdue, "Past due and still active", CalendarDays],
    ["Unassigned", data.summary.unassigned, "Needs a named owner", UserRoundX],
  ] as const;
  return <AppShell title="Executive Accountability" industry="rv"><div className={styles.page}>
    <header className={styles.hero}><div><span>Executive Advisor</span><h1>Turn leadership priorities<br/>into <em>accountable action.</em></h1><p>See ownership, due dates, completion, notices, and the full review trail for one reporting period.</p></div><Link href="/admin/executive"><Settings size={18}/>Notice rules</Link></header>
    {data.error && <p className="form-error executive-data-error"><AlertTriangle size={15}/>Some accountability data could not be loaded: {data.error}</p>}
    <div className={styles.topRow}><div className={styles.period}><span className={styles.icon}><CalendarDays size={25}/></span><ReportingPeriodSelector action="/executive/accountability" periods={data.availablePeriods} selected={data.reportingPeriod} label="Accountability period"/></div><div className={styles.tip}><Target size={36}/><div><strong>Stay on track</strong><p>Clear owners. Clear due dates.<br/>Real progress.</p></div></div></div>
    <section className={styles.metrics} aria-label="Accountability summary">{cards.map(([label, value, context, Icon], index) => <article key={label}><span className={`${styles.metricIcon} ${styles[`tone${index}`]}`}><Icon size={27}/></span><div><h2>{label}</h2><strong>{value}</strong><p>{context}</p></div></article>)}</section>
    <section className={styles.panels}>
      <article className={styles.panel}><div className={styles.panelHead}><span className={styles.icon}><BellRing size={24}/></span><div><h2>Reminders and escalations</h2><p>{data.settings.enabled ? `Reminders begin ${data.settings.remindBeforeDays} days before due; escalation begins after ${data.settings.escalateAfterDays} overdue days.` : "Accountability notices are disabled for this organization."}</p></div><form action="/executive/accountability" method="get"><input type="hidden" name="period" value={data.reportingPeriod}/><input type="hidden" name="owner" value={ownerFilter}/><input type="hidden" name="activity" value={activityFilter}/><label className="sr-only" htmlFor="notice-filter">Notice status</label><select id="notice-filter" name="notice" defaultValue={noticeFilter} aria-label="Notice status"><option value="all">All statuses</option><option value="reminder">Reminders</option><option value="escalation">Escalations</option></select><button type="submit" className={styles.applyFilter}>Apply notice filter</button></form></div>{notices.length ? <div className={styles.list}>{notices.map((notice) => <div key={`${notice.priorityKey}-${notice.level}`}><span className={`badge ${notice.level === "escalation" ? "amber" : "blue"}`}>{notice.title}</span><strong>{data.names[notice.priorityKey] ?? notice.priorityKey.replaceAll("-", " ")}</strong><p>{notice.explanation}</p><small>{notice.ownerName}{notice.dueDate ? ` · Due ${dateLabel(notice.dueDate)}` : " · No due date"}</small></div>)}</div> : <div className={styles.empty}><BellRing size={56}/><h3>{noticeFilter === "all" ? "No notices require attention" : `No ${noticeFilter} notices`}</h3><p>New notices appear automatically from active review owners and due dates.</p><Link href="/admin/executive"><Settings size={17}/>View notice rules</Link></div>}</article>
      <article className={styles.panel}><div className={styles.panelHead}><span className={styles.icon}><UsersRound size={24}/></span><div><h2>Priority owners and commitments</h2><p>The current review status of each priority in this period.</p></div><form action="/executive/accountability" method="get"><input type="hidden" name="period" value={data.reportingPeriod}/><input type="hidden" name="notice" value={noticeFilter}/><input type="hidden" name="activity" value={activityFilter}/><label className="sr-only" htmlFor="owner-filter">Priority owner</label><select id="owner-filter" name="owner" defaultValue={ownerFilter} aria-label="Priority owner"><option value="all">All owners</option><option value="unassigned">Unassigned</option>{owners.map((owner) => <option key={owner} value={owner}>{owner}</option>)}</select><button type="submit" className={styles.applyFilter}>Apply owner filter</button></form></div>{reviews.length ? <div className={styles.tableScroll}><table><thead><tr><th>Priority</th><th>Status</th><th>Owner</th><th>Due</th><th>Updated</th></tr></thead><tbody>{reviews.map((review) => <tr key={review.id}><td><strong>{data.names[review.priorityKey] ?? review.priorityKey.replaceAll("-", " ")}</strong></td><td><span className={`badge ${review.status === "completed" ? "blue" : review.status === "open" ? "amber" : ""}`}>{executiveReviewStatusLabel[review.status]}</span></td><td>{review.ownerName || "Unassigned"}</td><td>{dateLabel(review.dueDate)}</td><td>{timeLabel(review.updatedAt)}</td></tr>)}</tbody></table></div> : <div className={styles.empty}><UsersRound size={56}/><h3>{ownerFilter === "all" ? "No priority reviews yet" : "No reviews for this owner"}</h3><p>Review a recommended priority in the Command Center to begin tracking.</p><Link href={`/executive?period=${data.reportingPeriod}`}>Go to Command Center <ArrowRight size={17}/></Link></div>}</article>
    </section>
    <section className={`${styles.panel} ${styles.history}`}><div className={styles.panelHead}><span className={styles.icon}><History size={24}/></span><div><h2>Review trail</h2><strong>Priority history</strong><p>Append-only changes recorded when a manager updates a review.</p></div><form action="/executive/accountability" method="get"><input type="hidden" name="period" value={data.reportingPeriod}/><input type="hidden" name="notice" value={noticeFilter}/><input type="hidden" name="owner" value={ownerFilter}/><label className="sr-only" htmlFor="activity-filter">Review activity</label><select id="activity-filter" name="activity" defaultValue={activityFilter} aria-label="Review activity"><option value="all">All activities</option><option value="created">Created</option><option value="status">Status updates</option><option value="notes">With notes</option></select><button type="submit" className={styles.applyFilter}>Apply activity filter</button></form></div>{history.length ? <ol className="executive-history-list">{history.map((item, index) => <li key={`${item.id}-${item.changedAt}-${index}`}><span className="executive-history-dot"/><div><div className="metric-row"><strong>{data.names[item.priorityKey] ?? item.priorityKey.replaceAll("-", " ")}</strong><time>{timeLabel(item.changedAt)}</time></div><p>{item.previousStatus ? `${executiveReviewStatusLabel[item.previousStatus]} → ` : "Created as "}<b>{executiveReviewStatusLabel[item.status]}</b>{item.ownerName ? ` · ${item.ownerName}` : " · Unassigned"}</p>{item.reviewNote && <small>{item.reviewNote}</small>}</div></li>)}</ol> : <div className={styles.empty}><ClipboardList size={54}/><h3>{activityFilter === "all" ? "No history to show yet" : "No matching activity"}</h3><p>Updates, ownership changes, and status revisions will appear here.</p><Link href="/executive/readiness"><BookOpen size={17}/>Learn how it works</Link></div>}</section>
    <footer className={styles.footer}><Compass size={46}/><div><h2>Accountability drives results.</h2><p>Review priorities, confirm ownership, and keep your team moving forward.</p></div><Link href={`/executive?period=${data.reportingPeriod}`}>Go to Command Center <ArrowRight size={17}/></Link></footer>
  </div></AppShell>;
}
