"use client";

import { useDeferredValue, useEffect, useMemo, useRef, useState } from "react";
import { ChevronDown, ChevronLeft, ChevronRight, MoreVertical, Plus, Search, Settings2, Target, X } from "lucide-react";
import { useRouter } from "next/navigation";
import { AdminCoachScenarioForm } from "@/components/admin-coach-scenario-form";
import { CoachScenarioImporter } from "@/components/coach-scenario-importer";
import { getScenarioPage, type ScenarioPage } from "@/app/admin/coach/scenario-query";
import type { CoachScenario } from "@/lib/coach/types";

type Category = { id: string; name: string; position: number; archived: boolean };
const SCENARIO_PAGE_SIZE = 100;

export function AdminCoachScenarioManager({ initialPage, facets, categories, canManage, demo }: { initialPage: ScenarioPage; facets: { total: number; categoryCounts: Record<string, number>; tags: string[] }; categories: Category[]; canManage: boolean; demo: boolean }) {
  const router = useRouter(); const first = useRef(true);
  const [pageData, setPageData] = useState(initialPage), [page, setPage] = useState(1), [loading, setLoading] = useState(false);
  const [query, setQuery] = useState(""), deferredQuery = useDeferredValue(query), [category, setCategory] = useState("All Scenarios"), [difficulty, setDifficulty] = useState("all"), [tag, setTag] = useState("all"), [status, setStatus] = useState("all"), [sort, setSort] = useState("updated");
  const [selected, setSelected] = useState<CoachScenario | null>(null), [creating, setCreating] = useState(false), [checked, setChecked] = useState<string[]>([]), [menuId, setMenuId] = useState("");
  const [manageOpen, setManageOpen] = useState(false), [newCategory, setNewCategory] = useState(""), [error, setError] = useState(""), [busy, setBusy] = useState(false), [dragged, setDragged] = useState("");
  const activeCategories = useMemo(() => categories.filter((item) => !item.archived), [categories]); const archivedCategories = useMemo(() => categories.filter((item) => item.archived), [categories]);
  const categoryNames = activeCategories.map((item) => item.name); const editorOpen = creating || Boolean(selected); const pages = Math.max(1, Math.ceil(pageData.total / SCENARIO_PAGE_SIZE));
  useEffect(() => { if (first.current) { first.current = false; return; } let cancelled = false; setLoading(true); void getScenarioPage({ category, difficulty, tag, status, sort, query: deferredQuery, page }).then((result) => { if (!cancelled) { setPageData(result); setLoading(false); if (result.page !== page) setPage(result.page); } }); return () => { cancelled = true; }; }, [category, difficulty, tag, status, sort, deferredQuery, page, initialPage]);
  async function act(payload: Record<string, unknown>) { setBusy(true); setError(""); const response = await fetch("/api/admin/coach/scenario-actions", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const data = await response.json().catch(() => ({})); setBusy(false); if (!response.ok) { setError(data.error || "The action could not be completed."); return false; } setChecked([]); router.refresh(); return true; }
  async function bulk(action: string) { const payload: Record<string, unknown> = { action, ids: checked }; if (action === "category") { const value = window.prompt("Move selected scenarios to which category?", categoryNames[0] || ""); if (!value) return; payload.category = value; } if (action === "difficulty") { const value = window.prompt("Difficulty: Foundational, Intermediate, or Advanced", "Intermediate"); if (!value) return; payload.difficulty = value; } if (action === "tags") { const value = window.prompt("Add tags (comma separated):"); if (!value) return; payload.tags = value; } await act(payload); }
  async function categoryAction(action: string, item?: Category, value?: string | number) { const payload: Record<string, unknown> = { action: `category:${action}`, id: item?.id }; if (action === "add" || action === "rename") payload.name = value; if (action === "reorder") payload.position = value; if (await act(payload)) setNewCategory(""); }
  return <div className={`text-template-admin ${editorOpen ? "editor-open" : ""}`}>
    <div className="text-template-titlebar"><div><span className="eyebrow">Tenant coaching content</span><h1>Practice Scenarios</h1><p>Create, organize, import, and manage multi-round sales practice scenarios for your team.</p><small>Platform methodology remains separately controlled.</small></div><div className="text-template-primary-actions"><CoachScenarioImporter categories={categoryNames}/><button className="btn btn-primary" type="button" onClick={() => { setSelected(null); setCreating(true); }}><Plus/> New Scenario</button></div></div>
    <nav aria-label="Scenario categories" className="template-category-tabs"><button className={category === "All Scenarios" ? "active" : ""} onClick={() => { setCategory("All Scenarios"); setPage(1); }}><Target/> All Scenarios <span>{facets.total}</span></button>{activeCategories.slice(0,7).map((item) => <button className={category === item.name ? "active" : ""} key={item.id} onClick={() => { setCategory(item.name); setPage(1); }}>{item.name} <span>{facets.categoryCounts[item.name] || 0}</span></button>)}{activeCategories.length > 7 && <label className="template-more-categories">More <ChevronDown/><select aria-label="More scenario categories" value={activeCategories.slice(7).some((item) => item.name === category) ? category : ""} onChange={(event) => { setCategory(event.target.value); setPage(1); }}><option value="" disabled>Choose category</option>{activeCategories.slice(7).map((item) => <option key={item.id}>{item.name}</option>)}</select></label>}</nav>
    <section className="template-catalog" aria-label="Workspace practice scenarios"><div className="template-catalog-tools"><label><Search/><input aria-label="Search scenarios" placeholder="Search scenarios…" value={query} onChange={(event) => { setQuery(event.target.value); setPage(1); }}/></label><select aria-label="Difficulty" value={difficulty} onChange={(event) => { setDifficulty(event.target.value); setPage(1); }}><option value="all">All difficulties</option><option>Foundational</option><option>Intermediate</option><option>Advanced</option></select><select aria-label="Tag" value={tag} onChange={(event) => { setTag(event.target.value); setPage(1); }}><option value="all">All tags</option>{facets.tags.map((value) => <option key={value}>{value}</option>)}</select><select aria-label="Status" value={status} onChange={(event) => { setStatus(event.target.value); setPage(1); }}><option value="all">All statuses</option><option value="published">Published</option><option value="draft">Draft</option><option value="archived">Archived</option></select><select aria-label="Sort scenarios" value={sort} onChange={(event) => { setSort(event.target.value); setPage(1); }}><option value="updated">Recently updated</option><option value="oldest">Oldest updated</option><option value="az">Title A–Z</option><option value="difficulty">Difficulty</option></select><button className="btn btn-secondary" type="button" onClick={() => setManageOpen(true)}><Settings2/> Manage categories</button></div>
      {checked.length > 0 && <div className="template-bulk-bar"><strong>{checked.length} selected</strong><button onClick={() => bulk("publish")}>Publish</button><button onClick={() => bulk("category")}>Change category</button><button onClick={() => bulk("difficulty")}>Change difficulty</button><button onClick={() => bulk("tags")}>Add tags</button><button onClick={() => bulk("archive")}>Archive</button><button onClick={() => setChecked([])}>Clear</button></div>}{error && <p className="form-error">{error}</p>}{pageData.error && <p className="form-error">{pageData.error}</p>}
      <div className="template-table-wrap" aria-busy={loading}><table className="template-table"><thead><tr><th><input type="checkbox" aria-label="Select visible scenarios" checked={pageData.rows.length > 0 && pageData.rows.every((item) => checked.includes(item.id))} onChange={(event) => setChecked(event.target.checked ? [...new Set([...checked, ...pageData.rows.map((item) => item.id)])] : checked.filter((id) => !pageData.rows.some((item) => item.id === id)))}/></th><th>Scenario name</th><th>Category</th><th>Difficulty</th><th>Persona</th><th>Duration</th><th>Status</th><th>Updated</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{pageData.rows.map((item) => <tr key={item.id} onClick={() => { setSelected(item); setCreating(false); }}><td><input type="checkbox" aria-label={`Select ${item.title}`} checked={checked.includes(item.id)} onClick={(event) => event.stopPropagation()} onChange={(event) => setChecked(event.target.checked ? [...checked,item.id] : checked.filter((id) => id !== item.id))}/></td><td><strong>{item.title}</strong></td><td><span className="category-pill">{item.category}</span></td><td>{item.difficulty}</td><td>{item.customer.length > 54 ? `${item.customer.slice(0,54)}…` : item.customer}</td><td>{item.rounds.length} rounds</td><td><span className={`status-pill ${item.status.toLowerCase()}`}><i/>{item.status}</span></td><td>{item.updatedAt ? new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric" }).format(new Date(item.updatedAt)) : "—"}</td><td><button aria-label={`Actions for ${item.title}`} onClick={(event) => { event.stopPropagation(); setMenuId(menuId === item.id ? "" : item.id); }}><MoreVertical/></button>{menuId === item.id && <div className="template-row-menu"><button onClick={() => setSelected(item)}>Edit</button><button onClick={() => act({ action: item.status === "Published" ? "draft" : "publish", ids: [item.id] })}>{item.status === "Published" ? "Unpublish" : "Publish"}</button><button onClick={() => act({ action: item.status === "Archived" ? "draft" : "archive", ids: [item.id] })}>{item.status === "Archived" ? "Restore" : "Archive"}</button></div>}</td></tr>)}</tbody></table>{!pageData.rows.length && <div className="template-empty"><Target/><h2>No matching scenarios</h2><p>{facets.total ? "Adjust your search or filters." : "Create a scenario or import an existing collection."}</p><button className="btn btn-primary" onClick={() => setCreating(true)}><Plus/> New scenario</button></div>}</div>
      <footer className="template-pagination"><span>Showing {pageData.rows.length ? (pageData.page-1)*SCENARIO_PAGE_SIZE+1 : 0}–{Math.min(pageData.page*SCENARIO_PAGE_SIZE,pageData.total)} of {pageData.total} scenarios</span><div><button aria-label="Previous page" disabled={page===1} onClick={() => setPage(Math.max(1,page-1))}><ChevronLeft/></button><span>{page} / {pages}</span><button aria-label="Next page" disabled={page===pages} onClick={() => setPage(Math.min(pages,page+1))}><ChevronRight/></button></div></footer>
    </section>
    {editorOpen && <aside className="template-editor-drawer scenario-editor-drawer" aria-label={creating ? "New scenario" : "Edit scenario"}><header><h2>{creating ? "New Scenario" : "Edit Scenario"}</h2><button aria-label="Close editor" onClick={() => { setCreating(false); setSelected(null); }}><X/></button></header><div className="scenario-editor-scroll"><AdminCoachScenarioForm key={selected?.id || "new"} demo={demo} scenario={selected || undefined} categories={categoryNames}/></div></aside>}
    {manageOpen && <div className="template-import-backdrop"><section className="category-manager" role="dialog" aria-modal="true" aria-label="Manage scenario categories"><header><div><span className="badge amber">Workspace settings</span><h2>Manage categories</h2><p>Rename, reorder, archive, or restore categories without deleting scenarios.</p></div><button aria-label="Close category manager" onClick={() => setManageOpen(false)}><X/></button></header><form onSubmit={(event) => { event.preventDefault(); void categoryAction("add", undefined, newCategory); }}><input aria-label="New category name" value={newCategory} onChange={(event) => setNewCategory(event.target.value)} placeholder="New category name"/><button className="btn btn-primary" disabled={busy}>Add category</button></form><div className="category-list">{activeCategories.map((item,index) => <article draggable key={item.id} onDragStart={() => setDragged(item.id)} onDragOver={(event) => event.preventDefault()} onDrop={() => { const source=activeCategories.find((value)=>value.id===dragged); if(source&&source.id!==item.id) void categoryAction("reorder",source,index*10-5); setDragged(""); }}><span className="category-drag">⋮⋮</span><strong>{item.name}</strong><small>{facets.categoryCounts[item.name] || 0} scenarios</small><button onClick={() => { const name=window.prompt("Rename category",item.name); if(name) void categoryAction("rename",item,name); }}>Rename</button><button onClick={() => categoryAction("archive",item)}>Archive</button></article>)}</div>{archivedCategories.length > 0 && <><h3>Archived</h3><div className="category-list archived">{archivedCategories.map((item)=><article key={item.id}><strong>{item.name}</strong><button onClick={() => categoryAction("restore",item)}>Restore</button></article>)}</div></>}</section></div>}
  </div>;
}
