"use client";

import { useActionState, useState } from "react";
import { saveAICommunicationStandards, type OrganizationSettingsActionState } from "@/app/admin/settings/actions";
import { defaultCommunicationStandards, type CommunicationStandards } from "@/lib/rag/prompt-compiler";

const initial: OrganizationSettingsActionState = { error: "", success: "" };
const select = (name: string, label: string, value: string, options: Array<[string, string]>) => <label><span className="label">{label}</span><select className="input" name={name} defaultValue={value}>{options.map(([id, text]) => <option value={id} key={id}>{text}</option>)}</select></label>;
function check(name: string, label: string, value: boolean) { return <label className="checkbox-row"><input name={name} type="checkbox" defaultChecked={value}/><span>{label}</span></label>; }

export function AICommunicationStandardsForm({ standards = defaultCommunicationStandards, canManage }: { standards?: CommunicationStandards; canManage: boolean }) {
  const [state, action, pending] = useActionState(saveAICommunicationStandards, initial);
  const [preview, setPreview] = useState(""); const [previewError, setPreviewError] = useState(""); const [testing, setTesting] = useState(false);
  async function test(form: HTMLFormElement) { setTesting(true); setPreview(""); setPreviewError(""); const values = new FormData(form); const body: Record<string, unknown> = Object.fromEntries(values); ["useShortParagraphs","useBullets","useHeadings","avoidLargeBlocks","askDiscoveryBeforeRecommendation","explainRecommendation","offerAlternative","connectBenefits"].forEach((key) => body[key] = values.has(key)); try { const response = await fetch("/api/ai/preview", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ question: String(body.previewQuestion || "I'm looking for a golf cart."), standards: body }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "The response could not be generated."); setPreview(result.answer); } catch (error) { setPreviewError(error instanceof Error ? error.message : "The response could not be generated."); } finally { setTesting(false); } }
  return <form className="form-stack" action={action} onSubmit={(event) => { if (!canManage) event.preventDefault(); }}>
    <section className="card form-stack"><div><span className="eyebrow">Company behavior</span><h2>AI Communication Standards</h2><p>These tenant-specific settings control how AI communicates. Product facts, pricing, inventory, and policies stay in the Knowledge Base.</p></div><div className="grid grid-3">{select("tone", "Communication tone", standards.tone, [["professional","Professional"],["conversational","Conversational"],["friendly","Friendly"],["direct","Direct"],["consultative","Consultative"]])}{select("responseLength", "Response length", standards.responseLength, [["concise","Concise"],["balanced","Balanced"],["detailed","Detailed"]])}{select("salesApproach", "Sales approach", standards.salesApproach, [["consultative","Consultative"],["educational","Educational"],["direct","Direct"],["relationship_focused","Relationship-focused"]])}{select("discoveryLevel", "Discovery level", standards.discoveryLevel, [["minimal","Minimal"],["moderate","Moderate"],["thorough","Thorough"]])}{select("competitorBehavior", "Competitor behavior", standards.competitorBehavior, [["do_not_discuss","Do not discuss competitors"],["when_asked","Compare only when asked"],["when_helpful","Compare when helpful"]])}{select("ctaStrength", "Call-to-action strength", standards.ctaStrength, [["soft","Soft"],["balanced","Balanced"],["strong","Strong"]])}</div></section>
    <section className="card form-stack"><h2>Formatting and recommendations</h2><div className="grid grid-2"><div className="form-stack">{check("useShortParagraphs","Use short paragraphs",standards.useShortParagraphs)}{check("useBullets","Use bullets when helpful",standards.useBullets)}{check("useHeadings","Use headings for longer answers",standards.useHeadings)}{check("avoidLargeBlocks","Avoid large blocks of text",standards.avoidLargeBlocks)}</div><div className="form-stack">{check("askDiscoveryBeforeRecommendation","Ask discovery questions before recommending",standards.askDiscoveryBeforeRecommendation)}{check("explainRecommendation","Explain why a recommendation fits",standards.explainRecommendation)}{check("offerAlternative","Offer an alternative when appropriate",standards.offerAlternative)}{check("connectBenefits","Connect features to customer benefits",standards.connectBenefits)}</div></div><label><span className="label">Advanced AI instructions</span><small className="field-help">For company-specific behavior. Do not put product specifications, inventory, pricing, or policies here—those belong in approved knowledge.</small><textarea className="input" name="advancedInstructions" rows={8} maxLength={12000} defaultValue={standards.advancedInstructions}/></label></section>
    <section className="card form-stack"><div><span className="eyebrow">Response check</span><h2>Evaluate AI behavior</h2><p>Evaluate the current, unsaved settings against the same grounding rules used by the Sales Assistant.</p></div><label><span className="label">Example prompt</span><textarea className="input" name="previewQuestion" rows={3} defaultValue="I'm looking for a golf cart." maxLength={2000}/></label><button className="btn btn-secondary" type="button" onClick={(event) => test(event.currentTarget.form!)} disabled={!canManage || testing}>{testing ? "Evaluating…" : "Evaluate AI behavior"}</button>{preview && <div className="callout"><strong>Response</strong><p style={{ whiteSpace: "pre-wrap" }}>{preview}</p></div>}{previewError && <p className="form-error">{previewError}</p>}</section>
    <section className="callout"><strong>Mandatory accuracy rules</strong><p>RunFloor always uses approved knowledge for factual claims and never invents pricing, availability, specifications, policies, financing, or warranty information. These protections cannot be disabled.</p></section>
    {!canManage && <p className="demo-note">Tenant administrator access is required to change company AI standards.</p>}{state.error && <p className="form-error">{state.error}</p>}{state.success && <p className="form-success">{state.success}</p>}<button className="btn btn-primary" type="submit" disabled={!canManage || pending}>{pending ? "Saving…" : "Save AI Communication Standards"}</button>
  </form>;
}
