"use client";
import { useMemo, useRef, useState } from "react";
import { Download, FileSpreadsheet, Upload, X } from "lucide-react";
import { useRouter } from "next/navigation";
import type { ImportedCoachScenario } from "@/lib/coach/scenario-import";

const headers = ["scenario_name","category","difficulty","duration_minutes","customer_persona","practice_objective","customer_opening_statement","round_2_prompt","round_3_prompt","skills","tags","response_options","weight_clarify","weight_listen","weight_open","weight_solve","weight_explain","weight_recommend","status"];
const sample = ["Trade-In Discovery","Discovery","Intermediate","8","An informed buyer considering a trade-in","Practice discovery and value framing","What can you give me for my current vehicle?","I already know its book value.","Give me your best number and I may move forward.","Clarify;Listen;Recommend","Trade-In;Negotiation","Tell me more about its condition.|I can guarantee the highest value.|Let's skip that and discuss payment.","20","20","15","15","15","15","draft"];
const csvCell = (value: string) => `"${value.replaceAll('"','""')}"`;

export function CoachScenarioImporter({ categories }: { categories: string[] }) {
  const router = useRouter(), fileRef = useRef<HTMLInputElement>(null);
  const [open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[items,setItems]=useState<ImportedCoachScenario[]>([]),[missing,setMissing]=useState<string[]>([]),[selected,setSelected]=useState<string[]>([]),[strategy,setStrategy]=useState("skip"),[createCategories,setCreateCategories]=useState(true),[result,setResult]=useState("");
  const valid = useMemo(()=>items.filter((item)=>selected.includes(item.clientId)&&!item.validationIssues.length),[items,selected]);
  function download(){ const blob=new Blob([[headers,sample].map((row)=>row.map(csvCell).join(",")).join("\r\n")],{type:"text/csv"}); const url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="runfloor-practice-scenarios-template.csv";a.click();URL.revokeObjectURL(url); }
  async function upload(file?:File){if(!file)return;setBusy(true);setError("");const form=new FormData();form.set("file",file);const response=await fetch("/api/admin/coach/scenario-import",{method:"POST",body:form});const data=await response.json().catch(()=>({}));setBusy(false);if(!response.ok){setError(data.error||"The file could not be processed.");return;}setItems(data.scenarios||[]);setMissing(data.missingCategories||[]);setSelected((data.scenarios||[]).map((item:ImportedCoachScenario)=>item.clientId));}
  async function commit(){setBusy(true);setError("");const response=await fetch("/api/admin/coach/scenario-import",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({scenarios:valid,duplicateStrategy:strategy,createMissingCategories:createCategories})});const data=await response.json().catch(()=>({}));setBusy(false);if(!response.ok){setError(data.error||"Import failed.");return;}setResult(`${data.imported} imported, ${data.replaced} replaced, ${data.skipped} skipped.`);router.refresh();}
  return <><button className="btn btn-secondary" type="button" onClick={()=>setOpen(true)}><Upload/> Import Scenarios</button>{open&&<div className="template-import-backdrop"><section className="template-import-modal" role="dialog" aria-modal="true" aria-label="Import practice scenarios"><header><div><span className="badge blue">Bulk import</span><h2>Import practice scenarios</h2><p>Upload up to 500 complete, three-round scenarios from CSV or Excel.</p></div><button aria-label="Close importer" onClick={()=>setOpen(false)}><X/></button></header><div className="template-import-controls"><button className="btn btn-secondary" onClick={download}><Download/> Download CSV template</button><button className="btn btn-primary" disabled={busy} onClick={()=>fileRef.current?.click()}><FileSpreadsheet/> {busy?"Reading…":"Choose CSV or Excel"}</button><input ref={fileRef} hidden type="file" accept=".csv,.xlsx" onChange={(e)=>void upload(e.target.files?.[0])}/></div>{error&&<p className="form-error">{error}</p>}{result&&<p className="form-success">{result}</p>}{items.length>0&&<><div className="template-import-metrics"><span><strong>{items.length}</strong> detected</span><span><strong>{items.filter(i=>!i.validationIssues.length).length}</strong> ready</span><span><strong>{items.filter(i=>i.duplicateId).length}</strong> duplicates</span><span><strong>{items.filter(i=>i.validationIssues.length).length}</strong> needs attention</span></div>{missing.length>0&&<div className="callout"><strong>New categories: {missing.join(", ")}</strong><label><input type="checkbox" checked={createCategories} onChange={(e)=>setCreateCategories(e.target.checked)}/> Create these categories during import</label><small>Existing categories: {categories.join(", ") || "None yet"}</small></div>}<label className="label">When a scenario name already exists<select className="input" value={strategy} onChange={(e)=>setStrategy(e.target.value)}><option value="skip">Skip duplicate</option><option value="replace">Replace existing scenario</option><option value="new">Import as a new copy</option></select></label><div className="template-import-preview">{items.map((item)=><article key={item.clientId} className={item.validationIssues.length?"has-errors":""}><input type="checkbox" aria-label={`Import ${item.title||"row"}`} checked={selected.includes(item.clientId)} onChange={(e)=>setSelected(e.target.checked?[...selected,item.clientId]:selected.filter(id=>id!==item.clientId))}/><div><strong>{item.title||"Unnamed scenario"}</strong><p>{item.category} · {item.difficulty} · 3 rounds · {item.status}</p>{item.duplicateReason&&<small>{item.duplicateReason}</small>}{item.validationIssues.map(issue=><small className="form-error" key={issue}>{issue}</small>)}</div></article>)}</div><footer><span>{valid.length} ready to import</span><button className="btn btn-primary" disabled={busy||!valid.length} onClick={()=>void commit()}>{busy?"Importing…":"Import selected"}</button></footer></>}</section></div>}</>;
}
