import Link from "next/link";
import { redirect } from "next/navigation";
import { ArrowRight, BarChart3, BookOpen, Bot, Boxes, ClipboardCheck, Clock3, GraduationCap, Megaphone, MessageSquare, Settings, Tags, TrendingUp, Users } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { BrandLogo } from "@/components/brand-logo";
import { getViewer } from "@/lib/auth/viewer";
import { getDashboardData } from "@/lib/dashboard/data";
import { getViewerIndustryTemplateKey } from "@/lib/organizations/industry";
import { HomeTools } from "@/components/home-tools";
import "./home-page.css";

export default async function Home({ searchParams }: { searchParams: Promise<{ view?: string; locationId?: string; employeeId?: string }> }) {
  const filters = await searchParams;
  if (filters.view || filters.locationId || filters.employeeId) redirect(`/dashboard/performance?${new URLSearchParams(Object.entries(filters).filter((entry): entry is [string,string] => Boolean(entry[1])))}`);
  const viewer = await getViewer();
  if (!viewer) redirect("/login");
  const [data, templateKey] = await Promise.all([getDashboardData({}), getViewerIndustryTemplateKey(viewer)]);
  const isRv = templateKey === "rv";
  const admin = ["tenant_admin", "platform_owner"].includes(viewer.role);
  const team = admin || viewer.role === "manager";
  const metrics = [[Bot,"Questions answered",data.metrics.questions,"orange","/assistant"],[MessageSquare,"Messages created",data.metrics.messages,"blue","/email"],[GraduationCap,"Training completed",`${data.metrics.training}%`,"purple","/training"],[Users,"Team confidence",data.metrics.confidence,"green","/dashboard/performance"]] as const;
  const activity = data.employees.filter((employee)=>employee.lastActivity && employee.lastActivity!=="—").slice(0,4);
  return <AppShell title="Home" industry={isRv ? "rv" : undefined}><div className={`rf-home ${isRv ? "rv-home" : ""}`}>
    {!isRv && <header className="home-welcome"><div><h1>Welcome back, {viewer.fullName.split(" ")[0]}</h1><p>Here’s what’s happening at {viewer.organizationName}.</p></div><div><span className="home-workspace"><Users size={15}/>{viewer.organizationName}</span>{viewer.demo && <span className="badge amber">Demo data</span>}</div></header>}
    <div className="home-top"><section className="home-hero"><div>{isRv ? <div className="rv-home-hero-copy"><h1>Welcome back,<br/><em>{viewer.fullName.split(" ")[0]}!</em></h1><p>Here’s what’s happening at {viewer.organizationName} today.</p><blockquote>“More Families. Greater Adventures.”</blockquote></div> : <><h2>Run Your <em>Sales Floor</em></h2><p>People. Process. Performance.</p></>}</div><div className="home-hero-bottom"><div>{[[BarChart3,"Sell smarter","/assistant"],[Settings,"Operate better","/operations"],[GraduationCap,"Train faster","/training"],[TrendingUp,"Grow stronger","/growth"]].map(([Icon,label,href])=><Link key={String(label)} href={String(href)}><Icon size={25}/><span>{String(label)}</span></Link>)}</div>{!isRv && <p>A connected workspace.<br/><strong>A better-prepared team.</strong></p>}</div></section><HomeTools admin={admin} team={team}/></div>
    <div className="home-body"><div className="home-primary"><div className="home-metrics">{metrics.map(([Icon,label,value,color,href])=><Link href={href} className="home-card home-metric" key={label}><span className={`home-icon ${color}`}><Icon size={23}/></span><div><small>{label}</small><strong>{value}</strong><span>Recorded workspace activity</span></div></Link>)}</div>
      <div className="home-insights"><section className="home-card"><div className="home-section-title"><h2><TrendingUp size={20}/> Training progress</h2><Link href="/dashboard/performance">View performance <ArrowRight size={13}/></Link></div><p className="home-caption">Completed training by team member</p>{data.employees.length ? <div className="home-chart">{data.employees.slice(0,5).map((employee)=><Link className="home-bar-row" href={`/dashboard/performance?view=employee&employeeId=${employee.id}`} key={employee.id}><div><span>{employee.name}</span><strong>{employee.training}%</strong></div><div className="home-bar"><span style={{width:`${Math.max(0,Math.min(100,employee.training))}%`}}/></div></Link>)}</div> : <div className="home-empty"><GraduationCap size={30}/><p>Complete training to start building your performance picture.</p><Link href="/training">Open training <ArrowRight size={14}/></Link></div>}</section>
      <section className="home-card"><div className="home-section-title"><h2><Clock3 size={20}/> Recent activity</h2><Link href="/dashboard/performance">View all</Link></div>{activity.length ? activity.map((employee)=><Link className="home-list-row" href={`/dashboard/performance?view=employee&employeeId=${employee.id}`} key={employee.id}><span className="home-icon blue"><Users size={18}/></span><div><strong>{employee.name}</strong><small>{employee.questions} questions · {employee.messages} messages</small></div><small>{employee.lastActivity}</small></Link>) : <div className="home-empty"><Clock3 size={28}/><p>Workspace activity will appear as your team uses RunFloor.</p><Link href="/assistant">Ask your first question <ArrowRight size={14}/></Link></div>}</section></div>
      <section className="home-card"><div className="home-section-title"><h2><Clock3 size={20}/> Jump back into your workspace</h2></div><div className="home-resume">{[[Boxes,"Products","Browse models","/products"],[ClipboardCheck,"Procedures","Open library","/operations/procedures"],[GraduationCap,"Training","Keep learning","/training"],[Tags,"Competitors","Explore models","/competitors"]].map(([Icon,label,copy,href])=><Link href={String(href)} key={String(label)}><Icon size={22}/><strong>{String(label)}</strong><span>{String(copy)} <ArrowRight size={13}/></span></Link>)}</div></section>
    </div><aside className="home-aside"><section className="home-card"><div className="home-section-title"><h2><Megaphone size={20}/> Workspace essentials</h2></div>{[[BookOpen,"Approved knowledge","Company information and guidance.","/knowledge-base"],[ClipboardCheck,"Daily operations","Checklists and assignments.","/operations/checklists"],[GraduationCap,"Build your skills","Explore available training.","/training"]].map(([Icon,label,copy,href])=><Link className="home-list-row" href={String(href)} key={String(label)}><span className="home-icon orange"><Icon size={18}/></span><div><strong>{String(label)}</strong><small>{String(copy)}</small></div><ArrowRight size={14}/></Link>)}</section>
      <section className="home-card"><div className="home-section-title"><h2><Users size={20}/>{team ? "Your team" : "Your workspace"}</h2><Link href={admin ? "/admin/users" : "/dashboard/performance"}>View all</Link></div>{data.employees.slice(0,4).map((employee)=><Link className="home-list-row" href={`/dashboard/performance?view=employee&employeeId=${employee.id}`} key={employee.id}><span className="home-initials">{employee.name.split(" ").map((part)=>part[0]).slice(0,2).join("")}</span><div><strong>{employee.name}</strong><small>{employee.role.replaceAll("_"," ")} · {employee.location}</small></div></Link>)}{!data.employees.length && <p className="home-caption">Team information is not available yet.</p>}</section>
    </aside></div>
    <section className="home-card home-resources"><div className="home-section-title"><h2><BookOpen size={20}/> Helpful resources</h2></div><div>{[[BookOpen,"Knowledge base","Company articles and guides","/knowledge-base"],[GraduationCap,"Sales coaching","Practice conversations","/coach"],[ClipboardCheck,"Operations library","Step-by-step procedures","/operations/procedures"]].map(([Icon,label,copy,href])=><Link href={String(href)} key={String(label)}><Icon size={23}/><div><strong>{String(label)}</strong><small>{String(copy)}</small></div><ArrowRight size={17}/></Link>)}</div></section>
    <footer className="home-footer"><BrandLogo compact/><span>People. Process. Performance.</span></footer>
  </div></AppShell>;
}
