"use client";

import { AlertTriangle, CheckCircle2, Clock3, Download, Gauge, LoaderCircle, MapPin, Plus, RotateCcw, Search, ShieldCheck, Target, UserRound, UsersRound } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { saveOperationsAlert, setOperationsAlertStatus } from "@/app/operations/actions";
import type { OperationsAlertRecord } from "@/lib/operations/data";
import type { OperationsPersistence } from "@/lib/operations/repository";
import { readOperationsAlerts, writeOperationsAlerts } from "@/lib/operations/storage";

const statuses: Array<"All statuses" | OperationsAlertRecord["status"]> = ["All statuses", "Open", "Acknowledged", "Resolved"];

export function OperationsAlertManager({ initialAlerts = [], persistence = "demo", initialError = "" }: { initialAlerts?: OperationsAlertRecord[]; persistence?: OperationsPersistence; initialError?: string }) {
  const [alerts, setAlerts] = useState<OperationsAlertRecord[] | null>(persistence === "supabase" ? initialAlerts : null);
  const [error, setError] = useState(initialError);
  const [statusFilter, setStatusFilter] = useState<(typeof statuses)[number]>("All statuses");
  const [locationFilter, setLocationFilter] = useState("All locations");
  const [severityFilter, setSeverityFilter] = useState("All priorities");
  const [query, setQuery] = useState("");
  const [sort, setSort] = useState("Newest first");
  const [title, setTitle] = useState("");
  const [detail, setDetail] = useState("");
  const [severity, setSeverity] = useState<OperationsAlertRecord["severity"]>("Medium");
  const [location, setLocation] = useState("Charleston");
  const [owner, setOwner] = useState("");
  const [dueDate, setDueDate] = useState("");

  useEffect(() => { if (persistence === "supabase") return; const timer = window.setTimeout(() => { try { setAlerts(readOperationsAlerts()); } catch { setError("Saved alerts could not be loaded from this browser."); setAlerts([]); } }, 0); return () => window.clearTimeout(timer); }, [persistence]);
  const counts = useMemo(() => ({ open: alerts?.filter((item) => item.status === "Open").length ?? 0, acknowledged: alerts?.filter((item) => item.status === "Acknowledged").length ?? 0, resolved: alerts?.filter((item) => item.status === "Resolved").length ?? 0 }), [alerts]);
  const filtered = useMemo(() => [...(alerts ?? [])].filter((alert) => statusFilter === "All statuses" || alert.status === statusFilter).filter((alert) => locationFilter === "All locations" || alert.location === locationFilter).filter((alert) => severityFilter === "All priorities" || alert.severity === severityFilter).filter((alert) => `${alert.title} ${alert.detail} ${alert.owner} ${alert.location}`.toLowerCase().includes(query.toLowerCase())).sort((a, b) => sort === "Oldest first" ? Date.parse(a.createdAt) - Date.parse(b.createdAt) : Date.parse(b.createdAt) - Date.parse(a.createdAt)), [alerts, locationFilter, query, severityFilter, sort, statusFilter]);
  const averageResolution = useMemo(() => { const spans = (alerts ?? []).flatMap((alert) => { const resolved = [...alert.history].reverse().find((item) => item.status === "Resolved"); return resolved ? [Math.max(0, Date.parse(resolved.changedAt) - Date.parse(alert.createdAt))] : []; }); return spans.length ? `${(spans.reduce((sum, span) => sum + span, 0) / spans.length / 86400000).toFixed(1)} days` : "—"; }, [alerts]);

  function save(next: OperationsAlertRecord[]) { try { writeOperationsAlerts(next); setAlerts(next); setError(""); } catch { setError("Alert changes could not be saved in this browser."); } }
  async function createAlert(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); if (title.trim().length < 2 || detail.trim().length < 10 || owner.trim().length < 2 || !dueDate) { setError("Add a title, useful description, owner, and due date."); return; } const input = { title: title.trim(), detail: detail.trim(), severity, location, owner: owner.trim(), dueDate }; if (persistence === "supabase") { const result = await saveOperationsAlert(input); if (result.error || !result.record) { setError(result.error ?? "Alert could not be created."); return; } setAlerts([result.record, ...(alerts ?? [])]); setError(""); } else { const now = new Date().toISOString(); const next: OperationsAlertRecord = { ...input, id: crypto.randomUUID(), status: "Open", createdAt: now, history: [{ id: crypto.randomUUID(), status: "Open", note: "Alert created.", changedAt: now }] }; save([next, ...(alerts ?? [])]); } setTitle(""); setDetail(""); setSeverity("Medium"); setOwner(""); setDueDate(""); }
  async function changeStatus(alertId: string, status: OperationsAlertRecord["status"]) { if (!alerts) return; const now = new Date().toISOString(); const note = status === "Acknowledged" ? "Owner acknowledged the alert." : status === "Resolved" ? "Alert marked resolved." : "Alert reopened for follow-up."; if (persistence === "demo") save(alerts.map((alert) => alert.id === alertId ? { ...alert, status, history: [...alert.history, { id: crypto.randomUUID(), status, note, changedAt: now }] } : alert)); else { const result = await setOperationsAlertStatus(alertId, status, note); if (result.error || !result.history) { setError(result.error ?? "Alert could not be updated."); return; } setAlerts(alerts.map((alert) => alert.id === alertId ? { ...alert, status, history: [...alert.history, result.history] } : alert)); setError(""); } }
  function exportAlerts() { const rows = [["Alert", "Location", "Priority", "Status", "Owner", "Created"], ...filtered.map((alert) => [alert.title, alert.location, alert.severity, alert.status, alert.owner, alert.createdAt])]; const csv = rows.map((row) => row.map((cell) => `"${String(cell).replaceAll('"', '""')}"`).join(",")).join("\n"); const url = URL.createObjectURL(new Blob([csv], { type: "text/csv" })); const link = document.createElement("a"); link.href = url; link.download = "operational-alerts.csv"; link.click(); URL.revokeObjectURL(url); }
  if (alerts === null && !error) return <div className="card operations-loading"><LoaderCircle className="spin" size={22}/><div><h2>Loading operational alerts</h2><p>Checking this browser for saved exceptions.</p></div></div>;

  const metrics = [{ label: "Open Alerts", value: counts.open, note: "Requires ownership", icon: AlertTriangle, tone: "red" }, { label: "Acknowledged", value: counts.acknowledged, note: "Follow-up underway", icon: Clock3, tone: "amber" }, { label: "Resolved", value: counts.resolved, note: "Closed with history", icon: CheckCircle2, tone: "green" }, { label: "Avg. Resolution Time", value: averageResolution, note: "Across resolved alerts", icon: Gauge, tone: "slate" }];
  return <div className="alert-command">
    <section className="alert-hero"><div><span>Manage the exceptions</span><h1>Surface problems, assign ownership,<br/><em>and close the loop.</em></h1><p>Track operational issues from the first alert through acknowledgment and verified resolution.</p></div><a className="alert-new" href="#alert-builder"><Plus/> New Alert</a></section>
    <section className="alert-metrics" aria-label="Alert summary">{metrics.map(({ label, value, note, icon: Icon, tone }) => <article key={label}><span className={`alert-metric-icon ${tone}`}><Icon/></span><div><b>{label}</b><strong>{value}</strong><small>{note}</small></div></article>)}</section>
    <section className="alert-controls"><div className="alert-tabs" aria-label="Filter alerts by status">{statuses.map((status) => <button className={statusFilter === status ? "active" : ""} key={status} onClick={() => setStatusFilter(status)} type="button">{status === "All statuses" ? "All Alerts" : status} ({status === "All statuses" ? alerts?.length ?? 0 : status === "Open" ? counts.open : status === "Acknowledged" ? counts.acknowledged : counts.resolved})</button>)}</div><div className="alert-filters"><label><Search/><span className="sr-only">Search alerts</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search alerts..."/></label><select aria-label="Filter by location" value={locationFilter} onChange={(event) => setLocationFilter(event.target.value)}><option>All locations</option><option>Charleston</option><option>Summerville</option></select><select aria-label="Filter by priority" value={severityFilter} onChange={(event) => setSeverityFilter(event.target.value)}><option>All priorities</option><option>Low</option><option>Medium</option><option>High</option><option>Critical</option></select><select aria-label="Sort alerts" value={sort} onChange={(event) => setSort(event.target.value)}><option>Newest first</option><option>Oldest first</option></select></div></section>
    {error && <p className="form-error alert-error"><AlertTriangle size={15}/>{error}</p>}
    <div className="alert-workspace"><aside className="alert-panel alert-builder" id="alert-builder"><header><span><Plus/></span><div><h2>Create an alert</h2><p>Capture an operational exception and assign clear responsibility.</p></div></header><form onSubmit={createAlert}><label className="wide">Alert title *<input required value={title} onChange={(event) => setTitle(event.target.value)} placeholder="e.g. Service bay equipment issue"/></label><label className="wide">What happened? *<textarea required rows={4} value={detail} onChange={(event) => setDetail(event.target.value)} placeholder="Describe the exception in detail..."/></label><label>Location *<select value={location} onChange={(event) => setLocation(event.target.value)}><option>Charleston</option><option>Summerville</option><option>All locations</option></select></label><label>Priority *<select value={severity} onChange={(event) => setSeverity(event.target.value as OperationsAlertRecord["severity"])}><option>Low</option><option>Medium</option><option>High</option><option>Critical</option></select></label><label>Assign to *<input required value={owner} onChange={(event) => setOwner(event.target.value)} placeholder="Person or team"/></label><label>Due date *<input required type="date" value={dueDate} onChange={(event) => setDueDate(event.target.value)}/></label><button className="alert-submit wide" type="submit">Create alert</button></form></aside>
      <section className="alert-panel alert-queue"><header><div><h2>Alert queue</h2><p>View, track, and manage all operational alerts.</p></div><button type="button" onClick={exportAlerts}><Download/> Export</button></header><div className="alert-table-wrap">{filtered.length ? <table><thead><tr><th>Alert</th><th>Location</th><th>Priority</th><th>Status</th><th>Assigned to</th><th>Created</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{filtered.map((alert) => <tr key={alert.id}><td><strong>{alert.title}</strong><small>{alert.detail}</small></td><td><span><MapPin/>{alert.location}</span></td><td><i className={`priority-${alert.severity.toLowerCase()}`}/>{alert.severity}</td><td><b className={`status-${alert.status.toLowerCase()}`}>{alert.status}</b></td><td><span><UserRound/>{alert.owner}</span></td><td>{new Date(alert.createdAt).toLocaleDateString()}</td><td>{alert.status === "Open" ? <button title="Acknowledge alert" onClick={() => changeStatus(alert.id, "Acknowledged")}><Clock3/></button> : alert.status === "Acknowledged" ? <button title="Resolve alert" onClick={() => changeStatus(alert.id, "Resolved")}><CheckCircle2/></button> : <button title="Reopen alert" onClick={() => changeStatus(alert.id, "Open")}><RotateCcw/></button>}</td></tr>)}</tbody></table> : <div className="alert-empty"><CheckCircle2/><h3>No alerts in this view</h3><p>Change a filter or create a new alert.</p></div>}</div><footer>Showing {filtered.length} of {alerts?.length ?? 0} alerts</footer></section>
    </div>
    <section className="alert-benefits"><div><Target/><span><strong>Catch Issues Early</strong><small>Identify problems before they impact the customer experience.</small></span></div><div><UsersRound/><span><strong>Drive Accountability</strong><small>Assign owners and track progress in real time.</small></span></div><div><Gauge/><span><strong>Improve Efficiency</strong><small>Turn exceptions into better processes.</small></span></div><div><ShieldCheck/><span><strong>Stronger Dealerships</strong><small>Smoother operations. Happier customers.</small></span></div></section>
  </div>;
}
