"use client";
import Link from "next/link";
import { AlertTriangle, BarChart3, CheckCircle2, ChevronRight, CircleDot, Clock3, Download, Lightbulb, LoaderCircle, MapPin, MoreHorizontal, Plus, Search, Send, ShieldAlert } from "lucide-react";
import { useEffect, useState } from "react";
import { saveOperationsIncident, setOperationsIncidentStatus } from "@/app/operations/actions";
import type { OperationsIncidentRecord } from "@/lib/operations/data";
import type { OperationsPersistence } from "@/lib/operations/repository";
import { formatOperationsDate, readOperationsIncidents, writeOperationsIncidents } from "@/lib/operations/storage";
const statuses = ["All statuses", "Reported", "Investigating", "Corrective Action", "Verified Closed"] as const;
type IncidentIndustry = "golf-cart" | "rv" | "generic";
export function OperationsIncidentManager({ initialIncidents = [], persistence = "demo", initialError = "", tailored = false, industry = "generic" }: { initialIncidents?: OperationsIncidentRecord[]; persistence?: OperationsPersistence; initialError?: string; tailored?: boolean; industry?: IncidentIndustry }) {
  const [items,setItems]=useState<OperationsIncidentRecord[]|null>(persistence === "supabase" ? initialIncidents : null); const [error,setError]=useState(initialError); const [filter,setFilter]=useState<(typeof statuses)[number]>("All statuses"); const [query,setQuery]=useState(""); const [locationFilter,setLocationFilter]=useState("All locations");
  const [sort,setSort]=useState<"newest"|"oldest"|"severity">("newest"); const [title,setTitle]=useState(""); const [category,setCategory]=useState<OperationsIncidentRecord["category"]>("Equipment"); const [severity,setSeverity]=useState<OperationsIncidentRecord["severity"]>("High"); const [location,setLocation]=useState("Charleston"); const [occurredAt,setOccurredAt]=useState(""); const [reportedBy,setReportedBy]=useState(""); const [description,setDescription]=useState(""); const [immediateAction,setImmediateAction]=useState(""); const [rootCause,setRootCause]=useState(""); const [correctiveAction,setCorrectiveAction]=useState(""); const [owner,setOwner]=useState(""); const [dueDate,setDueDate]=useState("");
  useEffect(()=>{if(persistence === "supabase")return;const timer=setTimeout(()=>{try{setItems(readOperationsIncidents())}catch{setError("Incident reports could not be loaded from this browser.");setItems([])}},0);return()=>clearTimeout(timer)},[persistence]);
  function save(next:OperationsIncidentRecord[]){try{writeOperationsIncidents(next);setItems(next);setError("")}catch{setError("Incident changes could not be saved in this browser.")}}
  async function create(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!title.trim()||!occurredAt||!reportedBy.trim()||!description.trim()||!immediateAction.trim()||!owner.trim()||!dueDate){setError("Complete the incident, containment, ownership, and due-date fields.");return}const input={title:title.trim(),category,severity,location,occurredAt,reportedBy:reportedBy.trim(),description:description.trim(),immediateAction:immediateAction.trim(),rootCause:rootCause.trim()||"Under investigation.",correctiveAction:correctiveAction.trim()||"To be determined during investigation.",owner:owner.trim(),dueDate};if(persistence==="supabase"){const result=await saveOperationsIncident(input);if(result.error||!result.record){setError(result.error??"Incident could not be created.");return}setItems([result.record,...(items??[])]);setError("")}else{const now=new Date().toISOString();save([{...input,id:crypto.randomUUID(),status:"Reported",createdAt:now,updatedAt:now},...(items??[])])}setTitle("");setOccurredAt("");setReportedBy("");setDescription("");setImmediateAction("");setRootCause("");setCorrectiveAction("");setOwner("");setDueDate("")}
  async function status(id:string,status:OperationsIncidentRecord["status"]){if(!items)return;if(persistence==="demo")save(items.map(x=>x.id===id?{...x,status,updatedAt:new Date().toISOString()}:x));else{const result=await setOperationsIncidentStatus(id,status);if(result.error){setError(result.error);return}setItems(items.map(x=>x.id===id?{...x,status,updatedAt:result.updatedAt??x.updatedAt}:x));setError("")}}
  function resetForm(){setTitle("");setCategory("Equipment");setSeverity("High");setLocation("Charleston");setOccurredAt("");setReportedBy("");setDescription("");setImmediateAction("");setRootCause("");setCorrectiveAction("");setOwner("");setDueDate("");setError("")}
  function exportCsv(){const rows=["Title,Category,Location,Severity,Occurred,Status,Owner",...(items??[]).map(x=>[x.title,x.category,x.location,x.severity,x.occurredAt,x.status,x.owner].map(value=>`"${String(value).replaceAll('"','""')}"`).join(","))];const url=URL.createObjectURL(new Blob([rows.join("\n")],{type:"text/csv;charset=utf-8"}));const link=document.createElement("a");link.href=url;link.download="incident-register.csv";link.click();URL.revokeObjectURL(url)}
  if(items===null&&!error)return <div className="card operations-loading"><LoaderCircle className="spin" size={22}/><div><h2>Loading incident reports</h2><p>Checking this browser for saved records.</p></div></div>;
  const locations=[...new Set((items??[]).map(x=>x.location))]; const severityRank={Critical:4,High:3,Medium:2,Low:1}; const filtered=(items??[]).filter(x=>(filter==="All statuses"||x.status===filter)&&(locationFilter==="All locations"||x.location===locationFilter)&&(!query.trim()||`${x.title} ${x.description} ${x.category} ${x.owner}`.toLowerCase().includes(query.trim().toLowerCase()))).sort((a,b)=>sort==="severity"?severityRank[b.severity]-severityRank[a.severity]:sort==="oldest"?Date.parse(a.createdAt)-Date.parse(b.createdAt):Date.parse(b.createdAt)-Date.parse(a.createdAt)); const active=(items??[]).filter(x=>x.status!=="Verified Closed").length; const high=(items??[]).filter(x=>x.status!=="Verified Closed"&&(x.severity==="High"||x.severity==="Critical")).length; const closed=(items??[]).filter(x=>x.status==="Verified Closed"); const averageDays=closed.length?Math.max(.1,closed.reduce((sum,x)=>sum+Math.max(0,Date.parse(x.updatedAt)-Date.parse(x.createdAt))/86400000,0)/closed.length).toFixed(1):"—";
  return <div className={`operations-incident-stack${tailored?" operations-incident-tailored":""}`} data-industry={industry}>
    <section className={`grid ${tailored?"grid-4 operations-incident-overview":"grid-3"}`} aria-label="Incident overview">
      <div className="card incident-metric incident-metric-active"><span className="metric-icon"><ShieldAlert/></span><div><span>Active incidents</span><strong>{active}</strong><small>Awaiting resolution</small></div><b>+{high || 0}<ChevronRight/></b></div>
      <div className="card incident-metric incident-metric-high"><span className="metric-icon"><AlertTriangle/></span><div><span>High priority</span><strong>{high}</strong><small>Requires immediate attention</small></div><b>Review<ChevronRight/></b></div>
      <div className="card incident-metric incident-metric-closed"><span className="metric-icon"><CheckCircle2/></span><div><span>Verified closed</span><strong>{closed.length}</strong><small>Corrective action completed</small></div><b>Resolved<ChevronRight/></b></div>
      {tailored&&<div className="card incident-metric incident-metric-time"><span className="metric-icon"><Clock3/></span><div><span>Avg. resolution time</span><strong>{averageDays}{averageDays!=="—"&&<small> days</small>}</strong><small>Across closed incidents</small></div><b>Trend<ChevronRight/></b></div>}
    </section>
    {error&&<p className="form-error operations-schedule-message"><AlertTriangle size={15}/>{error}</p>}
    <div className="operations-incident-layout">
      <aside id="report-incident" className="card operations-incident-form"><header><span className="metric-icon"><Plus/></span><div><h2>{tailored?"Report a New Incident":"Report an incident"}</h2><p>Help us keep our dealership safe, efficient, and customer-focused.</p></div></header><form className="form-stack" onSubmit={create}>
        <label><span className="label">Incident title <i>*</i></span><input className="input" required value={title} onChange={e=>setTitle(e.target.value)} placeholder="e.g. Service bay equipment issue"/></label>
        <div className="grid grid-2"><label><span className="label">Category <i>*</i></span><select className="input" value={category} onChange={e=>setCategory(e.target.value as OperationsIncidentRecord["category"])}><option>Safety</option><option>Customer</option><option>Equipment</option><option>Process</option><option>Other</option></select></label><label><span className="label">Severity <i>*</i></span><select className="input" value={severity} onChange={e=>setSeverity(e.target.value as OperationsIncidentRecord["severity"])}><option>Low</option><option>Medium</option><option>High</option><option>Critical</option></select></label></div>
        <div className="grid grid-2"><label><span className="label">Location <i>*</i></span><select className="input" value={location} onChange={e=>setLocation(e.target.value)}><option>Charleston</option><option>Summerville</option><option>All locations</option></select></label><label><span className="label">Occurred on <i>*</i></span><input className="input" required type="datetime-local" value={occurredAt} onChange={e=>setOccurredAt(e.target.value)}/></label></div>
        <label><span className="label">Description <i>*</i></span><textarea className="input" required rows={3} value={description} onChange={e=>setDescription(e.target.value)} placeholder="Describe what happened, the impact, and any immediate action taken..."/></label>
        <details className="incident-resolution-fields"><summary>Assignment &amp; resolution details <ChevronRight/></summary><div><label><span className="label">Reported by <i>*</i></span><input className="input" aria-required="true" value={reportedBy} onChange={e=>setReportedBy(e.target.value)}/></label><label><span className="label">Immediate containment <i>*</i></span><textarea className="input" aria-required="true" rows={2} value={immediateAction} onChange={e=>setImmediateAction(e.target.value)} placeholder="What was done right away to reduce risk?"/></label><label><span className="label">Root cause</span><textarea className="input" rows={2} value={rootCause} onChange={e=>setRootCause(e.target.value)}/></label><label><span className="label">Corrective action</span><textarea className="input" rows={2} value={correctiveAction} onChange={e=>setCorrectiveAction(e.target.value)}/></label><div className="grid grid-2"><label><span className="label">Owner <i>*</i></span><input className="input" aria-required="true" value={owner} onChange={e=>setOwner(e.target.value)} placeholder="Person or team"/></label><label><span className="label">Due date <i>*</i></span><input className="input" aria-required="true" type="date" value={dueDate} onChange={e=>setDueDate(e.target.value)}/></label></div></div></details>
        <div className="incident-form-actions"><button className="btn btn-ghost" type="button" onClick={resetForm}>Cancel</button><button className="btn btn-primary"><Send/> Submit Incident</button></div>
      </form></aside>
      <section className="operations-incident-register"><header className="incident-register-heading"><div><h2>Incident Register</h2><p>Track incidents from report to resolution.</p></div><div><button className="btn btn-ghost" type="button" onClick={exportCsv}><Download/> Export</button><Link className="btn btn-primary" href="/operations/performance">View analytics <ChevronRight/></Link></div></header>
        <div className="operations-incident-toolbar"><label className="operations-incident-search"><span className="sr-only">Search incidents</span><Search/><input className="input" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search incidents..."/></label><label><span className="sr-only">Location</span><select className="input" value={locationFilter} onChange={e=>setLocationFilter(e.target.value)}><option>All locations</option>{locations.map(x=><option key={x}>{x}</option>)}</select></label><label><span className="sr-only">Status</span><select className="input" value={filter} onChange={e=>setFilter(e.target.value as (typeof statuses)[number])}>{statuses.map(x=><option key={x}>{x}</option>)}</select></label><label><span className="sr-only">Sort order</span><select className="input" value={sort} onChange={e=>setSort(e.target.value as typeof sort)}><option value="newest">Newest first</option><option value="oldest">Oldest first</option><option value="severity">Highest severity</option></select></label></div>
        {filtered.length?<div className="incident-table-wrap"><table className="incident-table"><thead><tr><th>Title</th><th>Category</th><th>Location</th><th>Severity</th><th>Date &amp; time</th><th>Status</th><th>Assigned to</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{filtered.map(x=><tr key={x.id}><td><span className="incident-row-icon"><CircleDot/></span><strong>{x.title}</strong><small>{x.description}</small></td><td>{x.category}</td><td><MapPin/>{x.location}</td><td><span className={`severity-label severity-${x.severity.toLowerCase()}`}><AlertTriangle/>{x.severity}</span></td><td>{formatOperationsDate(x.occurredAt)}<small>{new Date(x.occurredAt).toLocaleTimeString([],{hour:"numeric",minute:"2-digit"})}</small></td><td><span className={`incident-status incident-status-${x.status.toLowerCase().replaceAll(" ","-")}`}><CheckCircle2/>{x.status}</span></td><td><span className="incident-owner"><b>{x.owner.split(/\s+/).map(word=>word[0]).join("").slice(0,2)}</b>{x.owner}</span></td><td><details className="incident-row-actions"><summary aria-label={`Actions for ${x.title}`}><MoreHorizontal/></summary><div><p>{x.immediateAction}</p>{x.status==="Reported"&&<button onClick={()=>status(x.id,"Investigating")}>Start investigation</button>}{x.status==="Investigating"&&<button onClick={()=>status(x.id,"Corrective Action")}>Begin corrective action</button>}{x.status==="Corrective Action"&&<button onClick={()=>status(x.id,"Verified Closed")}>Verify and close</button>}</div></details></td></tr>)}</tbody></table><footer>Showing {filtered.length} of {items?.length??0} incidents</footer></div>:<div className="card output empty"><div><ShieldAlert/><h2>No incidents in this view</h2><p>Adjust your filters or report a new incident to get started.</p></div></div>}
        <div className="incident-insights"><aside><Lightbulb/><div><strong>Pro Tip</strong><p>Add photos and clear details to speed up resolution time and prevent repeat issues.</p></div></aside><aside><BarChart3/><div><strong>Incident Trends</strong><p>See common issues, resolution times, and location comparisons.</p><Link href="/operations/performance">View analytics <ChevronRight/></Link></div></aside></div>
      </section>
    </div>
  </div>;
}
