"use client";

import Link from "next/link";
import { AlertTriangle, BarChart3, BellRing, CheckCircle2, ChevronRight, ClipboardCheck, Clock3, Download, Lightbulb, ListChecks, LoaderCircle, MapPin, MapPinned, Plus, Target, TrendingUp } from "lucide-react";
import { useEffect, useState } from "react";
import type { OperationsAlertRecord, OperationsChecklistRecord } from "@/lib/operations/data";
import type { OperationsPersistence } from "@/lib/operations/repository";
import { calculateOperationsPerformance } from "@/lib/operations/performance";
import { formatOperationsDate, readOperationsAlerts, readOperationsChecklists } from "@/lib/operations/storage";

export function OperationsPerformanceDashboard({ initialChecklists = [], initialAlerts = [], persistence = "demo", initialError = "", tailored = false, industry = "generic" }: { initialChecklists?: OperationsChecklistRecord[]; initialAlerts?: OperationsAlertRecord[]; persistence?: OperationsPersistence; initialError?: string; tailored?: boolean; industry?: "golf-cart"|"rv"|"generic" }) {
  const [checklists, setChecklists] = useState<OperationsChecklistRecord[] | null>(persistence === "supabase" ? initialChecklists : null);
  const [alerts, setAlerts] = useState<OperationsAlertRecord[] | null>(persistence === "supabase" ? initialAlerts : null);
  const [location, setLocation] = useState("All locations");
  const [source, setSource] = useState<"All work types"|"Checklists"|"Alerts">("All work types");
  const [error, setError] = useState(initialError);

  useEffect(() => { if (persistence === "supabase") return; const timer = window.setTimeout(() => { try { setChecklists(readOperationsChecklists()); setAlerts(readOperationsAlerts()); } catch { setError("Operations performance could not be loaded from this browser."); setChecklists([]); setAlerts([]); } }, 0); return () => window.clearTimeout(timer); }, [persistence]);

  if (checklists === null || alerts === null) return <div className="card operations-loading"><LoaderCircle className="spin" size={22}/><div><h2>Loading operations performance</h2><p>Reviewing saved checklists and alert history.</p></div></div>;
  if (error) return <div className="card operations-performance-state"><AlertTriangle size={24}/><div><h2>Performance unavailable</h2><p>{error}</p></div></div>;
  if (!tailored && !checklists.length && !alerts.length) return <div className="card output empty"><div><ClipboardCheck size={28}/><h2>No operations data yet</h2><p>Create a checklist or alert to begin measuring execution.</p></div></div>;

  const locationChecklists = location === "All locations" ? checklists : checklists.filter((item) => item.location === location || item.location === "All locations");
  const locationAlerts = location === "All locations" ? alerts : alerts.filter((item) => item.location === location || item.location === "All locations");
  const visibleChecklists = source === "Alerts" ? [] : locationChecklists;
  const visibleAlerts = source === "Checklists" ? [] : locationAlerts;
  const today = new Date().toLocaleDateString("en-CA");
  const performance = calculateOperationsPerformance(visibleChecklists, visibleAlerts, today);
  const locations = [...new Set([...checklists.map((item) => item.location), ...alerts.map((item) => item.location)])].filter((item) => item !== "All locations");
  const attentionItems = [
    ...visibleChecklists.filter((item) => item.dueDate < today && item.steps.some((step) => !step.complete)).map((item) => ({ id: `checklist-${item.id}`, type: "Checklist", title: item.title, location: item.location, dueDate: item.dueDate, href: "/operations/checklists" })),
    ...visibleAlerts.filter((item) => item.status !== "Resolved" && (item.dueDate < today || item.severity === "Critical" || item.severity === "High")).map((item) => ({ id: `alert-${item.id}`, type: "Alert", title: item.title, location: item.location, dueDate: item.dueDate, href: "/operations/alerts" })),
  ];
  const incompleteSteps=Math.max(0,performance.totalSteps-performance.completedSteps);
  const donutStyle={background:`conic-gradient(#08b975 0 ${performance.completion}%,#3184ef ${performance.completion}% ${Math.min(100,performance.completion+(incompleteSteps?Math.max(4,Math.round(incompleteSteps/Math.max(1,performance.totalSteps)*100)):0))}%,#e6ebef 0)`};
  const workTypes=visibleChecklists.map((item)=>({title:item.title,total:item.steps.length,completed:item.steps.filter((step)=>step.complete).length})).sort((a,b)=>b.total-a.total).slice(0,5);
  function exportCsv(){const rows=["Location,Completion,Completed Steps,Total Steps,Active Alerts,Overdue",...performance.byLocation.map((item)=>[item.location,item.completion,item.completedSteps,item.totalSteps,item.activeAlerts,item.overdueItems].map((value)=>`"${value}"`).join(","))];const url=URL.createObjectURL(new Blob([rows.join("\n")],{type:"text/csv;charset=utf-8"}));const anchor=document.createElement("a");anchor.href=url;anchor.download="operations-performance.csv";anchor.click();URL.revokeObjectURL(url)}

  if (tailored) return <div className="operations-performance-stack operations-performance-tailored" data-industry={industry}>
    <section className="grid grid-4 operations-performance-metrics" aria-label="Operations performance summary">
      <div className="card performance-metric performance-metric-green"><span className="metric-icon"><Target/></span><div><span>On-Time Completion</span><strong>{performance.completion}%</strong><small>{performance.completedSteps} of {performance.totalSteps} tasks</small></div><ChevronRight/></div>
      <div className="card performance-metric performance-metric-red"><span className="metric-icon"><AlertTriangle/></span><div><span>Overdue Work</span><strong>{performance.overdueItems}</strong><small>Requires attention</small></div><ChevronRight/></div>
      <div className="card performance-metric performance-metric-blue"><span className="metric-icon"><ListChecks/></span><div><span>Total Tasks</span><strong>{performance.totalSteps.toLocaleString()}</strong><small>Across selected locations</small></div><ChevronRight/></div>
      <div className="card performance-metric performance-metric-purple"><span className="metric-icon"><MapPinned/></span><div><span>Active Locations</span><strong>{locations.length}</strong><small>Reporting operations</small></div><ChevronRight/></div>
    </section>
    <div className="operations-performance-toolbar"><label><span>View location</span><select className="input" value={location} onChange={(event)=>setLocation(event.target.value)}><option>All locations</option>{locations.map((item)=><option key={item}>{item}</option>)}</select></label><label><span>Work source</span><select className="input" value={source} onChange={(event)=>setSource(event.target.value as typeof source)}><option>All work types</option><option>Checklists</option><option>Alerts</option></select></label><span className="performance-snapshot"><Clock3/>Current workspace snapshot</span><div><button className="btn btn-secondary" onClick={exportCsv}><Download/> Export</button><Link className="btn btn-primary" href="/operations/checklists"><Plus/> Create task</Link><Link className="btn btn-primary" href="/operations/alerts">Create alert</Link></div></div>
    <section className="operations-performance-charts"><div className="card operations-performance-trend"><header><div><BarChart3/><span><h2>Task Completion Trend</h2><p>Trend data appears as task history accumulates.</p></span></div><Link href="/operations/checklists">View details <ChevronRight/></Link></header><div className="operations-chart-empty"><TrendingUp/><strong>Historical trend is building</strong><span>RunFloor will chart completion over time as this workspace records activity.</span></div></div><div className="card operations-status-breakdown"><header><div><ListChecks/><span><h2>Task Status Breakdown</h2><p>Current selected workload.</p></span></div></header><div><span className="operations-donut" style={donutStyle}><i><b>{performance.totalSteps}</b><small>Total Tasks</small></i></span><ul><li><i className="green"/>Completed <b>{performance.completedSteps}</b><em>{performance.completion}%</em></li><li><i className="blue"/>Remaining <b>{incompleteSteps}</b><em>{100-performance.completion}%</em></li><li><i className="red"/>Overdue <b>{performance.overdueItems}</b><em>Attention</em></li><li><i/>Active Alerts <b>{performance.activeAlerts}</b><em>Open</em></li></ul></div></div></section>
    <section className="operations-performance-detail-grid">
      <div className="card performance-detail-card"><header><div><MapPin/><h2>Performance by Location</h2></div></header>{performance.byLocation.length?<div className="performance-location-table"><div><b>Location</b><b>Completion rate</b><b>Total tasks</b><b>Overdue</b></div>{performance.byLocation.map((item)=><div key={item.location}><strong>{item.location}</strong><span><b>{item.completion}%</b><i><em style={{width:`${item.completion}%`}}/></i></span><span>{item.totalSteps}</span><span className={item.overdueItems?"attention":""}>{item.overdueItems}</span></div>)}</div>:<div className="performance-empty-result"><MapPin/><strong>No location data yet</strong><p>Add location-specific tasks or alerts to compare performance.</p></div>}</div>
      <div className="card performance-detail-card"><header><div><ListChecks/><h2>Top Work Types</h2></div></header>{workTypes.length?<div className="performance-work-types">{workTypes.map((item)=><div key={item.title}><strong>{item.title}</strong><span>{item.total}</span><b>{item.total?Math.round(item.completed/item.total*100):0}%</b><i><em style={{width:`${item.total?Math.round(item.completed/item.total*100):0}%`}}/></i></div>)}</div>:<div className="performance-empty-result"><ClipboardCheck/><strong>No checklist work yet</strong><p>Create a checklist to see top work types.</p></div>}</div>
      <div className="card performance-insights"><header><div><Lightbulb/><h2>Insights &amp; Opportunities</h2></div></header><ul><li className="positive"><TrendingUp/><span><strong>{performance.completion}% task completion</strong><small>{performance.completedSteps} tasks completed in this view.</small></span></li><li className={performance.overdueItems?"negative":"positive"}><AlertTriangle/><span><strong>{performance.overdueItems} overdue item{performance.overdueItems===1?"":"s"}</strong><small>{performance.overdueItems?"Review priority work and active alerts.":"No overdue work in this view."}</small></span></li><li><BellRing/><span><strong>{performance.activeAlerts} active alert{performance.activeAlerts===1?"":"s"}</strong><small>{performance.resolvedAlerts} resolved in recorded history.</small></span></li></ul><Link className="btn btn-ghost" href="/operations/alerts">View detailed operations <ChevronRight/></Link></div>
    </section>
  </div>;

  return <div className="operations-performance-stack">
    <div className="operations-performance-toolbar"><div><h2>Execution overview</h2><p>Calculated from saved checklist steps and alert status history.</p></div><label><span className="label">Location</span><select className="input" value={location} onChange={(event) => setLocation(event.target.value)}><option>All locations</option>{locations.map((item) => <option key={item}>{item}</option>)}</select></label></div>
    <section className="grid grid-4 operations-performance-metrics" aria-label="Operations performance summary">
      <div className="card"><div className="metric-row"><span>Step completion</span><span className="metric-icon"><CheckCircle2 size={18}/></span></div><div className="metric">{performance.completion}%</div><span className="delta">{performance.completedSteps} of {performance.totalSteps} steps</span></div>
      <div className="card"><div className="metric-row"><span>Active alerts</span><span className="metric-icon"><BellRing size={18}/></span></div><div className="metric">{performance.activeAlerts}</div><span className="delta">{performance.resolvedAlerts} resolved in history</span></div>
      <div className={`card ${performance.overdueItems ? "performance-attention" : ""}`}><div className="metric-row"><span>Overdue work</span><span className="metric-icon"><AlertTriangle size={18}/></span></div><div className="metric">{performance.overdueItems}</div><span className="delta">Incomplete checklists and active alerts</span></div>
      <div className="card"><div className="metric-row"><span>Avg. resolution</span><span className="metric-icon"><Clock3 size={18}/></span></div><div className="metric">{performance.averageResolutionHours === null ? "—" : `${performance.averageResolutionHours}h`}</div><span className="delta">From recorded alert history</span></div>
    </section>
    <section className="operations-performance-grid">
      <div className="card"><div className="performance-card-heading"><div><h2>Location comparison</h2><p>Shared “All locations” work is included for each location.</p></div><MapPin size={20}/></div>{performance.byLocation.length ? <div className="operations-location-list">{performance.byLocation.map((item) => <article key={item.location}><div><strong>{item.location}</strong><small>{item.completedSteps} of {item.totalSteps} steps</small></div><div className="operations-location-progress"><div className="progress"><span style={{ width: `${item.completion}%` }}/></div><b>{item.completion}%</b></div><span className={item.overdueItems ? "operations-location-attention" : ""}>{item.overdueItems} overdue</span><span>{item.activeAlerts} active alerts</span></article>)}</div> : <div className="performance-empty-result"><MapPin size={28}/><strong>No location comparison available</strong><p>Add location-specific checklists or alerts to compare execution.</p></div>}</div>
      <div className="card"><div className="performance-card-heading"><div><h2>Needs attention</h2><p>Overdue work plus active high- or critical-severity alerts.</p></div><AlertTriangle size={20}/></div>{attentionItems.length ? <div className="operations-attention-list">{attentionItems.map((item) => <Link href={item.href} key={item.id}><span className={`badge ${item.type === "Alert" ? "amber" : "blue"}`}>{item.type}</span><div><strong>{item.title}</strong><small>{item.location} · Due {formatOperationsDate(item.dueDate)}</small></div></Link>)}</div> : <div className="performance-empty-result"><CheckCircle2 size={28}/><strong>No priority exceptions</strong><p>No overdue work or severe active alerts in this view.</p></div>}</div>
    </section>
    <div className="card operations-performance-method"><strong>How these numbers are calculated</strong><p>Completion equals completed checklist steps divided by all checklist steps. Overdue work includes incomplete checklists and unresolved alerts past their due date. Average resolution time uses the time between alert creation and its latest recorded resolution. RunFloor does not infer missing results.</p></div>
  </div>;
}
