"use client";
import { useMemo, useState } from "react";
import { BookOpenCheck, Plus } from "lucide-react";
import { copyPlatformProcedureTemplate } from "@/app/admin/platform/actions";

const categories = ["Sales Procedures", "Delivery & Post-Sale", "Inventory", "Service", "Parts", "CRM & Lead Management", "Customer Experience", "Management", "Employee & Administrative", "Other", "Uncategorized"];
type Template = { id:string; title:string; category:string; owner:string; summary:string; version:number };

export function PlatformProcedureTemplateLibrary({ templates, tenants }: { templates: Template[]; tenants: Array<{id:string;name:string}> }) {
  const [category,setCategory]=useState<string|null>(null); const [selectedId,setSelectedId]=useState<string|null>(null); const [selectedTenants,setSelectedTenants]=useState<string[]>([]); const [message,setMessage]=useState(""); const [error,setError]=useState(""); const [saving,setSaving]=useState(false);
  const visible=useMemo(()=>category ? templates.filter((template)=>template.category===category) : [],[templates,category]); const selected=templates.find((template)=>template.id===selectedId) || visible[0]; const orderedTenants=[...tenants].sort((a,b)=>a.name.localeCompare(b.name));
  async function apply(){if(!selected||!selectedTenants.length)return;setSaving(true);setMessage("");setError("");try{let added=0;let alreadyThere=0;for(const organizationId of selectedTenants){const form=new FormData();form.set("templateId",selected.id);form.set("organizationId",organizationId);const result=await copyPlatformProcedureTemplate(form);if(result.copied)added+=1;else alreadyThere+=1}const parts=[];if(added)parts.push(`Added “${selected.title}” to ${added} tenant${added===1?"":"s"}.`);if(alreadyThere)parts.push(`${alreadyThere} tenant${alreadyThere===1?" already has":"s already have"} this procedure.`);setMessage(parts.join(" ")||"No tenant changes were needed.");setSelectedTenants([])}catch(cause){setError(cause instanceof Error?cause.message:"The template could not be added. Please try again.")}finally{setSaving(false)}}
  return <div className="operations-procedure-workspace"><section><div className="section-heading"><div><h2>Master Procedure Templates</h2><p>Click a category to show or hide its procedures, then choose one to manage.</p></div><button className="btn btn-secondary" onClick={()=>document.getElementById("platform-template-editor")?.scrollIntoView({behavior:"smooth"})}><Plus size={16}/> Add template</button></div><div className="operations-category-list">{categories.map((name)=>{const count=templates.filter((template)=>template.category===name).length;const isOpen=category===name;return <button key={name} aria-expanded={isOpen} className={`card operations-category-card ${isOpen?"selected":""}`} onClick={()=>{setCategory(isOpen?null:name);setSelectedId(null)}}><strong>{isOpen?"⌄ ":"› "}{name}</strong><span>{count} templates · {isOpen?"Hide":"Show"}</span></button>})}</div>{category&&<div className="operations-procedure-cards">{visible.map((template)=><button key={template.id} className={`card operations-procedure-card ${selected?.id===template.id?"selected":""}`} onClick={()=>setSelectedId(template.id)}><BookOpenCheck size={18}/><h2>{template.title}</h2><p>{template.summary}</p><span>{template.owner} · v{template.version}</span></button>)}</div>}</section><aside id="platform-template-editor" className="card operations-procedure-editor">{selected?<><h2>{selected.title}</h2><p>{selected.summary}</p><p><strong>Category:</strong> {selected.category} · <strong>Owner:</strong> {selected.owner}</p><div className="form-stack"><label><input type="checkbox" checked={selectedTenants.length===orderedTenants.length} onChange={e=>setSelectedTenants(e.target.checked?orderedTenants.map(t=>t.id):[])}/> Add to all active tenants</label>{orderedTenants.map(t=><label key={t.id}><input type="checkbox" checked={selectedTenants.includes(t.id)} onChange={e=>setSelectedTenants(x=>e.target.checked?[...x,t.id]:x.filter(id=>id!==t.id))}/> {t.name}</label>)}</div><button className="btn btn-primary" disabled={!selectedTenants.length||saving} onClick={apply}>{saving?"Adding…":"Add to selected tenants"}</button>{message&&<p className="form-success">{message}</p>}{error&&<p className="form-error">{error}</p>}</>:<><h2>{category||"Choose a category"}</h2><p>{category?"No master templates in this category yet. Add one below.":"Open a category to view its procedure templates."}</p></>}</aside></div>;
}
