"use client";
import { useMemo, useState } from "react";
import { BookOpenCheck, Plus } from "lucide-react";
import { copyPlatformProcedureTemplate } from "@/app/admin/platform/actions";

const categories = ["Sales Procedures", "Delivery & Post-Sale", "Inventory", "Service", "Parts", "CRM & Lead Management", "Customer Experience", "Management", "Employee & Administrative", "Other", "Uncategorized"];
type Template = { id:string; title:string; category:string; owner:string; summary:string; version:number };

export function PlatformProcedureTemplateLibrary({ templates, tenants }: { templates: Template[]; tenants: Array<{id:string;name:string}> }) {
  const [category,setCategory]=useState(categories[0]); const [selectedId,setSelectedId]=useState<string|null>(null); const [selectedTenants,setSelectedTenants]=useState<string[]>([]); const [message,setMessage]=useState("");
  const visible=useMemo(()=>templates.filter((template)=>template.category===category),[templates,category]); const selected=templates.find((template)=>template.id===selectedId) || visible[0]; const orderedTenants=[...tenants].sort((a,b)=>a.name.localeCompare(b.name));
  async function apply(){if(!selected||!selectedTenants.length)return;for(const organizationId of selectedTenants){const form=new FormData();form.set("templateId",selected.id);form.set("organizationId",organizationId);await copyPlatformProcedureTemplate(form)}setMessage("Template added to selected tenants.")}
  return <div className="operations-procedure-workspace"><section><div className="section-heading"><div><h2>Master Procedure Templates</h2><p>Choose a category, then manage a master procedure.</p></div><button className="btn btn-secondary" onClick={()=>document.getElementById("platform-template-editor")?.scrollIntoView({behavior:"smooth"})}><Plus size={16}/> Add template</button></div><div className="operations-category-list">{categories.map((name)=><button key={name} className={`card operations-category-card ${category===name?"selected":""}`} onClick={()=>{setCategory(name);setSelectedId(null)}}><strong>{name}</strong><span>{templates.filter((template)=>template.category===name).length} templates</span></button>)}</div><div className="operations-procedure-cards">{visible.map((template)=><button key={template.id} className={`card operations-procedure-card ${selected?.id===template.id?"selected":""}`} onClick={()=>setSelectedId(template.id)}><BookOpenCheck size={18}/><h2>{template.title}</h2><p>{template.summary}</p><span>{template.owner} · v{template.version}</span></button>)}</div></section><aside id="platform-template-editor" className="card operations-procedure-editor">{selected?<><h2>{selected.title}</h2><p>{selected.summary}</p><p><strong>Category:</strong> {selected.category} · <strong>Owner:</strong> {selected.owner}</p><div className="form-stack"><label><input type="checkbox" checked={selectedTenants.length===orderedTenants.length} onChange={e=>setSelectedTenants(e.target.checked?orderedTenants.map(t=>t.id):[])}/> Add to all active tenants</label>{orderedTenants.map(t=><label key={t.id}><input type="checkbox" checked={selectedTenants.includes(t.id)} onChange={e=>setSelectedTenants(x=>e.target.checked?[...x,t.id]:x.filter(id=>id!==t.id))}/> {t.name}</label>)}</div><button className="btn btn-primary" disabled={!selectedTenants.length} onClick={apply}>Add to selected tenants</button>{message&&<p className="form-success">{message}</p>}</>:<><h2>{category}</h2><p>No master templates in this category yet. Add one below.</p></>}</aside></div>;
}
