import Link from "next/link";
import { TopScrollTable } from "@/components/top-scroll-table";
import { approveProduct, changeProductType, deleteProductModel } from "@/app/admin/competitor-sources/actions";
import { createAdminClient } from "@/lib/supabase/admin";

type Filters = { q?: string; type?: string; rvType?: string; year?: string; status?: string };

export async function RvProductModels({ organizationId, filters }: { organizationId: string; filters: Filters }) {
  const db = createAdminClient();
  const { data } = await db.from("products").select("id,name,model,manufacturer,brand,model_year,product_category,product_type,review_status,updated_at,specifications").eq("organization_id", organizationId).order("updated_at", { ascending: false }).limit(250);
  const query = (filters.q || "").trim().toLowerCase();
  const rows = (data || []).filter((product) => {
    const specifications = (product.specifications || {}) as Record<string, string>;
    const rvType = specifications.rvType || product.product_category || "";
    const floorplan = specifications.floorplan || "";
    const matchesQuery = !query || [product.name, product.model, product.manufacturer, product.brand, floorplan, specifications.productLine].filter(Boolean).join(" ").toLowerCase().includes(query);
    return matchesQuery && (!filters.type || product.product_type === filters.type) && (!filters.rvType || rvType === filters.rvType) && (!filters.year || String(product.model_year || "") === filters.year) && (!filters.status || product.review_status === filters.status);
  });
  const rvTypes = Array.from(new Set((data || []).map((product) => ((product.specifications || {}) as Record<string, string>).rvType || product.product_category).filter(Boolean))).sort();
  const years = Array.from(new Set((data || []).map((product) => product.model_year).filter((year): year is number => Boolean(year)))).sort((a, b) => b - a);

  return <section className="card" style={{ marginTop: 18 }}><div className="metric-row"><div><h2>RV Product Models</h2><p>Review and manage this RV workspace’s models. Detailed RV specifications stay in Edit.</p></div><span className="badge blue">{rows.length} shown</span></div>
    <form className="grid grid-3" method="get" style={{ margin: "16px 0" }}><input className="input" name="q" defaultValue={filters.q || ""} placeholder="Search model, manufacturer, floorplan, or product line"/><select className="input" name="type" defaultValue={filters.type || ""}><option value="">All product types</option><option value="our_product">My Products</option><option value="competitor_product">Competitors</option></select><select className="input" name="rvType" defaultValue={filters.rvType || ""}><option value="">All RV types</option>{rvTypes.map((type) => <option value={type} key={type}>{type}</option>)}</select><select className="input" name="year" defaultValue={filters.year || ""}><option value="">All years</option>{years.map((year) => <option value={year} key={year}>{year}</option>)}</select><select className="input" name="status" defaultValue={filters.status || ""}><option value="">All review statuses</option><option value="pending_review">Pending review</option><option value="approved">Approved</option></select><div style={{ display: "flex", gap: 8 }}><button className="btn btn-primary">Apply filters</button><Link className="btn btn-ghost" href="/admin/products">Clear</Link></div></form>
    <TopScrollTable><table className="table"><thead><tr><th>Type</th><th>Manufacturer</th><th>Model / Floorplan</th><th>Year</th><th>RV Type</th><th>Status</th><th>Updated</th><th>Actions</th></tr></thead><tbody>{rows.map((product) => { const specifications = (product.specifications || {}) as Record<string, string>; const rvType = specifications.rvType || product.product_category || "—"; const floorplan = specifications.floorplan; return <tr key={product.id}><td><span className={`badge ${product.product_type === "our_product" ? "green" : "blue"}`}>{product.product_type === "our_product" ? "My Product" : "Competitor"}</span></td><td>{product.manufacturer || product.brand || "—"}</td><td><strong>{product.model || product.name}</strong>{floorplan && floorplan !== product.model ? <small style={{ display: "block", color: "var(--muted)" }}>{floorplan}</small> : null}</td><td>{product.model_year || "—"}</td><td>{rvType}</td><td><span className={`badge ${product.review_status === "approved" ? "green" : "amber"}`}>{String(product.review_status || "pending_review").replaceAll("_", " ")}</span></td><td>{new Date(product.updated_at).toLocaleDateString()}</td><td><div className="product-row-actions"><Link className="btn btn-ghost status-button" href={`/admin/products/${product.id}/edit`}>Edit</Link>{product.review_status !== "approved" ? <form action={approveProduct}><input type="hidden" name="productId" value={product.id}/><button className="btn btn-ghost status-button">Approve</button></form> : null}<form action={changeProductType} style={{ display: "flex", gap: 6 }}><input type="hidden" name="productId" value={product.id}/><select className="input" name="productType" defaultValue={product.product_type} aria-label={`Change type for ${product.name}`} style={{ minWidth: 150 }}><option value="our_product">My Product</option><option value="competitor_product">Competitor</option></select><button className="btn btn-ghost status-button">Save</button></form><form action={deleteProductModel}><input type="hidden" name="productId" value={product.id}/><button className="btn btn-ghost danger-button">Delete</button></form></div></td></tr>; })}{!rows.length ? <tr><td colSpan={8}>No RV product models match these filters.</td></tr> : null}</tbody></table></TopScrollTable>
  </section>;
}
