import Link from "next/link";
import { ArrowRight, BarChart3, BookOpen, BrainCircuit, Clock3, ListChecks, MessageCircle, Settings2, ShieldCheck, Target, Trophy } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { coachSkills, type AdaptiveProfile } from "@/lib/coach/adaptive";
import styles from "@/app/coach/development/development.module.css";

const colors = ["#ff5725", "#1479df", "#0dab72", "#f3a80c", "#853bef", "#ed3563", "#14a5bf", "#ed5db7", "#145abe"];
const icons = [Target, MessageCircle, BookOpen, Trophy, ShieldCheck, MessageCircle, BrainCircuit, BarChart3, Settings2];

export function TailoredDevelopment({ profile }: { profile: AdaptiveProfile }) {
  const score = Math.max(0, Math.min(100, profile.overallScore));
  return <AppShell title="My Development" industry="rv"><main className={styles.experience}>
    <section className={styles.hero}><div><span>Persistent coaching profile</span><h1>Your development <em>plan.</em></h1><p>Practice today. Close more tomorrow.</p><div className={styles.heroPoints}><span><Target/>Build Real<br/>Sales Skills</span><span><BarChart3/>Track Progress<br/>Over Time</span><span><Trophy/>Become a<br/>Stronger Closer</span></div></div><blockquote>Same Roads.<br/>Bigger Opportunities.</blockquote><Link href="/coach/session">Start Recommended Practice <ArrowRight size={17}/></Link></section>
    <div className={styles.body}><div className={styles.summary}>
      <section className={styles.scoreCard}><h2>Overall Coaching Score</h2><div><strong className={styles.ring} style={{ "--score": `${score}%` } as React.CSSProperties}>{score ? `${score}%` : "—"}</strong><p><b>{score ? profile.trend : "Ready to grow"}</b><span>{score ? "Keep practicing to reach your next level." : "Complete a session to establish your score."}</span></p><Trophy className={styles.faint}/></div></section>
      <section className={styles.difficulty}><h2>Current Difficulty</h2><div><BarChart3/><p><strong>{profile.difficulty}</strong><span>Recommended focus:<br/>{profile.recommendedFocus}</span></p><Link href="/coach/session">Practice <ArrowRight size={13}/></Link></div></section>
      <section className={styles.history}><h2>Practice History</h2><div><span><MessageCircle/><strong>{profile.completedScenarios.length}</strong><small>Recent Sessions<br/>Completed</small></span><span><ListChecks/><strong>{profile.objectionTypes.length}</strong><small>Objection Types<br/>Practiced</small></span><span><Clock3/><strong>—</strong><small>Practice Time<br/>Not Tracked</small></span></div></section>
    </div><div className={styles.columns}><section className={styles.skills}><header><h2>Skill Development</h2><p>Your progress across key RV sales skills. Complete more sessions to grow each area.</p></header><div className={styles.skillRows}>{coachSkills.map((skill, index) => { const Icon = icons[index]; const value = Math.max(0, Math.min(100, profile.skillScores[skill] || 0)); return <div className={styles.skill} key={skill}><Icon style={{color:colors[index]}}/><span>{skill}</span><div className={styles.track}><i style={{width:`${value}%`,background:colors[index]}}/></div><strong>{value ? `${value}%` : "—"}</strong><ArrowRight size={15}/></div>; })}</div></section><aside className={styles.side}><section className={styles.focus}><h2>Focus Next</h2><div><Target/><div><strong>{profile.recommendedFocus}</strong><p>Use your current coaching focus to build stronger, more qualified customer conversations.</p><Link href="/coach/session">Practice This Skill</Link></div></div></section><section className={styles.strength}><Trophy/><div><h2>Recurring Strengths</h2><p>{profile.strengths.length ? profile.strengths.join(" · ") : "Complete a session to identify your top strengths."}</p></div></section><blockquote>“Progress isn’t about being perfect. It’s about showing up, practicing, and getting better every day.”<small>— RUNFLOOR</small></blockquote></aside></div>
    <div className={styles.quick}><Link href="/coach/session"><Target/><span><strong>Plan Next Practice</strong><small>Choose a focus and build your skills</small></span><ArrowRight/></Link><Link href="/coach/review"><BarChart3/><span><strong>View Session History</strong><small>See past sessions and key takeaways</small></span><ArrowRight/></Link><Link href="/coach/scenarios"><BookOpen/><span><strong>Explore Scenarios</strong><small>Find new situations to practice</small></span><ArrowRight/></Link><Link href="/coach/session"><Settings2/><span><strong>Adjust Practice Focus</strong><small>Select your next focus area</small></span><ArrowRight/></Link></div></div>
  </main></AppShell>;
}
