import Link from "next/link";
import { AlertTriangle, BarChart3, BookOpen, GitCompareArrows, MapPin, MessageCircle, PackageSearch, Users } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { PageHeader } from "@/components/page-header";
import { getAssistantAnalytics } from "@/lib/assistant/analytics";
import { getViewer } from "@/lib/auth/viewer";
import { getViewerIndustryTemplateKey } from "@/lib/organizations/industry";

function List({ title, items }: { title: string; items: readonly { label: string; count: number }[] }) { return <section className="card"><h2>{title}</h2>{items.length ? items.map((item) => <div className="metric-row" key={item.label}><span>{item.label}</span><strong>{item.count}</strong></div>) : <p>No activity for this period.</p>}</section>; }
export default async function AnalyticsPage({ searchParams }: { searchParams: Promise<{ view?: string; location?: string; rep?: string; days?: string }> }) {
  const params = await searchParams;
  const [data, viewer] = await Promise.all([getAssistantAnalytics(params), getViewer()]);
  const isRv = viewer ? await getViewerIndustryTemplateKey(viewer) === "rv" : false;
  if (!data.allowed) return <AppShell title="Sales Assistant Analytics" industry={isRv ? "rv" : undefined}><PageHeader eyebrow="Sales Assistant" title="Analytics unavailable" description={data.reason}/></AppShell>;
  const view = data.scope; const breadcrumb = view === "company" ? "Company" : view === "store" ? "Company > Store" : "Company > Store > Rep";
  const url = (next: Record<string, string>) => `/analytics?${new URLSearchParams({ view, days: data.days, ...next })}`; const tableRows = view === "company" ? data.stores.map((item) => ({ ...item, activity: item.users })) : data.reps.map((item) => ({ ...item, activity: 0 }));
  if (isRv) {
    const trendMax = Math.max(1, ...data.trend.map((item) => item.count));
    const topicMax = Math.max(1, ...data.topics.map((item) => item.count));
    return <AppShell title="Sales Assistant Analytics" industry="rv"><main className="rv-analytics">
      <section className="rv-analytics-hero"><div><span>Sales Assistant Analytics</span><h1>Insights That Move <em>More RVs</em></h1><p>See what your team is asking, how they&apos;re using the Sales Assistant, and where to focus for even bigger success.</p><div className="rv-analytics-benefits"><b><MessageCircle/>Real Questions<small>Real Insights</small></b><b><BarChart3/>Find Coaching<small>Opportunities</small></b><b><BookOpen/>Stronger Knowledge<small>Better Conversations</small></b><b><Users/>Help Your Team<small>Sell More RVs</small></b></div></div><blockquote>More Adventures.<br/>More Sales.</blockquote></section>
      <form className="rv-analytics-filters" method="get"><label><span>View</span><select name="view" defaultValue={view}><option value="company">Company</option><option value="store">Store</option><option value="rep">Rep</option></select></label>{view !== "rep" && <label><span>Store</span><select name="location" defaultValue={data.selectedLocation}><option value="">All authorized stores</option>{data.locations.map((location) => <option key={location.id} value={location.id}>{location.name}</option>)}</select></label>}<label><span>Period</span><select name="days" defaultValue={data.days}><option value="7">Last 7 Days</option><option value="30">Last 30 Days</option><option value="90">Last 90 Days</option></select></label><button className="btn btn-primary">Apply Filters</button></form>
      <div className="rv-analytics-metrics"><section><MessageCircle/><div><span>Total Questions</span><strong>{data.totals.questions}</strong><small>Selected period</small></div></section><section><Users/><div><span>Active Users</span><strong>{data.totals.activeUsers}</strong><small>Team participation</small></div></section><section><MessageCircle/><div><span>Questions per Rep</span><strong>{data.totals.averagePerRep}</strong><small>Average activity</small></div></section><section><AlertTriangle/><div><span>Unresolved Questions</span><strong>{data.totals.unresolved}</strong><small>Knowledge opportunities</small></div></section></div>
      <div className="rv-analytics-overview"><section className="card rv-analytics-trend"><header><div><h2>Usage Trend</h2><p>Questions asked by your team over time.</p></div><span>Last {data.days} Days</span></header>{data.trend.length ? <div className="rv-trend-chart">{data.trend.map((item) => <div key={item.label}><i style={{height:`${Math.max(8, item.count / trendMax * 100)}%`}}/><strong>{item.count}</strong><small>{item.label}</small></div>)}</div> : <p>No activity for this period.</p>}</section><section className="card rv-analytics-topics"><header><div><h2>Top Topics</h2><p>Most common question topics from your team.</p></div></header>{data.topics.length ? data.topics.map((item) => <div key={item.label}><span>{item.label}</span><i><b style={{width:`${item.count / topicMax * 100}%`}}/></i><strong>{item.count}</strong></div>) : <p>No topic activity for this period.</p>}</section></div>
      <div className="rv-analytics-cards"><section className="card"><PackageSearch/><div><h2>Product Questions</h2><p>Questions about RV models, features, or specifications.</p></div>{data.products.length ? data.products.slice(0,3).map((item) => <span key={item.label}>{item.label}<b>{item.count}</b></span>) : <small>No activity for this period.</small>}<Link href="/products">Explore Product Library →</Link></section><section className="card"><GitCompareArrows/><div><h2>Competitor Questions</h2><p>Questions about competitor models, pricing, or comparisons.</p></div>{data.competitors.length ? data.competitors.slice(0,3).map((item) => <span key={item.label}>{item.label}<b>{item.count}</b></span>) : <small>No activity for this period.</small>}<Link href="/competitors">Manage Competitors →</Link></section><section className="card"><MessageCircle/><div><h2>Top Objections</h2><p>Common customer objections your team is asking about.</p></div>{data.objections.length ? data.objections.slice(0,3).map((item) => <span key={item.label}>{item.label}<b>{item.count}</b></span>) : <small>No activity for this period.</small>}<Link href="/coach">View Coaching Resources →</Link></section></div>
      {view !== "rep" && <section className="card rv-analytics-table"><header><MapPin/><div><h2>{view === "company" ? "Store Comparison" : "Rep Usage"}</h2><p>Compare Sales Assistant activity across your authorized scope.</p></div></header><div className="table-wrap"><table className="table"><thead><tr><th>{view === "company" ? "Store" : "Rep"}</th><th>Questions</th><th>Active Users</th><th>Unresolved</th><th>Actions</th></tr></thead><tbody>{tableRows.map((item) => <tr key={item.id}><td><strong>{item.name}</strong></td><td>{item.questions}</td><td>{view === "company" ? item.activity : "—"}</td><td>—</td><td>{view === "company" ? <Link className="text-button" href={url({ view: "store", location: item.id })}>View store →</Link> : <Link className="text-button" href={url({ view: "rep", rep: item.id })}>View rep →</Link>}</td></tr>)}</tbody></table></div></section>}
      {view === "rep" && <section className="card rv-analytics-table"><h2>Recent Sales Assistant Activity</h2>{data.recent.length ? data.recent.map((item) => <div className="activity-row" key={`${item.question}-${item.created_at}`}><p><strong>{item.question}</strong><small>{item.topic} · {new Date(item.created_at).toLocaleDateString()}</small></p><span className={item.unresolved ? "badge amber" : "badge blue"}>{item.unresolved ? "Needs knowledge" : "Grounded"}</span></div>) : <p>No activity for this period.</p>}</section>}
    </main></AppShell>;
  }
  return <AppShell title="Sales Assistant Analytics"><PageHeader eyebrow={breadcrumb} title="Sales Assistant Analytics" description="Understand the questions your team asks, the knowledge they need, and where coaching can help."/>
    <form className="card" method="get" style={{ display: "flex", gap: 10, flexWrap: "wrap", alignItems: "end" }}><label><span className="label">View</span><select className="input" name="view" defaultValue={view}><option value="company">Company</option><option value="store">Store</option><option value="rep">Rep</option></select></label>{view !== "rep" && <label><span className="label">Store</span><select className="input" name="location" defaultValue={data.selectedLocation}><option value="">All authorized stores</option>{data.locations.map((location) => <option key={location.id} value={location.id}>{location.name}</option>)}</select></label>}<label><span className="label">Period</span><select className="input" name="days" defaultValue={data.days}><option value="7">Last 7 Days</option><option value="30">Last 30 Days</option><option value="90">Last 90 Days</option></select></label><button className="btn btn-primary">Apply</button></form>
    <div className="grid grid-4"><section className="card"><span>Questions</span><div className="metric">{data.totals.questions}</div></section><section className="card"><span>Active users</span><div className="metric">{data.totals.activeUsers}</div></section><section className="card"><span>Questions per rep</span><div className="metric">{data.totals.averagePerRep}</div></section><section className="card"><span>Unresolved</span><div className="metric">{data.totals.unresolved}</div></section></div>
    <div className="grid grid-2" style={{ marginTop: 18 }}><List title="Usage trend" items={data.trend}/><List title="Top topics" items={data.topics}/><List title="Product questions" items={data.products}/><List title="Competitor questions" items={data.competitors}/><List title="Top objections" items={data.objections}/><section className="card"><h2>Grounded responses</h2><div className="metric">{data.totals.grounded}</div><p>{data.totals.questions ? `${Math.round(data.totals.grounded / data.totals.questions * 100)}% grounded in approved knowledge` : "No questions in this period."}</p></section></div>
    {view !== "rep" && <section className="card" style={{ marginTop: 18 }}><h2>{view === "company" ? "Store comparison" : "Rep usage"}</h2><div className="table-wrap"><table className="table"><thead><tr><th>{view === "company" ? "Store" : "Rep"}</th><th>Questions</th><th>Active users</th><th></th></tr></thead><tbody>{tableRows.map((item) => <tr key={item.id}><td><strong>{item.name}</strong></td><td>{item.questions}</td><td>{view === "company" ? item.activity : "—"}</td><td>{view === "company" ? <Link className="text-button" href={url({ view: "store", location: item.id })}>View store</Link> : <Link className="text-button" href={url({ view: "rep", rep: item.id })}>View rep</Link>}</td></tr>)}</tbody></table></div></section>}
    {view === "rep" && <section className="card" style={{ marginTop: 18 }}><h2>Recent Sales Assistant activity</h2>{data.recent.length ? data.recent.map((item) => <div className="activity-row" key={`${item.question}-${item.created_at}`}><p><strong>{item.question}</strong><small style={{ display: "block" }}>{item.topic} · {new Date(item.created_at).toLocaleDateString()}</small></p><span className={item.unresolved ? "badge amber" : "badge blue"}>{item.unresolved ? "Needs knowledge" : "Grounded"}</span></div>) : <p>No activity for this period.</p>}</section>}
  </AppShell>;
}
