import Link from "next/link";
import { ArrowRight, BarChart3, CheckCircle2, Clock3, Lightbulb, Plus, Search, Star, UserRound, UsersRound, Wrench } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { ImprovementIntake } from "@/components/improvement-intake";
import { PageHeader } from "@/components/page-header";
import { getViewer } from "@/lib/auth/viewer";
import { getViewerIndustryTemplateKey } from "@/lib/organizations/industry";
import { getImprovementWorkspace } from "@/lib/operations/improvement-repository";
import styles from "./improvements.module.css";

export default async function ImprovementsPage() {
  const [data, viewer] = await Promise.all([getImprovementWorkspace(), getViewer()]);
  const templateKey = viewer ? await getViewerIndustryTemplateKey(viewer) : null;
  const workspaceName = viewer?.organizationName.trim().toLowerCase() || "";
  const tailored = Boolean(viewer && (templateKey === "golf-cart" || viewer.demo || workspaceName === "runfloor demo" || workspaceName === "rayne rv"));
  const isRv = templateKey === "rv" || workspaceName === "rayne rv" || (viewer?.demo && workspaceName === "runfloor rv");
  const items = data.items;
  const open = items.filter((item) => !["Verified", "Closed"].includes(item.status)).length;
  const review = items.filter((item) => item.managerDecision === "Pending").length;
  const verified = items.filter((item) => ["Verified", "Closed"].includes(item.status)).length;

  if (tailored) return <AppShell title="Help Us Improve" industry={isRv ? "rv" : undefined}><main className={styles.improvementExperience}>
    <section className={styles.hero}><div><span className={styles.eyebrow}>Process improvement</span><h1>Small Ideas.<br/><em>A Smoother Journey.</em></h1><p>Help us find what’s working, what’s not, and how we can make RunFloor an even better road for our team.</p></div><blockquote>Better<br/>People.<br/>Better<br/>Experiences.</blockquote></section>
    <div className={styles.content}>
      {data.error && <p className="form-error">{data.error}</p>}
      <section className={styles.metrics}><Metric label="Open submissions" value={open} copy="Still moving through review or action" icon={<Lightbulb/>}/><Metric label="Waiting for review" value={review} copy="Ready for a manager decision" icon={<Clock3/>}/><Metric label="Verified improvements" value={verified} copy="Results confirmed and closed" icon={<CheckCircle2/>}/><div className={`card ${styles.valueCard}`}><UsersRound/><div><strong>A stronger dealership<br/>together.</strong><p>Your feedback helps us create a better experience for our team and customers.</p></div></div></section>
      <nav className={styles.filters} aria-label="Submission filters"><span className={styles.active}>All Submissions</span><span>Open ({open})</span><span>In Review ({review})</span><span>Completed ({verified})</span><label><Search size={16}/><input className="input" placeholder="Search submissions..."/></label><select className="input" aria-label="Location"><option>All locations</option></select>{data.canManage && <Link className="btn btn-secondary" href="/operations/improvements/review"><UserRound size={16}/> Manager review</Link>}</nav>
      <div className={styles.workspace}><ImprovementIntake tailored persistence={data.persistence}/><section className={styles.submissions}><header><div><h2>Recent submissions</h2><p>Track the status of your ideas and see the impact they’re making.</p></div>{items.length > 0 && <Link className="text-button" href="/operations/improvements/dashboard">View all <ArrowRight size={14}/></Link>}</header>{items.length ? <div className="improvement-list">{items.slice(0,4).map((item)=><article className="card improvement-list-card" key={item.id}><div className="metric-row"><span className="badge">{item.status}</span><small>{new Date(item.submittedAt).toLocaleDateString()}</small></div><h2>{item.title}</h2><p>{item.description}</p><Link className="text-button" href={`/operations/improvements/${item.id}`}>View progress <ArrowRight size={14}/></Link></article>)}</div>:<div className={`output empty ${styles.empty}`}><div><Lightbulb size={38}/><h2>No submissions yet</h2><p>Be the first to share an idea, report a problem, or suggest an improvement.</p><a className="btn btn-primary" href="#share-idea"><Plus size={16}/> Share an idea</a></div></div>}</section></div>
      <section className={styles.pillars}><Pillar icon={<Wrench/>} title="Spot Problems Early" copy="Help us catch issues before they impact our customers."/><Pillar icon={<BarChart3/>} title="Drive Efficiency" copy="Your ideas help us work smarter, not harder."/><Pillar icon={<UsersRound/>} title="Stronger Team" copy="Real feedback from real people creates real change."/><Pillar icon={<Star/>} title="Better Customer Experience" copy="A better internal process leads to happier customers."/></section>
    </div>
  </main></AppShell>;

  return <AppShell title="Help Us Improve"><PageHeader eyebrow="Process improvement" title="Small observations can create meaningful change" description="Report a problem, suggest an improvement, and follow what happens next." action={<Link className="btn btn-primary" href="/operations/improvements/new"><Plus size={16}/> Help us improve</Link>}/><div className="callout operations-disclaimer"><Lightbulb size={20}/><div><strong>Simple employee experience</strong><p>Describe what you noticed in everyday language. Managers will handle the improvement-method terminology and review steps.</p></div></div>{data.error && <p className="form-error">{data.error}</p>}<section className="grid grid-3"><Metric label="Open submissions" value={open} copy="Still moving through review or action" icon={<Clock3/>}/><Metric label="Waiting for review" value={review} copy="Ready for a manager decision" icon={<UserRound/>}/><Metric label="Verified improvements" value={verified} copy="Results confirmed and closed" icon={<CheckCircle2/>}/></section>{data.canManage && <div className="improvement-page-actions"><Link className="btn btn-secondary" href="/operations/improvements/review"><UserRound size={16}/> Manager review</Link><Link className="btn btn-ghost" href="/operations/improvements/dashboard"><BarChart3 size={16}/> Improvement dashboard</Link></div>}{items.length ? <section className="improvement-list" aria-label="Improvement submissions">{items.map((item)=><article className="card improvement-list-card" key={item.id}><div className="metric-row"><span className="badge">{item.status}</span><small>{new Date(item.submittedAt).toLocaleDateString()}</small></div><h2>{item.title}</h2><p>{item.description}</p><Link className="text-button" href={`/operations/improvements/${item.id}`}>View progress <ArrowRight size={14}/></Link></article>)}</section>:<section className="card output empty"><div><Lightbulb size={28}/><h2>No submissions yet</h2><p>Report the first problem or improvement idea for your location.</p><Link className="btn btn-primary" href="/operations/improvements/new">Help us improve</Link></div></section>}</AppShell>;
}

function Metric({label,value,copy,icon}:{label:string;value:number;copy:string;icon:React.ReactNode}) { return <div className="card"><div className="metric-row"><span>{label}</span><span className="metric-icon">{icon}</span></div><div className="metric">{value}</div><p>{copy}</p></div>; }
function Pillar({icon,title,copy}:{icon:React.ReactNode;title:string;copy:string}) { return <div>{icon}<span><strong>{title}</strong><small>{copy}</small></span></div>; }
