import type { ProductDTO, ProductFamilyDTO, SalesGuideDTO } from "@/lib/products/types";

const guide = (sellingPoints: string[]): SalesGuideDTO => ({ bestFitCustomer:"A shopper comparing neighborhood transportation, comfort, features, and total ownership value.", sellingPoints, discoveryQuestions:["How many passengers do you usually carry?","Where will you drive most often?","Which comfort and technology features matter most?"], demonstrationSteps:["Confirm the customer's priorities","Walk through safety and comfort features","Demonstrate controls and storage","Review the configuration and published price"], objectionResponses:["Compare included equipment and ownership value, not only the starting price."], accessoryOpportunities:["Review compatible comfort, storage, protection, and audio accessories."], followUpNotes:"Send a concise recap of the selected model, configuration, published price, and agreed next step.", disclaimers:"Demo content only. Confirm availability, street-use requirements, fees, taxes, and final pricing with the dealership." });

const familyIds={pulse:"demo-family-activev-pulse",beyond:"demo-family-bintelli-beyond",nexus:"demo-family-bintelli-nexus",sivo:"demo-family-sivo-edge",accessories:"demo-family-accessories",warranties:"demo-family-warranties"} as const;
type Spec=[familyId:string,name:string,slug:string,model:string,price:number,sortOrder:number];
const cartDetails:Record<string,{description:string;range:string;powertrain:string;color:string;highlights:string[]}>= {
  "ActivEV Pulse":{description:"A modern street-ready electric cart with premium comfort and technology included.",range:"Powder Coated Steel",powertrain:"48V",color:"green",highlights:["10.1-inch touchscreen","Wireless phone charger","Backup camera","14-inch aluminum wheels"]},
  Beyond:{description:"A versatile neighborhood vehicle equipped for comfortable street and recreational use.",range:"Aluminum",powertrain:"48V",color:"blue",highlights:["Four-wheel hydraulic suspension","Hydraulic disc brakes","All-terrain tires","LED lighting"]},
  Nexus:{description:"A premium 72V cart with connected technology, power steering, and range-focused performance.",range:"Aluminum",powertrain:"72V",color:"navy",highlights:["72V lithium system","Power steering","13-inch infotainment display","Integrated roof fans"]},
  "SIVO Edge":{description:"A premium electric cart with an automotive-style dashboard and comfort-focused cabin.",range:"Powder Coated Steel",powertrain:"48V",color:"blue",highlights:["Dashboard cooling fans","10.1-inch touchscreen","Push-button start","Premium captain's chairs"]},
};
const specs:Spec[]=[
 [familyIds.pulse,"ActivEV Pulse","activev-pulse-2-passenger","2 Passenger",11295,0],[familyIds.pulse,"ActivEV Pulse","activev-pulse-4-forward-facing","4 Forward Facing",11495,1],[familyIds.pulse,"ActivEV Pulse","activev-pulse-6-passenger","6 Passenger",12795,2],[familyIds.pulse,"ActivEV Pulse","activev-pulse-lifted-6-passenger","Lifted 6 Passenger",13795,3],
 [familyIds.beyond,"Beyond","beyond-4-passenger-forward","4 Passenger Forward",13495,0],[familyIds.beyond,"Beyond","beyond-4-passenger-2-2","4 Passenger (2+2)",12995,1],[familyIds.beyond,"Beyond","beyond-6-passenger","6 Passenger",13995,2],
 [familyIds.nexus,"Nexus","nexus-4-passenger-forward","4 Passenger Forward",16995,0],[familyIds.nexus,"Nexus","nexus-lifted-4-passenger-facing-forward","Lifted 4 Passenger Facing Forward",18995,1],
 [familyIds.sivo,"SIVO Edge","sivo-edge-4-passenger-forward-facing","4 Passenger Forward Facing",12995,0],[familyIds.sivo,"SIVO Edge","sivo-edge-lifted-6-passenger","Lifted 6 Passenger",14495,1],
 [familyIds.accessories,"Beach Chair Holder","beach-chair-holder-standard","",195,0],[familyIds.accessories,"Beyond Side Steps - 6p","beyond-side-steps-6p-standard","",795,1],[familyIds.accessories,"Breezeasy Fan","breezeasy-fan-standard","",699,2],[familyIds.accessories,"Brush Guard","brush-guard-standard","",585,3],[familyIds.accessories,"Go Box","go-box-standard","",395,4],[familyIds.accessories,"Golf Bag Holder","golf-bag-holder-standard","",495,5],[familyIds.accessories,"Nexus / Beyond 4F Grab Bar","nexus-beyond-4f-grab-bar-standard","",495,6],[familyIds.accessories,"Rain Enclosure","rain-enclosure-standard","",495,7],[familyIds.accessories,"Rear Facing Grab Bar","rear-facing-grab-bar-standard","",495,8],[familyIds.accessories,"Soundbar 28-inch","soundbar-28-standard","",499,9],[familyIds.accessories,"Soundbar 33-inch","soundbar-33-standard","",599,10],[familyIds.accessories,"Storage Cover","storage-cover-standard","",399,11],[familyIds.accessories,"Subwoofer","subwoofer-standard","",599,12],[familyIds.accessories,"Tow Hitch","tow-hitch-standard","",445,13],[familyIds.accessories,"Under / Overglow - 4p","under-overglow-4p-standard","",465,14],[familyIds.accessories,"Under / Overglow - 6p","under-overglow-6p-standard","",495,15],
 [familyIds.warranties,"Axiom VSC Warranty","axiom-vsc-warranty-24-month","24 Month",545,0],[familyIds.warranties,"Axiom VSC Warranty","axiom-vsc-warranty-36-month","36 Month",645,1],[familyIds.warranties,"Axiom VSC Warranty","axiom-vsc-warranty-48-month","48 Month",755,2],[familyIds.warranties,"Axiom VSC Warranty","axiom-vsc-warranty-60-month","60 Month",835,3],[familyIds.warranties,"Axiom VSC Warranty","axiom-vsc-warranty-72-month","72 Month",885,4],[familyIds.warranties,"Axiom VSC Warranty","axiom-vsc-warranty-84-month","84 Month",995,5],[familyIds.warranties,"Battery & Key","battery-key-lifetime","Lifetime",395,6],[familyIds.warranties,"Gap Protection","gap-protection-1-48-months","1-48 Months",325,7],[familyIds.warranties,"Gap Protection","gap-protection-49-60-months","49-60 Months",335,8],[familyIds.warranties,"Gap Protection","gap-protection-61-72-months","61-72 Months",395,9],[familyIds.warranties,"Theft Protection","theft-protection-24-month","24 Month",195,10],[familyIds.warranties,"Theft Protection","theft-protection-36-month","36 Month",225,11],[familyIds.warranties,"Theft Protection","theft-protection-48-month","48 Month",245,12],[familyIds.warranties,"Theft Protection","theft-protection-60-month","60 Month",275,13],[familyIds.warranties,"Theft Protection","theft-protection-72-month","72 Month",295,14],[familyIds.warranties,"Tire Protection","tire-protection-36-month","36 Month",275,15],[familyIds.warranties,"Tire Protection","tire-protection-48-month","48 Month",345,16],[familyIds.warranties,"Tire Protection","tire-protection-60-month","60 Month",375,17],
];
export const demoProducts:ProductDTO[]=specs.map(([familyId,name,slug,model,price,sortOrder])=>{const cart=cartDetails[name];const highlights=cart?.highlights??[];return{id:`demo-${slug}`,familyId,name,slug,model,price,sortOrder,status:"Published",description:cart?.description??`Published ${name} option for the RunFloor demonstration catalog.`,range:cart?.range??"",seats:cart?model:"",powertrain:cart?.powertrain??"",dimensions:"",runningDistance:"",turningRadius:"",maxLoadCapacity:"",highlights,color:cart?.color??"blue",imageUrl:null,imageUrls:[],imagePaths:[],salesGuide:guide(highlights)}});
export const demoProductFamilies:ProductFamilyDTO[]=[
 [familyIds.pulse,"ActivEV Pulse","activev-pulse","Explore every ActivEV Pulse model and configuration."],[familyIds.beyond,"Bintelli Beyond","bintelli-beyond","Explore every Bintelli Beyond model and configuration."],[familyIds.nexus,"Bintelli Nexus","bintelli-nexus","Explore every Bintelli Nexus model and configuration."],[familyIds.sivo,"SIVO Edge","sivo-edge","Explore every SIVO Edge model and configuration."],[familyIds.accessories,"Accessories","accessories","Browse available accessories and add-on options."],[familyIds.warranties,"Warranties","warranties","Browse available warranty plans and coverage options."],
].map(([id,name,slug,description])=>({id,name,slug,description,imageUrl:null,imagePath:null,productCount:demoProducts.filter((product)=>product.familyId===id).length}));
