alter table public.products add column if not exists normalized_model text;
alter table public.products add column if not exists normalized_variant text;
alter table public.products add column if not exists source_url text;
alter table public.products add column if not exists source_last_checked_at timestamptz;
alter table public.products add column if not exists source_hash text;

create table public.competitor_sources (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade,
  competitor_name text not null, source_url text not null, source_type text not null default 'manufacturer_website' check (source_type in ('manufacturer_website','manual_upload','other')),
  is_active boolean not null default true, last_checked_at timestamptz, last_successful_sync_at timestamptz, sync_status text not null default 'idle', created_by uuid references public.profiles(id) on delete set null, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(organization_id, source_url)
);
create table public.competitor_product_aliases (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, product_id uuid not null references public.products(id) on delete cascade, alias text not null, normalized_alias text not null, created_at timestamptz not null default now(), unique(organization_id, normalized_alias));
create table public.competitor_sync_runs (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, source_id uuid not null references public.competitor_sources(id) on delete cascade, status text not null default 'queued', products_scanned int not null default 0, new_count int not null default 0, matched_count int not null default 0, update_count int not null default 0, duplicate_count int not null default 0, errors jsonb not null default '[]'::jsonb, initiated_by uuid references public.profiles(id) on delete set null, started_at timestamptz, completed_at timestamptz, created_at timestamptz not null default now());
create table public.competitor_sync_candidates (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, sync_run_id uuid not null references public.competitor_sync_runs(id) on delete cascade, matched_product_id uuid references public.products(id) on delete set null, source_url text not null, source_hash text not null, extracted_product jsonb not null check (jsonb_typeof(extracted_product) = 'object'), classification text not null check (classification in ('new','matched','update_available','possible_duplicate','skipped','error')), field_changes jsonb not null default '{}'::jsonb, approved_at timestamptz, approved_by uuid references public.profiles(id) on delete set null, created_at timestamptz not null default now());
create table public.competitor_product_change_history (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, product_id uuid not null references public.products(id) on delete cascade, changed_field text not null, previous_value jsonb, new_value jsonb, source_url text, change_type text not null, detected_at timestamptz not null default now(), approved_at timestamptz, approved_by uuid references public.profiles(id) on delete set null);
create index competitor_sources_org_idx on public.competitor_sources(organization_id,is_active); create index competitor_candidates_run_idx on public.competitor_sync_candidates(sync_run_id,classification); create index products_competitor_identity_idx on public.products(organization_id,brand,normalized_model,normalized_variant) where product_type='competitor_product';
alter table public.competitor_sources enable row level security; alter table public.competitor_product_aliases enable row level security; alter table public.competitor_sync_runs enable row level security; alter table public.competitor_sync_candidates enable row level security; alter table public.competitor_product_change_history enable row level security;
grant select,insert,update,delete on public.competitor_sources,public.competitor_product_aliases,public.competitor_sync_runs,public.competitor_sync_candidates,public.competitor_product_change_history to authenticated;
create policy "org members read competitor sync" on public.competitor_sources for select to authenticated using (private.is_org_member(organization_id)); create policy "leaders manage competitor sources" on public.competitor_sources for all to authenticated using (private.has_org_role(organization_id,array['tenant_admin','manager']::public.organization_role[])) with check (private.has_org_role(organization_id,array['tenant_admin','manager']::public.organization_role[]));
create policy "org members read competitor aliases" on public.competitor_product_aliases for select to authenticated using (private.is_org_member(organization_id)); create policy "leaders manage competitor aliases" on public.competitor_product_aliases for all to authenticated using (private.has_org_role(organization_id,array['tenant_admin','manager']::public.organization_role[])) with check (private.has_org_role(organization_id,array['tenant_admin','manager']::public.organization_role[]));
create policy "org members read competitor sync runs" on public.competitor_sync_runs for select to authenticated using (private.is_org_member(organization_id)); create policy "leaders manage competitor sync runs" on public.competitor_sync_runs for all to authenticated using (private.has_org_role(organization_id,array['tenant_admin','manager']::public.organization_role[])) with check (private.has_org_role(organization_id,array['tenant_admin','manager']::public.organization_role[]));
create policy "org members read competitor candidates" on public.competitor_sync_candidates for select to authenticated using (private.is_org_member(organization_id)); create policy "leaders manage competitor candidates" on public.competitor_sync_candidates for all to authenticated using (private.has_org_role(organization_id,array['tenant_admin','manager']::public.organization_role[])) with check (private.has_org_role(organization_id,array['tenant_admin','manager']::public.organization_role[]));
create policy "org members read competitor history" on public.competitor_product_change_history for select to authenticated using (private.is_org_member(organization_id)); create policy "leaders manage competitor history" on public.competitor_product_change_history for all to authenticated using (private.has_org_role(organization_id,array['tenant_admin','manager']::public.organization_role[])) with check (private.has_org_role(organization_id,array['tenant_admin','manager']::public.organization_role[]));
