import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { AppShell } from "@/components/app-shell";
import { PageHeader } from "@/components/page-header";
import { getViewer } from "@/lib/auth/viewer";
import { createClient } from "@/lib/supabase/server";
import { saveTemplateDetails, saveTemplateProduct } from "../../actions";
import { TemplateProductImporter } from "@/components/template-product-importer";
import { TemplateProductModels } from "@/components/template-product-models";

type Params = { id: string };
type Product = { id: string; family_name: string; name: string; model: string; model_year: number | null; model_variant: string; specifications: Record<string, string> | null; description: string; base_price_cents: number; range_text: string; seats_text: string; powertrain_text: string; product_type: string; manufacturer: string; product_category: string; updated_at: string };

const rvSpecificationFields = [
  ["shippingWeight", "Shipping Weight"], ["carryingCapacity", "Carrying Capacity"], ["hitchWeight", "Hitch Weight"], ["length", "Length"], ["height", "Height"], ["tireSize", "Tire Size"], ["freshWater", "Fresh Water"], ["grayWater", "Gray Water"], ["wasteWater", "Waste Water"], ["sleepingCapacity", "Sleeping Capacity"], ["numberOfPropaneTanks", "Number of Propane Tanks"], ["lpgCapacity", "LPG Capacity"], ["refrigeratorSize", "Refrigerator Size"],
] as const;

export default async function TemplateEditor({ params, searchParams }: { params: Promise<Params>; searchParams: Promise<{ edit?: string }> }) {
  const viewer = await getViewer();
  if (viewer?.role !== "platform_owner") redirect("/admin");
  const { id } = await params;
  const { edit } = await searchParams;
  const supabase = await createClient();
  const [{ data: template }, { data: products }] = await Promise.all([supabase.from("industry_templates").select("id,name,template_key,starter_configuration").eq("id", id).maybeSingle(), supabase.from("industry_template_products").select("id,family_name,name,model,model_year,model_variant,specifications,description,base_price_cents,range_text,seats_text,powertrain_text,product_type,manufacturer,product_category,updated_at").eq("industry_template_id", id).order("sort_order")]);
  if (!template) notFound();
  const config = (template.starter_configuration as { terminology?: { product?: string }; assistantInstructions?: string } | null) || {};
  const allProducts = (products || []) as Product[];
  const editingProduct = allProducts.find((product) => product.id === edit);
  const rvEditor = <form id="add-starter-product" action={saveTemplateProduct} className="card form-stack" style={{ marginTop: 12 }}><input type="hidden" name="templateId" value={template.id}/><input type="hidden" name="familyName" value="Starter Products"/><fieldset><legend>Basic Information</legend><div className="grid grid-3"><label><span className="label">Product Name</span><input className="input" name="name" required /></label><label><span className="label">Model</span><input className="input" name="model" /></label><label><span className="label">Manufacturer</span><input className="input" name="manufacturer" /></label><label><span className="label">Product Line / Series</span><input className="input" name="modelVariant" /></label><label><span className="label">Model Year</span><input className="input" name="modelYear" type="number" min="1900" max="2200" /></label><label><span className="label">Category</span><input className="input" name="productCategory" /></label><label><span className="label">Product Type</span><select className="input" name="productType" defaultValue="our_product"><option value="our_product">Our Product</option><option value="competitor_product">Competitor</option></select></label></div><label><span className="label">Description</span><textarea className="input" name="description" rows={4} /></label></fieldset><fieldset><legend>RV Specifications</legend><div className="grid grid-3">{rvSpecificationFields.map(([name, label]) => <label key={name}><span className="label">{label}</span><input className="input" name={name} /></label>)}</div></fieldset><button className="btn btn-primary">Save starter product</button></form>;
  const editor = (product?: Product) => <form id={product ? undefined : "add-starter-product"} action={saveTemplateProduct} className="grid grid-3 card" style={{ marginTop: 12 }}><input type="hidden" name="templateId" value={template.id}/>{product && <input type="hidden" name="productId" value={product.id}/>}<input className="input" name="familyName" defaultValue={product?.family_name || "Starter Products"} placeholder="Product family" required/><input className="input" name="name" defaultValue={product?.name} placeholder="Product name" required/><input className="input" name="model" defaultValue={product?.model} placeholder="Model"/><input className="input" name="basePriceCents" type="number" min="0" defaultValue={product?.base_price_cents || 0} placeholder="Price in cents"/><input className="input" name="rangeText" defaultValue={product?.range_text} placeholder="Range"/><input className="input" name="seatsText" defaultValue={product?.seats_text} placeholder="Seats"/><input className="input" name="powertrainText" defaultValue={product?.powertrain_text} placeholder="Powertrain"/><input className="input" name="manufacturer" defaultValue={product?.manufacturer} placeholder="Manufacturer"/><input className="input" name="productCategory" defaultValue={product?.product_category} placeholder="Category"/><select className="input" name="productType" defaultValue={product?.product_type || "our_product"}><option value="our_product">Our product</option><option value="competitor_product">Competitor product</option></select><textarea className="input" name="description" defaultValue={product?.description} placeholder="Description"/><button className="btn btn-primary">{product ? "Save product" : "Add starter product"}</button></form>;
  const editStarterProduct = editingProduct ? <form id="add-starter-product" action={saveTemplateProduct} className="card form-stack" style={{ marginTop: 12 }}><input type="hidden" name="templateId" value={template.id}/><input type="hidden" name="productId" value={editingProduct.id}/><input type="hidden" name="familyName" value={editingProduct.family_name}/><h3>Edit starter product</h3><div className="grid grid-3"><input className="input" name="name" defaultValue={editingProduct.name} placeholder="Product Name" required/><input className="input" name="model" defaultValue={editingProduct.model} placeholder="Model"/><input className="input" name="manufacturer" defaultValue={editingProduct.manufacturer} placeholder="Manufacturer"/><input className="input" name="modelVariant" defaultValue={editingProduct.model_variant} placeholder="Product Line / Series"/><input className="input" name="modelYear" type="number" min="1900" max="2200" defaultValue={editingProduct.model_year || ""} placeholder="Model Year"/><input className="input" name="productCategory" defaultValue={editingProduct.product_category} placeholder="Category"/><select className="input" name="productType" defaultValue={editingProduct.product_type}><option value="our_product">My Product</option><option value="competitor_product">Competitor</option></select></div><textarea className="input" name="description" defaultValue={editingProduct.description} placeholder="Description"/><button className="btn btn-primary">Save changes</button></form> : null;
  const savedRvProducts = <TemplateProductModels products={allProducts} templateId={template.id}/>;
  return <AppShell title="Template Editor"><PageHeader eyebrow="Industry template" title={template.name} description="Edit starter content here. Saved products are copied only into tenants created later."/><Link className="btn btn-ghost" href="/admin/platform">Back to Platform Admin</Link><section className="card" style={{ marginTop: 16 }}><h2>Terminology & AI instructions</h2><form action={saveTemplateDetails} className="form-stack"><input type="hidden" name="templateId" value={template.id}/><input className="input" name="productTerm" defaultValue={config.terminology?.product} placeholder="Product term, e.g. RV or Product / Service"/><textarea className="input" name="assistantInstructions" defaultValue={config.assistantInstructions} placeholder="Template-specific AI instructions" rows={5}/><button className="btn btn-primary">Save template details</button></form></section><TemplateProductImporter templateId={template.id}/><section style={{ marginTop: 20 }}><h2>Starter products</h2><p>Use generic examples. Existing tenant products are never changed.</p>{template.template_key === "rv" ? <>{editStarterProduct || rvEditor}{savedRvProducts}</> : <>{allProducts.map((product) => <div key={product.id}>{editor(product)}</div>)}{editor()}</>}</section></AppShell>;
}
